package wasmbin

import (
	"github.com/jakechampion/lang/internal/wasm/encode"
	"github.com/jakechampion/lang/internal/wasm/inst"
	"github.com/jakechampion/lang/internal/wasm/memory"
	"github.com/jakechampion/lang/internal/wasm/numeric"
)

// Preview 1 reads directly into the packed array. Locals after (reader, n):
// scratch, fd, data, count, box, error, errno. Partial reads copy into compact
// storage; the error local holds the replacement array on the success path.
func buildReaderReadChunkBytesBody(idxs map[string]uint32) []byte {
	var body []byte
	body = inst.InstLocalGet(body, 1)
	body = inst.InstI32Const(body, 0)
	body = numeric.InstI32LtS(body)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	body = inst.InstI32Const(body, 28) // WASI EINVAL
	body = inst.InstLocalSet(body, 8)
	body = emitHandleResultErr(body, idxs["__build_io_error"], idxs["__fern_alloc_rc1"], 8, 7, 6)
	body = inst.InstEnd(body)
	body = inst.InstI32Const(body, writerScratchAddr)
	body = inst.InstLocalSet(body, 2)
	body = inst.InstLocalGet(body, 0)
	body = memory.InstI32Load(body, 2, 0)
	body = inst.InstLocalSet(body, 3)
	body = inst.InstLocalGet(body, 1)
	body = inst.InstCall(body, idxs["__alloc_u8"])
	body = inst.InstLocalSet(body, 4)
	body = inst.InstLocalGet(body, 2)
	body = inst.InstLocalGet(body, 4)
	body = memory.InstI32Store(body, 2, 0)
	body = inst.InstLocalGet(body, 2)
	body = inst.InstLocalGet(body, 1)
	body = memory.InstI32Store(body, 2, 4)
	body = inst.InstLocalGet(body, 3)
	body = inst.InstLocalGet(body, 2)
	body = inst.InstI32Const(body, 1)
	body = inst.InstLocalGet(body, 2)
	body = inst.InstI32Const(body, 8)
	body = numeric.InstI32Add(body)
	body = inst.InstCall(body, idxs["wasi_fd_read"])
	body = inst.InstLocalTee(body, 8)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	body = inst.InstLocalGet(body, 4)
	body = inst.InstI32Const(body, arrHeaderBytes)
	body = numeric.InstI32Sub(body)
	body = inst.InstLocalGet(body, 1)
	body = inst.InstI32Const(body, arrHeaderBytes)
	body = numeric.InstI32Add(body)
	body = inst.InstCall(body, idxs["__free"])
	body = emitHandleResultErr(body, idxs["__build_io_error"], idxs["__fern_alloc_rc1"], 8, 7, 6)
	body = inst.InstEnd(body)
	body = inst.InstLocalGet(body, 2)
	body = memory.InstI32Load(body, 2, 8)
	body = inst.InstLocalSet(body, 5)
	body = inst.InstLocalGet(body, 5)
	body = inst.InstLocalGet(body, 1)
	body = numeric.InstI32LtU(body)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	body = inst.InstLocalGet(body, 5)
	body = inst.InstCall(body, idxs["__alloc_u8"])
	body = inst.InstLocalTee(body, 7)
	body = inst.InstLocalGet(body, 4)
	body = inst.InstLocalGet(body, 5)
	body = memory.InstMemoryCopy(body)
	body = inst.InstLocalGet(body, 4)
	body = inst.InstI32Const(body, arrHeaderBytes)
	body = numeric.InstI32Sub(body)
	body = inst.InstLocalGet(body, 1)
	body = inst.InstI32Const(body, arrHeaderBytes)
	body = numeric.InstI32Add(body)
	body = inst.InstCall(body, idxs["__free"])
	body = inst.InstLocalGet(body, 7)
	body = inst.InstLocalSet(body, 4)
	body = inst.InstEnd(body)
	body = inst.InstLocalGet(body, 4)
	body = inst.InstI32Const(body, 4)
	body = numeric.InstI32Sub(body)
	body = inst.InstLocalGet(body, 5)
	body = memory.InstI32Store(body, 2, 0)
	body = emitReaderBytesOk(body, idxs, 4, 6)
	return inst.PutFunctionBody(nil, inst.PutLocalsOneGroup(nil, 7, encode.ValtypeI32), body)
}

func emitReaderBytesOk(body []byte, idxs map[string]uint32, data, box uint32) []byte {
	body = inst.InstI32Const(body, 8)
	body = inst.InstCall(body, idxs["__fern_alloc_rc1"])
	body = inst.InstLocalTee(body, box)
	body = inst.InstI32Const(body, 0)
	body = memory.InstI32Store(body, 2, 0)
	body = inst.InstLocalGet(body, box)
	body = inst.InstLocalGet(body, data)
	body = memory.InstI32Store(body, 2, 4)
	return inst.InstLocalGet(body, box)
}

// Preview 2 returns an owned host list. Copy it directly into a byte array
// and release the list, distinguishing stream EOF from last-operation-failed.
// Locals after (reader, n): retbuf, stream, list, count, box, data, errno.
func buildReaderReadChunkBytesBodyP2(idxs map[string]uint32) []byte {
	var body []byte
	err := func(b []byte, code int32) []byte {
		b = inst.InstI32Const(b, code)
		b = inst.InstLocalSet(b, 8)
		return emitHandleResultErr(b, idxs["__build_io_error"], idxs["__fern_alloc_rc1"], 8, 7, 6)
	}
	body = inst.InstLocalGet(body, 1)
	body = inst.InstI32Const(body, 0)
	body = numeric.InstI32LtS(body)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	body = err(body, errnoInval)
	body = inst.InstEnd(body)
	body = emitClosedErrP2(body, idxs, 0, 8, 7, 6)
	body = inst.InstI32Const(body, writerScratchAddr)
	body = inst.InstLocalSet(body, 2)
	body = inst.InstLocalGet(body, 0)
	body = memory.InstI32Load(body, 2, 0)
	body = inst.InstLocalSet(body, 3)
	body = inst.InstLocalGet(body, 3)
	body = inst.InstLocalGet(body, 1)
	body = append(body, 0xAD) // i64.extend_i32_u
	body = inst.InstLocalGet(body, 2)
	body = inst.InstCall(body, idxs["wasi_io_blocking_read"])
	body = inst.InstLocalGet(body, 2)
	body = memory.InstI32Load8U(body, 0, 0)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	// stream-error tag 0 owns an error resource; tag 1 is EOF.
	body = inst.InstLocalGet(body, 2)
	body = memory.InstI32Load8U(body, 0, 4)
	body = numeric.InstI32Eqz(body)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	body = emitStreamErrorDrop(body, idxs, 2)
	body = err(body, errnoIo)
	body = inst.InstEnd(body)
	body = inst.InstI32Const(body, 0)
	body = inst.InstCall(body, idxs["__alloc_u8"])
	body = inst.InstLocalSet(body, 7)
	body = emitReaderBytesOk(body, idxs, 7, 6)
	body = inst.InstReturn(body)
	body = inst.InstEnd(body)
	body = inst.InstLocalGet(body, 2)
	body = memory.InstI32Load(body, 2, 4)
	body = inst.InstLocalSet(body, 4)
	body = inst.InstLocalGet(body, 2)
	body = memory.InstI32Load(body, 2, 8)
	body = inst.InstLocalSet(body, 5)
	body = emitReaderAdvanceP2(body, 0, 5)
	body = inst.InstLocalGet(body, 5)
	body = inst.InstCall(body, idxs["__alloc_u8"])
	body = inst.InstLocalTee(body, 7)
	body = inst.InstLocalGet(body, 4)
	body = inst.InstLocalGet(body, 5)
	body = memory.InstMemoryCopy(body)
	// An empty canonical list has no allocation to reclaim.
	body = inst.InstLocalGet(body, 5)
	body = inst.InstIfStart(body, inst.BlocktypeEmpty)
	body = inst.InstLocalGet(body, 4)
	body = inst.InstLocalGet(body, 5)
	body = inst.InstCall(body, idxs["__free"])
	body = inst.InstEnd(body)
	body = emitReaderBytesOk(body, idxs, 7, 6)
	return inst.PutFunctionBody(nil, inst.PutLocalsOneGroup(nil, 7, encode.ValtypeI32), body)
}
