//go:build linux

package strerror

import "syscall"

var hostErrnos = map[string]syscall.Errno{
	"EPERM":           syscall.EPERM,
	"ENOENT":          syscall.ENOENT,
	"ESRCH":           syscall.ESRCH,
	"EINTR":           syscall.EINTR,
	"EIO":             syscall.EIO,
	"ENXIO":           syscall.ENXIO,
	"E2BIG":           syscall.E2BIG,
	"ENOEXEC":         syscall.ENOEXEC,
	"EBADF":           syscall.EBADF,
	"ECHILD":          syscall.ECHILD,
	"EAGAIN":          syscall.EAGAIN,
	"ENOMEM":          syscall.ENOMEM,
	"EACCES":          syscall.EACCES,
	"EFAULT":          syscall.EFAULT,
	"EBUSY":           syscall.EBUSY,
	"EEXIST":          syscall.EEXIST,
	"EXDEV":           syscall.EXDEV,
	"ENODEV":          syscall.ENODEV,
	"ENOTDIR":         syscall.ENOTDIR,
	"EISDIR":          syscall.EISDIR,
	"EINVAL":          syscall.EINVAL,
	"ENFILE":          syscall.ENFILE,
	"EMFILE":          syscall.EMFILE,
	"ENOTTY":          syscall.ENOTTY,
	"ETXTBSY":         syscall.ETXTBSY,
	"EFBIG":           syscall.EFBIG,
	"ENOSPC":          syscall.ENOSPC,
	"ESPIPE":          syscall.ESPIPE,
	"EROFS":           syscall.EROFS,
	"EMLINK":          syscall.EMLINK,
	"EPIPE":           syscall.EPIPE,
	"ERANGE":          syscall.ERANGE,
	"EDEADLK":         syscall.EDEADLK,
	"ENAMETOOLONG":    syscall.ENAMETOOLONG,
	"ENOLCK":          syscall.ENOLCK,
	"ENOSYS":          syscall.ENOSYS,
	"ENOTEMPTY":       syscall.ENOTEMPTY,
	"ELOOP":           syscall.ELOOP,
	"EOVERFLOW":       syscall.EOVERFLOW,
	"EILSEQ":          syscall.EILSEQ,
	"ENOTSOCK":        syscall.ENOTSOCK,
	"EMSGSIZE":        syscall.EMSGSIZE,
	"EPROTOTYPE":      syscall.EPROTOTYPE,
	"ENOPROTOOPT":     syscall.ENOPROTOOPT,
	"EPROTONOSUPPORT": syscall.EPROTONOSUPPORT,
	"ENOTSUP":         syscall.ENOTSUP,
	"EAFNOSUPPORT":    syscall.EAFNOSUPPORT,
	"EADDRINUSE":      syscall.EADDRINUSE,
	"EADDRNOTAVAIL":   syscall.EADDRNOTAVAIL,
	"ENETDOWN":        syscall.ENETDOWN,
	"ENETUNREACH":     syscall.ENETUNREACH,
	"ENETRESET":       syscall.ENETRESET,
	"ECONNABORTED":    syscall.ECONNABORTED,
	"ECONNRESET":      syscall.ECONNRESET,
	"ENOBUFS":         syscall.ENOBUFS,
	"EISCONN":         syscall.EISCONN,
	"ENOTCONN":        syscall.ENOTCONN,
	"ETIMEDOUT":       syscall.ETIMEDOUT,
	"ECONNREFUSED":    syscall.ECONNREFUSED,
	"EHOSTUNREACH":    syscall.EHOSTUNREACH,
	"EALREADY":        syscall.EALREADY,
	"EINPROGRESS":     syscall.EINPROGRESS,
	"ESTALE":          syscall.ESTALE,
	"EDQUOT":          syscall.EDQUOT,
	"ECANCELED":       syscall.ECANCELED,
	"EOWNERDEAD":      syscall.EOWNERDEAD,
	"ENOTRECOVERABLE": syscall.ENOTRECOVERABLE,
	// Linux spells EOPNOTSUPP as ENOTSUP's alias, which Table records
	// as "no separate number" — checked as 0 here.
	"EOPNOTSUPP": 0,
}
