package mvs

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// LockFileName is the resolved-version lockfile written next to a
// manifest. Under MVS the versions are fully determined by the manifests
// + index, so the lock is not a resolution SNAPSHOT that can drift — it
// records the chosen (name, version, source) so builds are reproducible
// and offline without re-running resolution.
const LockFileName = "fern.lock"

// WriteLock writes the selected set to <dir>/fern.lock, sorted by name.
func WriteLock(dir string, sel []Selected) error {
	sorted := append([]Selected(nil), sel...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	var b strings.Builder
	b.WriteString("# generated by `fern -resolve`; do not edit by hand\n")
	for _, s := range sorted {
		b.WriteString("\n[[package]]\n")
		fmt.Fprintf(&b, "name = %q\n", s.Name)
		fmt.Fprintf(&b, "version = %q\n", s.Version.String())
		if s.Source.Path != "" {
			fmt.Fprintf(&b, "path = %q\n", filepath.ToSlash(s.Source.Path))
		} else {
			fmt.Fprintf(&b, "url = %q\n", s.Source.URL)
			fmt.Fprintf(&b, "hash = %q\n", s.Source.Hash)
		}
	}
	return os.WriteFile(filepath.Join(dir, LockFileName), []byte(b.String()), 0o644)
}

// ReadLock reads <dir>/fern.lock, returning name → Selected. Returns
// (nil, nil) when absent.
func ReadLock(dir string) (map[string]Selected, error) {
	b, err := os.ReadFile(filepath.Join(dir, LockFileName))
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	out := map[string]Selected{}
	var cur *Selected
	flush := func() error {
		if cur == nil {
			return nil
		}
		if cur.Name == "" || (cur.Version == Version{}) {
			return fmt.Errorf("%s: incomplete [[package]] entry", LockFileName)
		}
		out[cur.Name] = *cur
		cur = nil
		return nil
	}
	for ln, raw := range strings.Split(string(b), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if line == "[[package]]" {
			if err := flush(); err != nil {
				return nil, err
			}
			cur = &Selected{}
			continue
		}
		if cur == nil {
			return nil, fmt.Errorf("%s line %d: %q outside a [[package]] entry", LockFileName, ln+1, line)
		}
		eq := strings.Index(line, "=")
		if eq < 0 {
			return nil, fmt.Errorf("%s line %d: expected `key = value`", LockFileName, ln+1)
		}
		k := strings.TrimSpace(line[:eq])
		v, err := unquote(strings.TrimSpace(line[eq+1:]))
		if err != nil {
			return nil, fmt.Errorf("%s line %d: %s: %w", LockFileName, ln+1, k, err)
		}
		switch k {
		case "name":
			cur.Name = v
		case "version":
			ver, err := ParseVersion(v)
			if err != nil {
				return nil, fmt.Errorf("%s line %d: %w", LockFileName, ln+1, err)
			}
			cur.Version = ver
		case "path":
			cur.Source.Path = filepath.FromSlash(v)
		case "url":
			cur.Source.URL = v
		case "hash":
			cur.Source.Hash = v
		default:
			return nil, fmt.Errorf("%s line %d: unknown key %q", LockFileName, ln+1, k)
		}
	}
	if err := flush(); err != nil {
		return nil, err
	}
	return out, nil
}
