package coreutils

import "testing"

// TestExprParity holds coreutils/expr.fern to GNU expr.
//
// The corpus is in the shape of the utility: the option rule, then the
// grammar and its diagnostics, then each precedence level, then the
// arbitrary-precision arithmetic, then the POSIX basic regular
// expressions `:` compiles — which are the bulk of it, because the
// regexp dialect is where an implementation written from the manual
// diverges from glibc's.
// exprCases is the corpus, shared by the GNU parity gate and the
// self-host leg so neither can test something narrower than the other.
func exprCases(t *testing.T) []invocation {
	t.Helper()
	return []invocation{
		// --help and --version are options only as the SOLE argument,
		// and only spelled as a unique prefix: everywhere else they are
		// ordinary tokens of the expression.
		{name: "no arguments"},
		{name: "dashdash alone", args: []string{"--"}},
		{name: "dashdash then operand", args: []string{"--", "-1"}},
		{name: "dashdash then expression", args: []string{"--", "-1", "+", "2"}},
		{name: "dashdash then dashdash", args: []string{"--", "--"}},
		{name: "dashdash then two operands", args: []string{"--", "--", "1"}},
		{name: "dashdash then help", args: []string{"--", "--help"}},
		{name: "dashdash then version", args: []string{"--", "--version"}},
		{name: "help with an operand", args: []string{"--help", "x"}},
		{name: "help after an operand", args: []string{"x", "--help"}},
		{name: "help with a value", args: []string{"--help=x"}},
		{name: "abbreviated help with a value", args: []string{"--hel=x"}},
		{name: "help then version", args: []string{"--help", "--version"}},
		{name: "version then help", args: []string{"--version", "--help"}},
		{name: "help with an empty operand", args: []string{"--help", ""}},
		{name: "helpx is an operand", args: []string{"--helpx"}},
		{name: "upper case help is an operand", args: []string{"--HELP"}},
		{name: "unknown long is an operand", args: []string{"--foo"}},
		{name: "unknown short is an operand", args: []string{"-x"}},
		{name: "short h is an operand", args: []string{"-h"}},
		{name: "lone dash is an operand", args: []string{"-"}},
		{name: "negative number", args: []string{"-1"}},
		{name: "posix help", args: []string{"--help", "x"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix expression", args: []string{"1", "+", "2"}, env: []string{"POSIXLY_CORRECT=1"}},

		// The value, and the status that reports it.
		{name: "empty operand", args: []string{""}},
		{name: "zero", args: []string{"0"}},
		{name: "two zeros", args: []string{"00"}},
		{name: "negative zero", args: []string{"-0"}},
		{name: "negative two zeros", args: []string{"-00"}},
		{name: "many zeros", args: []string{"0000000000000000000000000000000000000"}},
		{name: "negative many zeros", args: []string{"-0000000000000000000000000000000000000"}},
		{name: "one", args: []string{"1"}},
		{name: "word", args: []string{"abc"}},
		{name: "non UTF-8 operand", args: []string{"\xff"}},
		{name: "non UTF-8 pair", args: []string{"\xff\xfe"}},

		// Syntax errors: which token each message names.
		{name: "trailing operand", args: []string{"1", "2"}},
		{name: "trailing empty operand", args: []string{"x", ""}},
		{name: "leading empty operand", args: []string{"", "x"}},
		{name: "two empty operands", args: []string{"", ""}},
		{name: "trailing quote in the operand", args: []string{"x", "it's"}},
		{name: "trailing control bytes", args: []string{"x", "a\tb\n"}},
		{name: "trailing non UTF-8", args: []string{"x", "\xff"}},
		{name: "missing right operand", args: []string{"1", "+"}},
		{name: "missing after star", args: []string{"1", "+", "2", "*"}},
		{name: "operator with no left operand", args: []string{"|", "1"}},
		{name: "open paren alone", args: []string{"("}},
		{name: "close paren alone", args: []string{")"}},
		{name: "empty parens", args: []string{"(", ")"}},
		{name: "unclosed paren", args: []string{"(", "1"}},
		{name: "unclosed paren with a word", args: []string{"(", "x"}},
		{name: "paren with a trailing operand", args: []string{"(", "1", "2"}},
		{name: "paren with a trailing operand closed", args: []string{"(", "1", "2", ")"}},
		{name: "nested unclosed paren", args: []string{"(", "(", "1", ")"}},
		{name: "close paren after an operand", args: []string{"1", ")"}},
		{name: "close paren after parens", args: []string{"(", "1", ")", "2"}},
		{name: "close paren after empty parens", args: []string{"(", ")", "2"}},
		{name: "open paren after an operand", args: []string{"1", "("}},
		{name: "paren after an operand", args: []string{"1", "(", "2", ")"}},
		{name: "close paren after an operator", args: []string{"(", "1", "+", ")"}},
		{name: "missing after paren open", args: []string{"1", "|", "(", "2"}},
		{name: "close paren after or", args: []string{"1", "|", "2", ")"}},

		// eval6: the keyword functions and `+ TOKEN`, which bind their
		// arguments at their own level rather than through arithmetic.
		{name: "length", args: []string{"length", "abc"}},
		{name: "length of empty", args: []string{"length", ""}},
		{name: "length of digits", args: []string{"length", "12345"}},
		{name: "length of non UTF-8", args: []string{"length", "\xff\xfe"}},
		{name: "length missing", args: []string{"length"}},
		{name: "length of length", args: []string{"length", "length"}},
		{name: "length of a quoted plus", args: []string{"length", "+", "a"}},
		{name: "length then plus", args: []string{"length", "abc", "+", "1"}},
		{name: "length then star", args: []string{"length", "abc", "*", "2"}},
		{name: "length then colon", args: []string{"length", "abc", ":", "a"}},
		{name: "length of parens", args: []string{"length", "(", "1", ")"}},
		{name: "length of a parenthesised sum", args: []string{"length", "(", "1", "+", "2", ")"}},
		{name: "length missing after plus", args: []string{"length", "+"}},
		{name: "quote is not a keyword", args: []string{"quote"}},
		{name: "quote with an operand", args: []string{"quote", "a"}},
		{name: "length of quote", args: []string{"length", "quote"}},
		{name: "plus quotes a keyword", args: []string{"+", "match"}},
		{name: "plus quotes length", args: []string{"+", "length"}},
		{name: "plus quotes a plus", args: []string{"+", "+"}},
		{name: "plus quotes an operand", args: []string{"+", "1"}},
		{name: "plus then plus then operand", args: []string{"+", "+", "+", "1"}},
		{name: "plus four times", args: []string{"+", "+", "+", "+"}},
		{name: "plus then trailing operand", args: []string{"+", "+", "1"}},
		{name: "plus quotes an open paren", args: []string{"(", "+", "(", ")"}},
		{name: "plus quotes a close paren", args: []string{"(", "+", ")", ")"}},
		{name: "plus quotes a close paren unclosed", args: []string{"(", "+", ")"}},
		{name: "plus quotes match then operands", args: []string{"+", "match", "a", "b"}},
		{name: "match missing both", args: []string{"match"}},
		{name: "match missing the regexp", args: []string{"match", "a"}},
		{name: "match with a trailing operand", args: []string{"match", "a", "b", "c"}},
		{name: "match", args: []string{"match", "abc", `a\(b\)`}},
		{name: "match counts", args: []string{"match", "abc", "ab"}},
		{name: "match then plus", args: []string{"match", "abc", "ab", "+", "1"}},
		{name: "index", args: []string{"index", "abc", "b"}},
		{name: "index of any", args: []string{"index", "abc", "xb"}},
		{name: "index in order of the string", args: []string{"index", "abc", "cb"}},
		{name: "index not found", args: []string{"index", "abc", "x"}},
		{name: "index of empty chars", args: []string{"index", "abc", ""}},
		{name: "index in an empty string", args: []string{"index", "", "a"}},
		{name: "index of a non UTF-8 byte", args: []string{"index", "\xff\xfe", "\xfe"}},
		{name: "index missing both", args: []string{"index"}},
		{name: "index missing the chars", args: []string{"index", "a"}},
		{name: "index with a trailing operand", args: []string{"index", "abc", "a", "b"}},
		{name: "index then plus", args: []string{"index", "abc", "c", "+", "1"}},
		{name: "index of a quoted plus", args: []string{"index", "+", "a", "b"}},
		{name: "substr", args: []string{"substr", "abc", "1", "2"}},
		{name: "substr from zero", args: []string{"substr", "abc", "0", "2"}},
		{name: "substr past the end", args: []string{"substr", "abc", "2", "10"}},
		{name: "substr negative position", args: []string{"substr", "abc", "-1", "2"}},
		{name: "substr negative length", args: []string{"substr", "abc", "1", "-1"}},
		{name: "substr zero length", args: []string{"substr", "abc", "1", "0"}},
		{name: "substr beyond the string", args: []string{"substr", "abc", "4", "1"}},
		{name: "substr last byte", args: []string{"substr", "abc", "3", "1"}},
		{name: "substr non-integer position", args: []string{"substr", "abc", "x", "1"}},
		{name: "substr non-integer length", args: []string{"substr", "abc", "1", "x"}},
		{name: "substr huge position", args: []string{"substr", "abc", "99999999999999999999", "1"}},
		{name: "substr huge length", args: []string{"substr", "abc", "1", "99999999999999999999"}},
		{name: "substr fractional position", args: []string{"substr", "abc", "1.5", "1"}},
		{name: "substr fractional length", args: []string{"substr", "abc", "1", "1.5"}},
		{name: "substr of empty", args: []string{"substr", "", "1", "1"}},
		{name: "substr of non UTF-8", args: []string{"substr", "\xff\xfe", "2", "1"}},
		{name: "substr missing all", args: []string{"substr"}},
		{name: "substr missing two", args: []string{"substr", "abc"}},
		{name: "substr missing one", args: []string{"substr", "abc", "1"}},
		{name: "substr with a trailing operand", args: []string{"substr", "abc", "1", "2", "3"}},
		{name: "substr with a quoted position", args: []string{"substr", "abc", "+", "1", "2"}},
		{name: "substr with a quoted length", args: []string{"substr", "abc", "1", "+", "2"}},
		{name: "substr then plus", args: []string{"substr", "abc", "1", "2", "+", "3"}},
		{name: "substr then plus one", args: []string{"substr", "abc", "1", "1", "+", "1"}},

		// Arithmetic, arbitrary-precision.
		{name: "sum", args: []string{"1", "+", "2"}},
		{name: "sum of quoted plus", args: []string{"1", "+", "+", "2"}},
		{name: "difference", args: []string{"1", "-", "1"}},
		{name: "difference to negative", args: []string{"0", "-", "1"}},
		{name: "difference of negatives", args: []string{"1", "-", "-1"}},
		{name: "left associative difference", args: []string{"1", "-", "1", "-", "1"}},
		{name: "product then sum", args: []string{"2", "*", "3", "+", "4"}},
		{name: "sum then product", args: []string{"2", "+", "3", "*", "4"}},
		{name: "parenthesised sum", args: []string{"(", "1", "+", "2", ")", "*", "3"}},
		{name: "unparenthesised", args: []string{"1", "+", "2", "*", "3"}},
		{name: "nested parens", args: []string{"(", "(", "1", ")", ")"}},
		{name: "quotient", args: []string{"8", "/", "2", "/", "2"}},
		{name: "negative quotient truncates", args: []string{"-7", "/", "2"}},
		{name: "remainder takes the dividend sign", args: []string{"-7", "%", "2"}},
		{name: "remainder of a negative divisor", args: []string{"7", "%", "-2"}},
		{name: "quotient of a parenthesised negative", args: []string{"(", "0", "-", "5", ")", "/", "5"}},
		{name: "divide by zero", args: []string{"2", "/", "0"}},
		{name: "modulo by zero", args: []string{"2", "%", "0"}},
		{name: "zero divided by zero", args: []string{"0", "/", "0"}},
		{name: "zero divided", args: []string{"0", "/", "5"}},
		{name: "zero modulo", args: []string{"0", "%", "5"}},
		{name: "negative zero divided", args: []string{"-0", "/", "5"}},
		{name: "negative divided by negative", args: []string{"-5", "/", "-5"}},
		{name: "leading zeros are an integer", args: []string{"05", "+", "0"}},
		{name: "negative zero is an integer", args: []string{"-0", "+", "0"}},
		{name: "many leading zeros", args: []string{"0000000000000000000000000000000000001", "+", "0"}},
		{name: "many leading zeros negative", args: []string{"-0000000000000000000000000000000000001", "+", "0"}},
		{name: "many zeros sum", args: []string{"0000000000000000000000000000000000000", "+", "0"}},
		{name: "explicit plus is not an integer", args: []string{"+5", "+", "1"}},
		{name: "leading space is not an integer", args: []string{" 5", "+", "1"}},
		{name: "trailing space is not an integer", args: []string{"5 ", "+", "1"}},
		{name: "decimal is not an integer", args: []string{"5.0", "+", "1"}},
		{name: "exponent is not an integer", args: []string{"1e3", "+", "1"}},
		{name: "empty is not an integer", args: []string{"", "+", "1"}},
		{name: "word is not an integer", args: []string{"a", "+", "b"}},
		{name: "word times a number", args: []string{"a", "*", "2"}},
		{name: "star is not an integer", args: []string{"1", "+", "*"}},
		{name: "star on the left", args: []string{"*", "+", "1"}},
		{name: "non UTF-8 is not an integer", args: []string{"\xff", "+", "1"}},
		{name: "dash is not an integer", args: []string{"-", "+", "1"}},
		{name: "dash minus dash", args: []string{"-", "-", "-"}},
		{name: "minus with a missing operand", args: []string{"-", "-"}},
		{name: "minus then minus then one", args: []string{"1", "-", "-", "1"}},
		{name: "three stars", args: []string{"*", "*", "*"}},
		{name: "big sum", args: []string{"99999999999999999999999999", "+", "1"}},
		{name: "big difference to zero", args: []string{"99999999999999999999999999", "-", "99999999999999999999999999"}},
		{name: "big product", args: []string{"99999999999999999999999", "*", "99999999999999999999999"}},
		{name: "big negation", args: []string{"-99999999999999999999999999", "*", "-1"}},
		{name: "big quotient", args: []string{"100000000000000000000", "/", "3"}},
		{name: "big remainder", args: []string{"100000000000000000000", "%", "3"}},
		{name: "big negative quotient", args: []string{"-100000000000000000000", "/", "7"}},
		{name: "big negative remainder", args: []string{"-100000000000000000000", "%", "7"}},
		{name: "big quotient by a negative", args: []string{"100000000000000000000", "/", "-7"}},
		{name: "big remainder by a negative", args: []string{"100000000000000000000", "%", "-7"}},
		{name: "past i64 max", args: []string{"9223372036854775807", "+", "1"}},
		{name: "past i64 min", args: []string{"-9223372036854775808", "-", "1"}},
		{name: "past u64 max", args: []string{"18446744073709551615", "+", "1"}},
		{name: "square of two to the sixty four", args: []string{"18446744073709551616", "*", "18446744073709551616"}},
		{name: "small over big", args: []string{"1", "/", "99999999999999999999999"}},
		{name: "negative small over big", args: []string{"-1", "/", "99999999999999999999999"}},
		{name: "negative small modulo big", args: []string{"-1", "%", "99999999999999999999999"}},
		{name: "big modulo itself", args: []string{"-99999999999999999999999", "%", "99999999999999999999999"}},

		// Comparisons: numeric when both sides look like integers,
		// byte-wise otherwise.
		{name: "less than", args: []string{"1", "<", "2"}},
		{name: "numeric less than", args: []string{"2", "<", "10"}},
		{name: "string less than", args: []string{"a", "<", "b"}},
		{name: "not less than", args: []string{"10", "<", "9"}},
		{name: "string compare when one side is not a number", args: []string{"10", "<", "9a"}},
		{name: "string compare the other way", args: []string{"9a", "<", "10"}},
		{name: "digits and a letter", args: []string{"9", "<", "1a"}},
		{name: "equal strings", args: []string{"abc", "=", "abc"}},
		{name: "numeric equality ignores leading zeros", args: []string{"1", "=", "01"}},
		{name: "double equals", args: []string{"1", "==", "01"}},
		{name: "not equal", args: []string{"1", "!=", "01"}},
		{name: "negative less than zero", args: []string{"-1", "<", "0"}},
		{name: "negative ordering", args: []string{"-1", "<", "-2"}},
		{name: "empty against a number", args: []string{"", "<", "0"}},
		{name: "empty against a word", args: []string{"", "<", "a"}},
		{name: "empty equals empty", args: []string{"", "=", ""}},
		{name: "empty against zero", args: []string{"", "=", "0"}},
		{name: "empty less than or equal", args: []string{"", "<=", ""}},
		{name: "empty greater than or equal", args: []string{"", ">=", ""}},
		{name: "empty not equal", args: []string{"", "!=", ""}},
		{name: "empty greater", args: []string{"", ">", ""}},
		{name: "case orders by byte", args: []string{"A", "<", "a"}},
		{name: "greater by case", args: []string{"a", ">", "A"}},
		{name: "not greater than itself", args: []string{"a", ">", "a"}},
		{name: "greater or equal", args: []string{"10", ">=", "10"}},
		{name: "leading zero equality", args: []string{"010", "=", "10"}},
		{name: "leading zero ordering", args: []string{"010", ">", "9"}},
		{name: "decimals compare as strings", args: []string{"1.5", "<", "1.6"}},
		{name: "decimal against an integer", args: []string{"1.5", "<", "10"}},
		{name: "explicit plus compares as a string", args: []string{"+1", "=", "1"}},
		{name: "space compares as a string", args: []string{" 1", "=", "1"}},
		{name: "one point zero", args: []string{"1.0", "=", "1"}},
		{name: "hex compares as a string", args: []string{"0x10", "=", "16"}},
		{name: "hex ordering", args: []string{"0x10", "<", "16"}},
		{name: "big comparison", args: []string{"99999999999999999999", "<", "100000000000000000000"}},
		{name: "big negative comparison", args: []string{"-99999999999999999999", "<", "-100000000000000000000"}},
		{name: "chained comparison", args: []string{"1", "<", "2", "<", "3"}},
		{name: "parenthesised comparison", args: []string{"(", "1", "<", "2", ")", "<", "3"}},
		{name: "less or equal strings", args: []string{"a", "<=", "a"}},
		{name: "prefix is less", args: []string{"abc", "<", "abcd"}},
		{name: "longer is not less", args: []string{"abcd", "<", "abc"}},
		{name: "negative zero equals zero", args: []string{"-0", "=", "0"}},
		{name: "negative zero not less", args: []string{"-0", "<", "0"}},
		{name: "two zeros equal zero", args: []string{"00", "=", "0"}},
		{name: "dash compares as a string", args: []string{"-", "<", "0"}},
		{name: "dash against a negative", args: []string{"-", "<", "-1"}},
		{name: "non UTF-8 compares unsigned", args: []string{"\xff", "<", "a"}},
		{name: "non UTF-8 ordering", args: []string{"\xff", ">", "\xfe"}},
		{name: "non UTF-8 equality", args: []string{"\xff", "=", "\xff"}},
		{name: "comparison binds looser than sum", args: []string{"2", "<", "3", "+", "4"}},

		// `|` and `&`, and the short-circuit that decides whether the
		// other side's error is ever reached.
		{name: "or takes the left", args: []string{"1", "|", "2"}},
		{name: "or takes the right", args: []string{"0", "|", "2"}},
		{name: "or of empty", args: []string{"", "|", "2"}},
		{name: "or of two zeros", args: []string{"0", "|", "0"}},
		{name: "or of two empties", args: []string{"", "|", ""}},
		{name: "or of zero and empty", args: []string{"0", "|", ""}},
		{name: "or of empty and zero", args: []string{"", "|", "0"}},
		{name: "or of two zeros digits", args: []string{"00", "|", "5"}},
		{name: "or of negative zero", args: []string{"-0", "|", "5"}},
		{name: "or of words", args: []string{"a", "|", "b"}},
		{name: "or of empty and a word", args: []string{"", "|", "a"}},
		{name: "or chains", args: []string{"1", "|", "2", "|", "3"}},
		{name: "or chains to the last", args: []string{"0", "|", "0", "|", "3"}},
		{name: "or chains to zero", args: []string{"0", "|", "", "|", ""}},
		{name: "and takes the left", args: []string{"1", "&", "2"}},
		{name: "and of a zero left", args: []string{"0", "&", "2"}},
		{name: "and of a zero right", args: []string{"1", "&", "0"}},
		{name: "and of empties", args: []string{"", "&", ""}},
		{name: "and of words", args: []string{"a", "&", "b"}},
		{name: "and chains", args: []string{"1", "&", "2", "&", "3"}},
		{name: "and binds tighter than or", args: []string{"1", "&", "2", "|", "3"}},
		{name: "and binds tighter the other way", args: []string{"0", "&", "2", "|", "3"}},
		{name: "or then and", args: []string{"1", "|", "0", "&", "3"}},
		{name: "or skips the division by zero", args: []string{"1", "|", "1", "/", "0"}},
		{name: "or skips the non-integer", args: []string{"1", "|", "abc", "/", "0"}},
		{name: "and skips the division by zero", args: []string{"0", "&", "1", "/", "0"}},
		{name: "and reaches the division by zero", args: []string{"1", "&", "1", "/", "0"}},
		{name: "and of a word reaches it", args: []string{"abc", "&", "1", "/", "0"}},
		{name: "and skips the bad operand", args: []string{"0", "&", "abc", "+", "1"}},
		{name: "or skips the bad regexp", args: []string{"1", "|", "abc", ":", `\(`}},
		{name: "and skips the bad regexp", args: []string{"0", "&", "abc", ":", `\(`}},
		{name: "and skips the match", args: []string{"0", "&", "abc", ":", ""}},
		{name: "and of empty skips the group", args: []string{"", "&", "ab", ":", `a\(b\)`}},
		{name: "or still parses the right", args: []string{"1", "|", "1", "+"}},
		{name: "or still parses a keyword", args: []string{"1", "|", "length"}},
		{name: "and still parses the right", args: []string{"0", "&", "1", "+"}},
		{name: "or of a parenthesised right", args: []string{"1", "|", "(", "2", ")"}},
		{name: "or takes a parenthesised right", args: []string{"0", "|", "(", "2", ")"}},
		{name: "or with a missing right", args: []string{"1", "|"}},
		{name: "equality chains", args: []string{"1", "=", "1", "=", "1"}},

		// `:` — anchored POSIX basic regular expressions.
		{name: "colon binds tighter than plus", args: []string{"1", "+", "2", ":", "3"}},
		{name: "colon on the right of plus", args: []string{"3", ":", "3", "+", "1"}},
		{name: "colon result times", args: []string{"abc", ":", "ab", "*", "2"}},
		{name: "colon chains", args: []string{"abc", ":", "a", ":", "x"}},
		{name: "colon with a trailing operand", args: []string{"abc", ":", "a", "b"}},
		{name: "group returns its match", args: []string{"abc", ":", `a\(b\)c`}},
		{name: "no group counts bytes", args: []string{"abc", ":", "ab"}},
		{name: "anchored at the start", args: []string{"abc", ":", "b"}},
		{name: "longer than the string", args: []string{"abc", ":", "abcd"}},
		{name: "dot star", args: []string{"abc", ":", ".*"}},
		{name: "empty regexp", args: []string{"abc", ":", ""}},
		{name: "empty against empty", args: []string{"", ":", ""}},
		{name: "star over empty", args: []string{"", ":", "a*"}},
		{name: "group that never matches", args: []string{"abc", ":", `a\(x\)*c`}},
		{name: "group skipped by the star", args: []string{"abc", ":", `a\(x\)*bc`}},
		{name: "first group of two", args: []string{"abc", ":", `\(a\)\(b\)`}},
		{name: "empty group", args: []string{"abc", ":", `a\(\)`}},
		{name: "caret at the start", args: []string{"abc", ":", "^abc"}},
		{name: "dollar at the end", args: []string{"abc", ":", "abc$"}},
		{name: "dollar without the start", args: []string{"abc", ":", "bc$"}},
		{name: "caret mid pattern is literal", args: []string{"a^b", ":", "a^b"}},
		{name: "caret mid pattern does not match", args: []string{"ab", ":", "a^b"}},
		{name: "caret after a group is literal", args: []string{"a^b", ":", `\(a\)^b`}},
		{name: "caret inside a group is an anchor", args: []string{"a^b", ":", `a\(^b\)`}},
		{name: "caret after an alternation is an anchor", args: []string{"b", ":", `a\|^b`}},
		{name: "caret after an alternation does not match a caret", args: []string{"^b", ":", `a\|^b`}},
		{name: "dollar mid pattern is literal", args: []string{"a$b", ":", "a$b"}},
		{name: "dollar mid pattern does not match", args: []string{"a$b", ":", "a$"}},
		{name: "dollar before a group close is an anchor", args: []string{"ab", ":", `\(a$\)b`}},
		{name: "dollar before an alternation is an anchor", args: []string{"a", ":", `a$\|b`}},
		{name: "two dollars", args: []string{"a$", ":", "a$$"}},
		{name: "two dollars on a bare letter", args: []string{"a", ":", "a$$"}},
		{name: "two carets", args: []string{"^", ":", "^^"}},
		{name: "caret then caret then letter", args: []string{"a", ":", "^^a"}},
		{name: "dollar at the start is literal", args: []string{"$a", ":", "$a"}},
		{name: "caret alone", args: []string{"a", ":", "^"}},
		{name: "dollar alone", args: []string{"a", ":", "$"}},
		{name: "caret dollar on empty", args: []string{"", ":", "^$"}},
		{name: "whole string anchors", args: []string{"a", ":", "^a$"}},
		{name: "whole string anchors fail", args: []string{"ab", ":", "^a$"}},
		{name: "star after a caret is literal", args: []string{"*abc", ":", "^*a"}},
		{name: "star after a caret does not match a letter", args: []string{"abc", ":", "^*a"}},
		{name: "leading star is literal", args: []string{"*a", ":", "*a"}},
		{name: "leading star does not match a letter", args: []string{"abc", ":", "*a"}},
		{name: "star after a group open is literal", args: []string{"*a", ":", `\(*a\)`}},
		{name: "star alone after a caret", args: []string{"*", ":", "^*"}},
		{name: "escaped star", args: []string{"a*", ":", `a\*`}},
		{name: "alternation", args: []string{"abc", ":", `a\|b`}},
		{name: "alternation takes the longest", args: []string{"abcd", ":", `a\|ab`}},
		{name: "alternation over groups", args: []string{"abcd", ":", `\(a\|ab\)\(c\|bcd\)`}},
		{name: "empty alternative", args: []string{"ab", ":", `a\|`}},
		{name: "leading empty alternative", args: []string{"ab", ":", `\|a`}},
		{name: "two empty alternatives", args: []string{"ab", ":", `a\|\|b`}},
		{name: "empty alternative on empty", args: []string{"", ":", `a\|`}},
		{name: "group alternation captures the last", args: []string{"ab", ":", `\(a\|b\)*`}},
		{name: "unset group in an alternation", args: []string{"b", ":", `\(a\)\|\(b\)`}},
		{name: "set group in an alternation", args: []string{"ab", ":", `\(a\)\|\(b\)`}},
		{name: "unset group before a literal", args: []string{"b", ":", `\(a\)*b`}},
		{name: "plus", args: []string{"abbc", ":", `ab\+c`}},
		{name: "question", args: []string{"ac", ":", `ab\?c`}},
		{name: "bare plus is literal", args: []string{"a+c", ":", "a+c"}},
		{name: "bare question is literal", args: []string{"a?c", ":", "a?c"}},
		{name: "bare bar is literal", args: []string{"a|c", ":", "a|c"}},
		{name: "interval exact", args: []string{"aaa", ":", `a\{2\}`}},
		{name: "interval at least", args: []string{"aaa", ":", `a\{2,\}`}},
		{name: "interval range", args: []string{"aaa", ":", `a\{1,2\}`}},
		{name: "interval up to", args: []string{"aaa", ":", `a\{,2\}`}},
		{name: "interval up to under", args: []string{"a", ":", `a\{,2\}`}},
		{name: "interval both open", args: []string{"aaa", ":", `a\{,\}`}},
		{name: "interval zero", args: []string{"", ":", `a\{0\}`}},
		{name: "interval zero then a letter", args: []string{"b", ":", `a\{0\}b`}},
		{name: "bare braces are literal", args: []string{"a{2}", ":", "a{2}"}},
		{name: "escaped braces with no atom", args: []string{"{1}", ":", `\{1\}`}},
		{name: "escaped brace with no atom does not match", args: []string{"a", ":", `\{1`}},
		{name: "escaped open brace alone", args: []string{"a", ":", `\{`}},
		{name: "escaped close brace alone", args: []string{"}", ":", `\}`}},
		{name: "escaped close brace after a letter", args: []string{"a}", ":", `a\}`}},
		{name: "escaped braces in a group", args: []string{"{1}", ":", `\(\{1\}\)`}},
		{name: "interval of an interval", args: []string{"aa", ":", `a\{1\}\{2\}`}},
		{name: "interval range of an interval", args: []string{"aaa", ":", `a\{1,2\}\{2\}`}},
		{name: "star after an interval", args: []string{"aaaa", ":", `a\{2\}*`}},
		{name: "plus after an interval", args: []string{"aa", ":", `a\{2\}\+`}},
		{name: "question after an interval", args: []string{"aa", ":", `a\{2\}\?`}},
		{name: "double star", args: []string{"aaa", ":", "a**"}},
		{name: "star then interval", args: []string{"aaa", ":", `a*\{2\}`}},
		{name: "interval at the maximum", args: []string{"aaa", ":", `a\{32767\}`}},
		{name: "interval past the maximum", args: []string{"aaa", ":", `a\{32768\}`}},
		{name: "interval count overflows", args: []string{"aaa", ":", `a\{99999999999999999999\}`}},
		{name: "interval too big", args: []string{"abc", ":", `a\{99999\}`}},
		{name: "unterminated interval", args: []string{"abc", ":", `a\{`}},
		{name: "unterminated interval with a count", args: []string{"abc", ":", `a\{1`}},
		{name: "unterminated interval with a range", args: []string{"abc", ":", `a\{1,2`}},
		{name: "decreasing interval", args: []string{"abc", ":", `a\{2,1\}`}},
		{name: "non-numeric interval", args: []string{"abc", ":", `a\{x\}`}},
		{name: "empty interval", args: []string{"aaa", ":", `a\{\}`}},
		{name: "three-part interval", args: []string{"aaa", ":", `a\{2,3,4\}`}},

		// Bracket expressions.
		{name: "bracket alone", args: []string{"abc", ":", "["}},
		{name: "bracket at the end of a pattern", args: []string{"x", ":", "x["}},
		{name: "negated bracket alone", args: []string{"x", ":", "[^"}},
		{name: "unterminated bracket", args: []string{"abc", ":", "[a"}},
		{name: "unterminated bracket with a dash", args: []string{"x", ":", "[a-"}},
		{name: "empty bracket", args: []string{"abc", ":", "[]"}},
		{name: "negated bracket with only a close", args: []string{"x", ":", "[^]"}},
		{name: "close bracket first is a member", args: []string{"abc", ":", "[]a]"}},
		{name: "negated close bracket first", args: []string{"abc", ":", "[^]a]x"}},
		{name: "close bracket member", args: []string{"]", ":", "[]]"}},
		{name: "backslash in a bracket is literal", args: []string{"\\", ":", `[\]`}},
		{name: "escaped close bracket in a bracket", args: []string{"]", ":", `[\]]`}},
		{name: "escaped close bracket does not match a letter", args: []string{"a", ":", `[\]]`}},
		{name: "dash at the end is a member", args: []string{"a-", ":", "[a-]"}},
		{name: "dash at the start is a member", args: []string{"-a", ":", "[-a]"}},
		{name: "dash only", args: []string{"-", ":", "[--]"}},
		{name: "close bracket and dash", args: []string{"]", ":", "[]-]"}},
		{name: "close bracket and dash matches a dash", args: []string{"-", ":", "[]-]"}},
		{name: "close bracket and dash does not match a letter", args: []string{"a", ":", "[]-]"}},
		{name: "negated close bracket and dash", args: []string{"a", ":", "[^]-]"}},
		{name: "range", args: []string{"b", ":", "[a-c]"}},
		{name: "single element range", args: []string{"a", ":", "[a-a]"}},
		{name: "reversed range matches nothing", args: []string{"b", ":", "[z-a]"}},
		{name: "reversed range on empty", args: []string{"", ":", "[z-a]"}},
		{name: "dash after a range", args: []string{"b", ":", "[a-b-c]"}},
		{name: "caret is a member after a close bracket", args: []string{"^", ":", "[]^]"}},
		{name: "negated caret", args: []string{"^", ":", "[^^]"}},
		{name: "negated caret matches a letter", args: []string{"a", ":", "[^^]"}},
		{name: "character class", args: []string{"abc", ":", "[[:alpha:]]*"}},
		{name: "two character classes", args: []string{"a", ":", "[[:alpha:][:digit:]]"}},
		{name: "digit class matches a digit", args: []string{"1", ":", "[[:alpha:][:digit:]]"}},
		{name: "space class", args: []string{" ", ":", "[[:space:]]"}},
		{name: "blank class", args: []string{" ", ":", "[[:blank:]]"}},
		{name: "punct class", args: []string{"!", ":", "[[:punct:]]"}},
		{name: "print class", args: []string{"a", ":", "[[:print:]]"}},
		{name: "graph class", args: []string{"a", ":", "[[:graph:]]"}},
		{name: "upper class", args: []string{"A", ":", "[[:upper:]]"}},
		{name: "lower class", args: []string{"a", ":", "[[:lower:]]"}},
		{name: "xdigit class", args: []string{"f", ":", "[[:xdigit:]]"}},
		{name: "xdigit class rejects", args: []string{"g", ":", "[[:xdigit:]]"}},
		{name: "alnum class", args: []string{"a", ":", "[[:alnum:]]"}},
		{name: "cntrl class rejects", args: []string{"ab", ":", "[[:cntrl:]]"}},
		{name: "negated class", args: []string{"a", ":", "[^[:digit:]]"}},
		{name: "unknown class name", args: []string{"abc", ":", "[[:foo:]]"}},
		{name: "upper case class name", args: []string{"a", ":", "[[:ALPHA:]]"}},
		{name: "class without the colon", args: []string{"a", ":", "[[:alpha]"}},
		{name: "class without the bracket", args: []string{"a", ":", "[[:alpha:"}},
		{name: "class opener alone", args: []string{"a", ":", "[[:"}},
		{name: "collating opener alone", args: []string{"a", ":", "[[."}},
		{name: "unterminated class in a bracket", args: []string{"abc", ":", "[[:alpha:]"}},
		{name: "collating element", args: []string{"abc", ":", "[[.a.]]"}},
		{name: "collating dash", args: []string{"a", ":", "[[.-.]]"}},
		{name: "collating range", args: []string{"b", ":", "[[.a.]-[.c.]]"}},
		{name: "collating then dash", args: []string{"a-", ":", "[[.a.]-]"}},
		{name: "multi-byte collating element", args: []string{"abc", ":", "[[.foo.]]"}},
		{name: "equivalence class", args: []string{"abc", ":", "[[=a=]]"}},
		{name: "multi-byte equivalence class", args: []string{"x", ":", "[[=ab=]]"}},
		{name: "equivalence class as a range end", args: []string{"b", ":", "[[=a=]-c]"}},
		{name: "class as a range start", args: []string{"a", ":", "[[:alpha:]-z]"}},
		{name: "class as a range end", args: []string{"a", ":", "[a-[:digit:]]"}},
		{name: "digit class as a range start", args: []string{"b", ":", "[[:digit:]-z]"}},
		{name: "bracket over a non UTF-8 byte", args: []string{"\xff", ":", "[\xff]"}},
		{name: "bracket range over non UTF-8 bytes", args: []string{"\xff\xfe", ":", "[\xfe-\xff]*"}},
		{name: "negated bracket matches a high byte", args: []string{"\xff", ":", "[^a]"}},
		{name: "interval over a bracket", args: []string{"ab", ":", `[ab]\{2\}`}},
		{name: "interval over a bracket fails", args: []string{"ab", ":", `[ab]\{3\}`}},

		// Escapes, backreferences and the GNU word operators.
		{name: "trailing backslash", args: []string{"abc", ":", "\\"}},
		{name: "trailing backslash after a letter", args: []string{"abc", ":", `a\`}},
		{name: "escaped dot", args: []string{".", ":", `\.`}},
		{name: "escaped dot does not match a letter", args: []string{"a", ":", `\.`}},
		{name: "escaped letter is the letter", args: []string{"a", ":", `\a`}},
		{name: "escaped n is the letter n", args: []string{"n", ":", `\n`}},
		{name: "escaped n does not match a letter", args: []string{"a", ":", `\n`}},
		{name: "escaped caret", args: []string{"^", ":", `\^`}},
		{name: "escaped dollar", args: []string{"$", ":", `\$`}},
		{name: "escaped caret then a letter", args: []string{"a", ":", `\^a`}},
		{name: "escaped dollar after a letter", args: []string{"a", ":", `a\$`}},
		{name: "backslash zero", args: []string{"a", ":", `\0`}},
		{name: "backslash zero against a digit", args: []string{"a0", ":", `\0`}},
		{name: "word class", args: []string{"a", ":", `\w`}},
		{name: "word class rejects", args: []string{"a", ":", `\W`}},
		{name: "underscore is a word byte", args: []string{"_", ":", `\w`}},
		{name: "space class shorthand", args: []string{" ", ":", `\s`}},
		{name: "non-space class shorthand", args: []string{"a", ":", `\S`}},
		{name: "word boundary", args: []string{"a b", ":", `a\b`}},
		{name: "word boundary inside a word", args: []string{"ab", ":", `a\b`}},
		{name: "non boundary", args: []string{"ab", ":", `a\B`}},
		{name: "word end", args: []string{"ab", ":", `a\>`}},
		{name: "word start", args: []string{"ab", ":", `\<ab`}},
		{name: "buffer end", args: []string{"a", ":", `a\'`}},
		{name: "buffer end with more text", args: []string{"a'", ":", `a\'`}},
		{name: "buffer start", args: []string{"a", ":", "\\`a"}},
		{name: "backreference", args: []string{"aa", ":", `\(a\)\1`}},
		{name: "backreference that fails", args: []string{"abc", ":", `\(a\)\1`}},
		{name: "backreference of a star", args: []string{"aa", ":", `\(a*\)\1`}},
		{name: "backreference of a star over four", args: []string{"aaaa", ":", `\(a*\)\1`}},
		{name: "backreference of a star over five", args: []string{"aaaaa", ":", `\(a*\)\1`}},
		{name: "backreference of a star over six", args: []string{"aaaaaa", ":", `\(a*\)\1`}},
		{name: "backreference of a word", args: []string{"abcabc", ":", `\(abc\)\1`}},
		{name: "backreference of a word that fails", args: []string{"abcabd", ":", `\(abc\)\1`}},
		{name: "two backreferences", args: []string{"abcab", ":", `\(a\)\(b\)c\1\2`}},
		{name: "backreference to an empty group", args: []string{"x", ":", `\(\)\1`}},
		{name: "backreference past an empty group", args: []string{"xx", ":", `\(x\)\(\)\1`}},
		{name: "backreference of a dot", args: []string{"aXa", ":", `\(.\)X\1`}},
		{name: "backreference of a dot that fails", args: []string{"aXbXc", ":", `\(.\)X\1`}},
		{name: "backreference is case sensitive", args: []string{"AA", ":", `\(a\)\1`}},
		{name: "backreference to the second group", args: []string{"abb", ":", `\(a\)\(b\)\2`}},
		{name: "backreference to the second group fails", args: []string{"ab", ":", `\(a\)\(b\)\2`}},
		{name: "backreference with no group", args: []string{"aa", ":", `\1`}},
		{name: "backreference past the group count", args: []string{"aa", ":", `\(a\)\2`}},
		{name: "backreference nine", args: []string{"a", ":", `\9`}},
		{name: "ninth backreference", args: []string{"abcdefghii", ":", `\(a\)\(b\)\(c\)\(d\)\(e\)\(f\)\(g\)\(h\)\(i\)\9`}},
		{name: "ten is one then a zero", args: []string{"abcdefghija0", ":", `\(a\)\(b\)\(c\)\(d\)\(e\)\(f\)\(g\)\(h\)\(i\)\(j\)\10`}},
		{name: "ten is one then a zero that fails", args: []string{"abcdefghij", ":", `\(a\)\(b\)\(c\)\(d\)\(e\)\(f\)\(g\)\(h\)\(i\)\(j\)\10`}},
		{name: "unmatched group open", args: []string{"abc", ":", `\(`}},
		{name: "unmatched group close", args: []string{"abc", ":", `\)`}},
		{name: "nested unmatched group open", args: []string{"a", ":", `\(\(a\)`}},
		{name: "extra group close", args: []string{"a", ":", `\(a\)\)`}},
		{name: "group close after a letter", args: []string{"a", ":", `a\)`}},

		// Greedy structure: which iteration a group reports.
		{name: "star over a group", args: []string{"abcd", ":", `\(a*\)*`}},
		{name: "star over a group before a literal", args: []string{"aab", ":", `\(a*\)*b`}},
		{name: "two stars", args: []string{"aaa", ":", `\(a*\)\(a\)`}},
		{name: "star over a single byte group", args: []string{"aaa", ":", `\(a\)*`}},
		{name: "star over a pair", args: []string{"abab", ":", `\(ab\)*`}},
		{name: "interval over a pair", args: []string{"abab", ":", `\(ab\)\{2\}`}},
		{name: "nested groups", args: []string{"abab", ":", `\(a\(b\)\)*`}},
		{name: "star over an interval", args: []string{"aaa", ":", `\(a\{1,2\}\)*`}},
		{name: "interval over a star", args: []string{"aaa", ":", `\(a*\)\{2\}`}},
		{name: "group then a starred group", args: []string{"xyz", ":", `\(x\)\(y\)*`}},
		{name: "shorter alternative first", args: []string{"aaaa", ":", `\(a\|aa\)*`}},
		{name: "longer alternative first", args: []string{"aaaa", ":", `\(aa\|a\)*`}},
		{name: "interval over a group of two", args: []string{"aaaa", ":", `\(a\{2\}\)\{2\}`}},
		{name: "interval over a group of two that fails", args: []string{"aaa", ":", `\(a\{2\}\)\{2\}`}},
		{name: "group interval range", args: []string{"aaa", ":", `\(a\)\{2,3\}`}},
		{name: "group interval zero", args: []string{"a", ":", `\(a\)\{0\}`}},
		{name: "group interval open", args: []string{"aa", ":", `\(a\)\{0,\}`}},
		{name: "group of everything", args: []string{"abc", ":", `\(.*\)c`}},
		{name: "trailing group", args: []string{"abc", ":", `.*\(.\)`}},
		{name: "two trailing groups", args: []string{"abc", ":", `\(.*\)\(c\)`}},
		{name: "star over a dot group", args: []string{"abc", ":", `\(.\)*`}},
		{name: "star over an alternation", args: []string{"abc", ":", `\(a\|b\|c\)*`}},
		{name: "dot star to the last", args: []string{"aXbXc", ":", ".*X"}},
		{name: "dot does not overshoot", args: []string{"ab", ":", "..."}},
		{name: "dot on empty", args: []string{"", ":", "."}},
		{name: "empty group on empty", args: []string{"", ":", `\(\)`}},
		{name: "nested stars need no backtracking blowup", args: []string{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", ":", `\(a*\)*\(a*\)*\(a*\)*b`}},
		{name: "star over a group to a literal", args: []string{"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy", ":", `\(x*\)*y`}},
		{name: "star over a group to a missing literal", args: []string{"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", ":", `\(x*\)*y`}},

		// The write-failure paths: expr exits 3, not 1.
		{name: "closed stdout", args: []string{"1"}, stdout: stdoutClosed},
		{name: "closed stdout with a zero value", args: []string{"0"}, stdout: stdoutClosed},
		{name: "closed stdout with a syntax error", args: []string{"1", "+"}, stdout: stdoutClosed},
		{name: "closed stdout with a bad regexp", args: []string{"abc", ":", `\(`}, stdout: stdoutClosed},
		{name: "full stdout", args: []string{"1"}, stdout: stdoutFull},
		{name: "full stdout with a zero value", args: []string{"0"}, stdout: stdoutFull},
		{name: "full stdout with a syntax error", args: []string{"1", "+"}, stdout: stdoutFull},
		{name: "full stdout with a bad regexp", args: []string{"abc", ":", `\(`}, stdout: stdoutFull},
	}
}

func TestExprParity(t *testing.T) {
	requireParity(t, "expr", exprCases(t))
}

func TestExprHelp(t *testing.T) {
	requireHelp(t, "expr", []string{"--help"}, 0)
	requireHelp(t, "expr", []string{"--hel"}, 0)
	requireHelp(t, "expr", []string{"--h"}, 0)
	requireVersion(t, "expr", []string{"--version"}, 0)
	requireVersion(t, "expr", []string{"--v"}, 0)
}
