package coreutils

import "testing"

// TestNumfmtParity holds coreutils/numfmt.fern to GNU numfmt.
//
// The corpus follows the utility: the options and their diagnostics, the
// scaling in and out, the rounding (which is where a long double's last
// digit shows), the field machinery, --format, and the stdin paths.
//
// Three invocations are deliberately absent. `numfmt -d, --from=si` on a
// field with a trailing blank reads PAST the field's terminator in GNU
// 9.4 and prints whatever follows it in memory — here, the environment
// — so there is nothing to be byte-equal to (#8533).
// numfmtCases is the corpus, shared by the GNU parity gate and the
// self-host leg so neither can test something narrower than the other.
func numfmtCases(t *testing.T) []invocation {
	t.Helper()
	return []invocation{
		// No operands and no stdin.
		{name: "no arguments"},
		{name: "dashdash alone", args: []string{"--"}},
		{name: "one operand", args: []string{"1"}},
		{name: "dashdash then operand", args: []string{"--", "1"}},
		{name: "negative operand", args: []string{"--", "-1"}},
		{name: "lone dash", args: []string{"-"}},
		{name: "empty operand", args: []string{""}},
		{name: "non UTF-8 operand", args: []string{"\xff"}},
		{name: "two operands", args: []string{"1000", "2000"}},

		// Option faults: glibc's getopt, then numfmt's own.
		{name: "unknown short", args: []string{"-x"}},
		{name: "unknown long", args: []string{"--x"}},
		{name: "short requires an argument", args: []string{"-d"}},
		{name: "long requires an argument", args: []string{"--from"}},
		{name: "to requires an argument", args: []string{"--to"}},
		{name: "round requires an argument", args: []string{"--round"}},
		{name: "field requires an argument", args: []string{"--field"}},
		{name: "invalid requires an argument", args: []string{"--invalid"}},
		{name: "delimiter requires an argument", args: []string{"--delimiter"}},
		{name: "from-unit requires an argument", args: []string{"--from-unit"}},
		{name: "to-unit requires an argument", args: []string{"--to-unit"}},
		{name: "help does not take an argument", args: []string{"--help=x"}},
		{name: "ambiguous f", args: []string{"--f", "1"}},
		{name: "ambiguous fr", args: []string{"--fr", "1"}},
		{name: "ambiguous t", args: []string{"--t", "1"}},
		{name: "ambiguous h", args: []string{"--h", "1"}},
		{name: "ambiguous de", args: []string{"--de", "1"}},
		{name: "unique del", args: []string{"--del", ",", "1"}},
		{name: "unique fi", args: []string{"--fi", "1", "1"}},
		{name: "unique fo", args: []string{"--fo", "%f", "1"}},
		{name: "unique g", args: []string{"--g", "1"}},
		{name: "unique p", args: []string{"--p", "5", "1"}},
		{name: "unique s", args: []string{"--s", "X", "1"}},
		{name: "unique z", args: []string{"--z", "1"}},
		{name: "unique head", args: []string{"--head", "1"}},
		{name: "operand before an option", args: []string{"1000", "--to=si"}},
		{name: "posix stops at the operand", args: []string{"1000", "--to=si"}, env: []string{"POSIXLY_CORRECT=1"}},

		// --from and --to.
		{name: "from si", args: []string{"--from=si", "1K"}},
		{name: "from si lower case", args: []string{"--from=si", "1k"}},
		{name: "from si M", args: []string{"--from=si", "1M"}},
		{name: "from si G", args: []string{"--from=si", "1G"}},
		{name: "from si T", args: []string{"--from=si", "1T"}},
		{name: "from si P", args: []string{"--from=si", "1P"}},
		{name: "from si E", args: []string{"--from=si", "1E"}},
		{name: "from si Z", args: []string{"--from=si", "1Z"}},
		{name: "from si Y", args: []string{"--from=si", "1Y"}},
		{name: "from si R", args: []string{"--from=si", "1R"}},
		{name: "from si Q", args: []string{"--from=si", "1Q"}},
		{name: "from si unknown letter", args: []string{"--from=si", "1X"}},
		{name: "from si with a B", args: []string{"--from=si", "1KB"}},
		{name: "from si with an i", args: []string{"--from=si", "1Ki"}},
		{name: "from si fraction", args: []string{"--from=si", "1.5K"}},
		{name: "from si two fraction digits", args: []string{"--from=si", "1.55K"}},
		{name: "from si three fraction digits", args: []string{"--from=si", "1.555K"}},
		{name: "from si four fraction digits", args: []string{"--from=si", "1.5555K"}},
		{name: "from si leading point", args: []string{"--from=si", ".5K"}},
		{name: "from si trailing point", args: []string{"--from=si", "5.K"}},
		{name: "from si exponent", args: []string{"--from=si", "1e3"}},
		{name: "from si hex", args: []string{"--from=si", "0x10"}},
		{name: "from si digit after the unit", args: []string{"--from=si", "1K2"}},
		{name: "from si bare unit", args: []string{"--from=si", "K"}},
		{name: "from si empty", args: []string{"--from=si", ""}},
		{name: "from si comma", args: []string{"--from=si", "1,5K"}},
		{name: "from si explicit plus", args: []string{"--from=si", "+1K"}},
		{name: "from si leading blank", args: []string{"--from=si", " 1K"}},
		{name: "from si blank before the unit", args: []string{"--from=si", "1 K"}},
		{name: "from si negative", args: []string{"--from=si", "--", "-1K"}},
		{name: "from si negative fraction", args: []string{"--from=si", "--", "-1.5K"}},
		{name: "from iec", args: []string{"--from=iec", "1K"}},
		{name: "from iec with an i", args: []string{"--from=iec", "1Ki"}},
		{name: "from iec with iB", args: []string{"--from=iec", "1KiB"}},
		{name: "from iec M", args: []string{"--from=iec", "1M"}},
		{name: "from iec-i", args: []string{"--from=iec-i", "1Ki"}},
		{name: "from iec-i without the i", args: []string{"--from=iec-i", "1K"}},
		{name: "from iec-i Mi", args: []string{"--from=iec-i", "1Mi"}},
		{name: "from iec-i with a B", args: []string{"--from=iec-i", "1KiB"}},
		{name: "from auto K", args: []string{"--from=auto", "1K"}},
		{name: "from auto Ki", args: []string{"--from=auto", "1Ki"}},
		{name: "from auto KiB", args: []string{"--from=auto", "1KiB"}},
		{name: "from auto KB", args: []string{"--from=auto", "1KB"}},
		{name: "from auto M", args: []string{"--from=auto", "1M"}},
		{name: "from auto Mi", args: []string{"--from=auto", "1Mi"}},
		{name: "from auto plain", args: []string{"--from=auto", "1"}},
		{name: "from auto bare i", args: []string{"--from=auto", "1i"}},
		{name: "from auto B", args: []string{"--from=auto", "1B"}},
		{name: "from si B", args: []string{"--from=si", "1B"}},
		{name: "from none with a unit", args: []string{"--from=none", "1K"}},
		{name: "from unknown", args: []string{"--from=foo", "1"}},
		{name: "from prefix s", args: []string{"--from=s", "1"}},
		{name: "from upper case", args: []string{"--from=SI", "1K"}},
		{name: "from empty", args: []string{"--from=", "1"}},
		{name: "from prefix i is ambiguous", args: []string{"--from=i", "1"}},
		{name: "from prefix iec is exact", args: []string{"--from=iec", "1K"}},
		{name: "to unknown", args: []string{"--to=foo", "1"}},
		{name: "to none", args: []string{"--to=none", "1"}},
		{name: "to has no auto", args: []string{"--to=auto", "1"}},
		{name: "to si", args: []string{"--to=si", "1000"}},
		{name: "to si million", args: []string{"--to=si", "1000000"}},
		{name: "to si and from si", args: []string{"--to=si", "--from=si", "1K"}},
		{name: "to si from iec", args: []string{"--to=si", "--from=iec", "1K"}},
		{name: "to iec from si", args: []string{"--to=iec", "--from=si", "1K"}},
		{name: "to si rejects a suffix", args: []string{"--to=si", "1K"}},

		// The scaling ladder and its rounding.
		{name: "to si 1500", args: []string{"--to=si", "1500"}},
		{name: "to si 1501", args: []string{"--to=si", "1501"}},
		{name: "to si 1499", args: []string{"--to=si", "1499"}},
		{name: "to si 999", args: []string{"--to=si", "999"}},
		{name: "to si 1", args: []string{"--to=si", "1"}},
		{name: "to si 0", args: []string{"--to=si", "0"}},
		{name: "to si 999999", args: []string{"--to=si", "999999"}},
		{name: "to si 999500", args: []string{"--to=si", "999500"}},
		{name: "to si 1023", args: []string{"--to=si", "1023"}},
		{name: "to iec 1023", args: []string{"--to=iec", "1023"}},
		{name: "to iec 1024", args: []string{"--to=iec", "1024"}},
		{name: "to iec 1025", args: []string{"--to=iec", "1025"}},
		{name: "to iec 1536", args: []string{"--to=iec", "1536"}},
		{name: "to iec 1000", args: []string{"--to=iec", "1000"}},
		{name: "to iec-i 1024", args: []string{"--to=iec-i", "1024"}},
		{name: "to iec-i 1000", args: []string{"--to=iec-i", "1000"}},
		{name: "to iec-i mega", args: []string{"--to=iec-i", "1048576"}},
		{name: "to iec-i two mega", args: []string{"--to=iec-i", "2000000"}},
		{name: "to iec tera", args: []string{"--to=iec", "1099511627776"}},
		{name: "to iec zetta", args: []string{"--to=iec", "1180591620717411303424"}},
		{name: "to iec past zetta", args: []string{"--to=iec", "1180591620717411303424000"}},
		{name: "to si exponent is not a number", args: []string{"--to=si", "1e3"}},
		{name: "to si 999 point 9", args: []string{"--to=si", "999.9"}},
		{name: "to si 1000 point 1", args: []string{"--to=si", "1000.1"}},
		{name: "to si 1000 point 5", args: []string{"--to=si", "1000.5"}},
		{name: "to si carries", args: []string{"--to=si", "1049", "1050", "1051", "1099", "1100"}},
		{name: "to si carries to two", args: []string{"--to=si", "1949", "1950", "1951"}},
		{name: "to si drops the decimal", args: []string{"--to=si", "9949", "9950", "9951", "9999", "10000"}},
		{name: "to si tens", args: []string{"--to=si", "10049", "10050", "10051", "10499", "10500", "10501"}},
		{name: "to si hundreds", args: []string{"--to=si", "99949", "99950", "99951", "100000", "100499", "100500", "100501"}},
		{name: "to si ladder", args: []string{"--to=si", "999999", "9999999", "99999999", "999999999", "1000000000"}},
		{name: "to si digits", args: []string{"--to=si", "123456789", "12345678", "1234567", "123456", "12345", "1234", "123", "12"}},
		{name: "to si fractions", args: []string{"--to=si", "1.1", "1.9", "0.1", "0.5", "0.9", "0.99", "0.01", "0.001"}},
		{name: "to si halves", args: []string{"--to=si", "0.5", "1.5", "2.5", "3.5", "8.5", "9.5"}},
		{name: "to si negative fractions", args: []string{"--to=si", "--", "-0.5", "-0.1", "-0"}},
		{name: "to si explicit plus", args: []string{"--to=si", "+1"}},
		{name: "to si negative zero point zero", args: []string{"--to=si", "--", "-0.0"}},
		{name: "to si negatives", args: []string{"--to=si", "--", "-1500", "-1501", "-1499", "-999"}},
		{name: "to si big", args: []string{"--to=si", "12345678901234567890", "99999999999999999999", "1000000000000000000000"}},
		{name: "to si quetta", args: []string{"--to=si", "123456789012345678901234567890123"}},
		{name: "to si past quetta", args: []string{"--to=si", "999999999999999999999999999999999"}},
		{name: "to si 32 digits", args: []string{"--to=si", "12345678901234567890123456789012"}},
		{name: "to si 33 digits", args: []string{"--to=si", "99999999999999999999999999999999"}},
		{name: "to si 34 digits", args: []string{"--to=si", "1234567890123456789012345678901234"}},
		{name: "to si 35 digits", args: []string{"--to=si", "12345678901234567890123456789012345"}},
		{name: "to si 36 digits", args: []string{"--to=si", "999999999999999999999999999999999999"}},
		{name: "unscaled 34 digits", args: []string{"1234567890123456789012345678901234"}},
		{name: "unscaled 34 fraction digits", args: []string{"0.1234567890123456789012345678901234"}},
		{name: "to si tiny", args: []string{"--to=si", "0.000000000000000000000000000001"}},
		{name: "to si exa", args: []string{"--to=si", "1234567890123456789"}},
		{name: "to si past exa", args: []string{"--to=si", "123456789012345678901"}},
		{name: "to iec exa", args: []string{"--to=iec", "1234567890123456789"}},

		// The unscaled path and what it refuses to print.
		{name: "keeps the written precision", args: []string{"1.5", "1.50", "1.500", "1.0", "00001", "0001.5000", "0.0000"}},
		{name: "leading point", args: []string{".5"}},
		{name: "trailing point", args: []string{"5."}},
		{name: "point alone", args: []string{"."}},
		{name: "zero point", args: []string{"0."}},
		{name: "nineteen digits", args: []string{"9999999999999999999"}},
		{name: "twenty digits", args: []string{"10000000000000000000"}},
		{name: "twenty nines", args: []string{"99999999999999999999"}},
		{name: "eighteen fraction digits", args: []string{"0.000000000000000001"}},
		{name: "nineteen fraction digits", args: []string{"0.0000000000000000001"}},
		{name: "ten point seventeen", args: []string{"10.00000000000000001"}},
		{name: "hundred point seventeen", args: []string{"100.00000000000000001"}},
		{name: "tenth to nineteen places", args: []string{"0.1000000000000000001"}},
		{name: "eighteen digits and a fraction", args: []string{"999999999999999999.9"}},
		{name: "nineteen digits and a fraction", args: []string{"9999999999999999999.9"}},

		// --round.
		{name: "round up", args: []string{"--round=up", "--to=si", "1001", "1000", "1500", "1499", "1450", "1451"}},
		{name: "round down", args: []string{"--round=down", "--to=si", "1999", "1950", "1000", "999", "9999", "10999"}},
		{name: "round down big", args: []string{"--round=down", "--to=si", "999999", "999950", "999999999", "1023"}},
		{name: "round down iec", args: []string{"--round=down", "--to=iec", "1023", "1024", "2047"}},
		{name: "round from zero", args: []string{"--round=from-zero", "--to=si", "1001"}},
		{name: "round towards zero", args: []string{"--round=towards-zero", "--to=si", "1999", "9999", "99999", "999999"}},
		{name: "round nearest", args: []string{"--round=nearest", "--to=si", "1050", "1049", "1051", "1150", "1250", "1350", "1450", "1550"}},
		{name: "round nearest tens", args: []string{"--round=nearest", "--to=si", "10500", "11500", "12500", "9950", "9949", "9500", "9499"}},
		{name: "round nearest carries", args: []string{"--round=nearest", "--to=si", "999500", "999499", "999999"}},
		{name: "round nearest unscaled", args: []string{"--round=nearest", "--", "-1050"}},
		{name: "round nearest negatives", args: []string{"--round=nearest", "--to=si", "--", "-1050", "-1150", "-1250"}},
		{name: "round up negatives", args: []string{"--round=up", "--to=si", "--", "-1001", "-1999"}},
		{name: "round down negatives", args: []string{"--round=down", "--to=si", "--", "-1001", "-1999"}},
		{name: "round from zero negative", args: []string{"--round=from-zero", "--to=si", "--", "-1001"}},
		{name: "round towards zero negative", args: []string{"--round=towards-zero", "--to=si", "--", "-1999", "-999.9"}},
		{name: "round negative fractions", args: []string{"--round=up", "--to=si", "--", "-999.9"}},
		{name: "round down negative fraction", args: []string{"--round=down", "--to=si", "--", "-999.9"}},
		{name: "round nearest negative fractions", args: []string{"--round=nearest", "--to=si", "--", "-999.9", "-999.5", "-999.4", "-0.5", "-1.5", "-2.5"}},
		{name: "round nearest keeps precision", args: []string{"--round=nearest", "0.5", "1.5", "2.5", "3.5"}},
		{name: "round nearest negative half", args: []string{"--round=nearest", "--", "-0.5"}},
		{name: "round up keeps precision", args: []string{"--round=up", "0.5", "0.1", "0.0000001", "0", "0.0"}},
		{name: "round up tiny", args: []string{"--round=up", "0.000000000000000000001"}},
		{name: "round down long fractions", args: []string{"--round=down", "0.9", "0.999999999999999999", "0.99999999999999999", "0.9999999999999999"}},
		{name: "round down too long", args: []string{"--round=down", "0.9999999999999999999"}},
		{name: "round down big and long", args: []string{"--round=down", "999999999999999999.9"}},
		{name: "round up long fractions", args: []string{"--round=up", "1.000000000000000001", "1.00000000000000001", "1.0000000000000001"}},
		{name: "round up too long", args: []string{"--round=up", "1.0000000000000000001"}},
		{name: "round up big", args: []string{"--round=up", "100000000000000000.1"}},
		{name: "round up big and long", args: []string{"--round=up", "1000000000000000000.1"}},
		{name: "round unknown", args: []string{"--round=x", "1"}},
		{name: "round empty", args: []string{"--round=", "1"}},
		{name: "round prefixes", args: []string{"--round=u", "1"}},
		{name: "round prefix to is ambiguous", args: []string{"--round=to", "1"}},
		{name: "round prefix t", args: []string{"--round=t", "1"}},
		{name: "round prefix f", args: []string{"--round=f", "1"}},
		{name: "round prefix n", args: []string{"--round=n", "1"}},
		{name: "round prefix d", args: []string{"--round=d", "1"}},
		{name: "round nearest halves at a precision", args: []string{"--round=nearest", "--format=%.3f", "0.0005", "0.0015", "0.0025"}},
		{name: "round nearest halves at two places", args: []string{"--round=nearest", "--format=%.2f", "0.005", "0.015", "1.005", "1.045"}},
		{name: "round nearest half at one place", args: []string{"--round=nearest", "--format=%.1f", "0.05"}},
		{name: "round nearest halves past one", args: []string{"--round=nearest", "--format=%.3f", "1.0005", "2.0005"}},

		// --from-unit and --to-unit.
		{name: "from-unit", args: []string{"--from-unit=1000", "1"}},
		{name: "from-unit with to", args: []string{"--from-unit=1000", "--to=si", "1"}},
		{name: "from-unit iec", args: []string{"--from-unit=1024", "--to=iec", "1"}},
		{name: "from-unit three", args: []string{"--from-unit=3", "7"}},
		{name: "from-unit with a suffix", args: []string{"--from-unit=1K", "1"}},
		{name: "from-unit iec suffix", args: []string{"--from-unit=1Ki", "1"}},
		{name: "from-unit with a B", args: []string{"--from-unit=1KiB", "1"}},
		{name: "from-unit zero", args: []string{"--from-unit=0", "1"}},
		{name: "from-unit negative", args: []string{"--from-unit=-1", "1"}},
		{name: "from-unit word", args: []string{"--from-unit=x", "1"}},
		{name: "from-unit empty", args: []string{"--from-unit=", "1"}},
		{name: "from-unit fraction", args: []string{"--from-unit=1.5", "1"}},
		{name: "from-unit exponent", args: []string{"--from-unit=1e3", "1"}},
		{name: "from-unit too big", args: []string{"--from-unit=99999999999999999999", "1"}},
		{name: "from-unit eighteen digits", args: []string{"--from-unit=999999999999999999", "1"}},
		{name: "from-unit nineteen digits", args: []string{"--from-unit=9999999999999999999", "1"}},
		{name: "from-unit u64 max", args: []string{"--from-unit=18446744073709551615", "1"}},
		{name: "from-unit past u64", args: []string{"--from-unit=18446744073709551616", "1"}},
		{name: "from-unit i64 max", args: []string{"--from-unit=9223372036854775807", "1"}},
		{name: "from-unit past i64", args: []string{"--from-unit=9223372036854775808", "1"}},
		{name: "from-unit quetta", args: []string{"--from-unit=1Q", "1"}},
		{name: "from-unit exa", args: []string{"--from-unit=1E", "1"}},
		{name: "from-unit exabyte", args: []string{"--from-unit=1EB", "1"}},
		{name: "from-unit plus", args: []string{"--from-unit=+5", "10"}},
		{name: "from-unit leading blank", args: []string{"--from-unit= 5", "10"}},
		{name: "from-unit trailing letter", args: []string{"--from-unit=5x", "10"}},
		{name: "to-unit", args: []string{"--to-unit=1000", "1000", "1500", "1499", "999", "1"}},
		{name: "to-unit rounds", args: []string{"--to-unit=1000", "--round=down", "1999"}},
		{name: "to-unit nearest", args: []string{"--to-unit=1000", "--round=nearest", "1500", "2500"}},
		{name: "to-unit three", args: []string{"--to-unit=3", "7", "8", "9"}},
		{name: "to-unit zero", args: []string{"--to-unit=0", "1"}},
		{name: "to-unit word", args: []string{"--to-unit=x", "1"}},
		{name: "to-unit suffix", args: []string{"--to-unit=1K", "1000"}},
		{name: "to-unit iec suffix", args: []string{"--to-unit=1Ki", "1024", "1000"}},
		{name: "to-unit exa", args: []string{"--to-unit=1E", "1"}},
		{name: "to-unit quetta", args: []string{"--to-unit=1Q", "1"}},
		{name: "to-unit with to", args: []string{"--to-unit=1000", "--to=si", "1000000", "1000", "1500", "1"}},
		{name: "both units", args: []string{"--from-unit=1000", "--to-unit=1000", "5"}},
		{name: "both units mixed", args: []string{"--from-unit=1024", "--to-unit=1000", "1", "1000"}},
		{name: "from-unit with from", args: []string{"--from-unit=1000", "--from=si", "1K", "1M"}},
		{name: "to-unit with from", args: []string{"--to-unit=1000", "--from=si", "1K", "1.5K", "1.4999K", "1.0001K"}},
		{name: "to-unit seven", args: []string{"--to-unit=7", "--from=si", "1K", "1M"}},
		{name: "to-unit empty", args: []string{"--to-unit="}},
		{name: "to-unit negative", args: []string{"--to-unit=-5", "1"}},
		{name: "to-unit plus", args: []string{"--to-unit=+5", "10"}},
		{name: "to-unit blank", args: []string{"--to-unit= 5", "10"}},
		{name: "to-unit trailing blank", args: []string{"--to-unit=5 ", "10"}},

		// --padding and --suffix.
		{name: "padding", args: []string{"--padding=5", "1"}},
		{name: "padding wider than the value", args: []string{"--padding=5", "1000"}},
		{name: "padding left", args: []string{"--padding=-5", "1"}},
		{name: "padding narrower", args: []string{"--padding=1", "1000"}},
		{name: "padding zero", args: []string{"--padding=0", "1000"}},
		{name: "padding word", args: []string{"--padding=x", "1"}},
		{name: "padding empty", args: []string{"--padding=", "1"}},
		{name: "padding leading blank", args: []string{"--padding= 5", "1"}},
		{name: "padding trailing blank", args: []string{"--padding=5 ", "1"}},
		{name: "padding plus", args: []string{"--padding=+5", "1"}},
		{name: "padding negative zero", args: []string{"--padding=-0", "1"}},
		{name: "padding huge", args: []string{"--padding=99999999999999999999", "1"}},
		{name: "padding huge negative", args: []string{"--padding=-99999999999999999999", "1"}},
		{name: "padding minus one", args: []string{"--padding=-1", "1"}},
		{name: "padding with a scale", args: []string{"--padding=5", "--to=si", "1000", "1"}},
		{name: "padding an operand with blanks", args: []string{"--padding=5", " 1", "1 ", " 1 "}},
		{name: "padding left an operand with blanks", args: []string{"--padding=-5", " 1 "}},
		{name: "padding an empty operand", args: []string{"--padding=5", ""}},
		{name: "padding a blank operand", args: []string{"--padding=5", " "}},
		{name: "suffix", args: []string{"--suffix=X", "1"}},
		{name: "suffix with a scale", args: []string{"--suffix=X", "--to=si", "1000", "1"}},
		{name: "suffix empty", args: []string{"--suffix=", "1"}},
		{name: "suffix already there", args: []string{"--suffix=X", "1X"}},
		{name: "suffix after a unit", args: []string{"--suffix=X", "--from=si", "1KX"}},
		{name: "suffix before a unit", args: []string{"--suffix=X", "--from=si", "1XK"}},
		{name: "suffix without one in the input", args: []string{"--suffix=X", "--from=si", "1K"}},
		{name: "suffix that is a unit and more", args: []string{"--suffix=KX", "--from=si", "1KX"}},
		{name: "suffix twice", args: []string{"--suffix=X", "1XX"}},
		{name: "suffix as its own operand", args: []string{"--suffix=X", "1", "X"}},
		{name: "suffix then a blank", args: []string{"--suffix=X", "1X "}},
		{name: "suffix and padding", args: []string{"--suffix=X", "--padding=5", "1"}},
		{name: "suffix and left padding", args: []string{"--suffix=X", "--padding=-5", "1"}},
		{name: "suffix padding and scale", args: []string{"--suffix=X", "--padding=5", "--to=si", "1000"}},
		{name: "two letter suffix", args: []string{"--suffix=XY", "1XY", "1X"}},
		{name: "two letter suffix half present", args: []string{"--suffix=XY", "1Y"}},
		{name: "suffix lower case unit", args: []string{"--suffix=x", "--from=si", "1Kx"}},
		{name: "suffix B", args: []string{"--suffix=B", "--from=si", "1KB"}},
		{name: "suffix iB", args: []string{"--suffix=iB", "--from=si", "1KiB"}},
		{name: "suffix B from iec-i", args: []string{"--suffix=B", "--from=iec-i", "1KiB"}},
		{name: "suffix B from auto", args: []string{"--suffix=B", "--from=auto", "1KiB", "1KB"}},
		{name: "suffix i", args: []string{"--suffix=i", "--from=si", "1Ki"}},
		{name: "suffix i from auto", args: []string{"--suffix=i", "--from=auto", "1Ki"}},
		{name: "suffix K", args: []string{"--suffix=K", "--from=si", "1KK", "1K"}},
		{name: "suffix point", args: []string{"--suffix=.", "1.", "1.5."}},
		{name: "suffix digit", args: []string{"--suffix=5", "15", "155"}},
		{name: "suffix blank", args: []string{"--suffix= ", "1 ", "1"}},

		// --delimiter and --field.
		{name: "delimiter comma", args: []string{"-d,", "1,2"}},
		{name: "delimiter two characters", args: []string{"--delimiter=,,", "1,2"}},
		{name: "delimiter empty", args: []string{"--delimiter=", "1,2"}},
		{name: "delimiter empty short", args: []string{"-d", "", "1"}},
		{name: "delimiter empty short with a comma", args: []string{"-d", "", "1,2"}},
		{name: "delimiter empty and a field", args: []string{"-d", "", "--field=2", "1 2"}},
		{name: "field word", args: []string{"--field=x", "1"}},
		{name: "field zero", args: []string{"--field=0", "1"}},
		{name: "field one", args: []string{"--field=1", "1"}},
		{name: "field two", args: []string{"--field=2", "1"}},
		{name: "field two of two", args: []string{"--field=2", "1 2"}},
		{name: "field ranges", args: []string{"--field=1-2", "1 2 3"}},
		{name: "field all", args: []string{"--field=-", "1 2 3"}},
		{name: "field from", args: []string{"--field=2-", "1 2 3"}},
		{name: "field to", args: []string{"--field=-2", "1 2 3"}},
		{name: "field list", args: []string{"--field=1,3", "1 2 3"}},
		{name: "field list out of order", args: []string{"--field=3,1", "1 2 3"}},
		{name: "field repeated", args: []string{"--field=1,1", "1 2 3"}},
		{name: "field single range", args: []string{"--field=1-1", "1 2 3"}},
		{name: "field decreasing range", args: []string{"--field=3-1", "1 2 3"}},
		{name: "field overlapping", args: []string{"--field=1-3,2", "1 2 3"}},
		{name: "field overlapping ranges", args: []string{"--field=1-2,2-3", "1 2 3"}},
		{name: "field double dash", args: []string{"--field=1--2", "1 2 3"}},
		{name: "field trailing dash", args: []string{"--field=1-2-", "1 2 3"}},
		{name: "field comma alone", args: []string{"--field=,", "1 2 3"}},
		{name: "field trailing comma", args: []string{"--field=1,", "1 2 3"}},
		{name: "field leading comma", args: []string{"--field=,1", "1 2 3"}},
		{name: "field empty between commas", args: []string{"--field=1,,2", "1 2 3"}},
		{name: "field leading blank", args: []string{"--field= 1", "1 2 3"}},
		{name: "field trailing blank", args: []string{"--field=1 ", "1 2 3"}},
		{name: "field range with a word", args: []string{"--field=1-x", "1 2 3"}},
		{name: "field too large", args: []string{"--field=99999999999999999999", "1 2 3"}},
		{name: "field range end too large", args: []string{"--field=1-99999999999999999999", "1 2 3"}},
		{name: "field range start too large", args: []string{"--field=99999999999999999999-", "1 2 3"}},
		{name: "field past the line", args: []string{"--field=4", "1 2 3"}},
		{name: "field two converts", args: []string{"--field=2", "--to=si", "1000 2000 3000"}},
		{name: "field range converts", args: []string{"--field=1-2", "--to=si", "1000 2000 3000"}},
		{name: "field all converts", args: []string{"--field=-", "--to=si", "1000 2000 3000"}},
		{name: "field all with blanks", args: []string{"--field=-", "--to=si", "  1000  2000  3000  "}},
		{name: "field one with blanks", args: []string{"--field=1", "--to=si", "  1000  2000  3000  "}},
		{name: "field two with blanks", args: []string{"--field=2", "--to=si", "  1000  2000  3000  "}},
		{name: "field three with blanks", args: []string{"--field=3", "--to=si", "  1000  2000  3000  "}},
		{name: "field all with tabs", args: []string{"--field=-", "--to=si", "1000\t2000\t3000"}},
		{name: "field two with tabs", args: []string{"--field=2", "--to=si", "1000\t2000\t3000"}},
		{name: "field three with tabs", args: []string{"--field=3", "--to=si", "1000\t2000\t3000"}},
		{name: "field one with a tab after", args: []string{"--field=1", "--to=si", "1000\t2000"}},
		{name: "field one with mixed blanks", args: []string{"--field=1", "--to=si", "1000 \t 2000"}},
		{name: "field one with more mixed blanks", args: []string{"--field=1", "--to=si", "1000  \t2000"}},
		{name: "field two with mixed blanks", args: []string{"--field=2", "--to=si", "1000 \t 2000"}},
		{name: "field two of a leading blank", args: []string{"--field=2", "--to=si", " 1000"}},
		{name: "field one of a leading blank", args: []string{"--field=1", "--to=si", " 1000"}},
		{name: "field one of a leading tab", args: []string{"--field=1", "--to=si", "\t1000"}},
		{name: "field one of a trailing blank", args: []string{"--field=1", "--to=si", "1000 "}},
		{name: "field two of a trailing blank", args: []string{"--field=2", "--to=si", "1000 "}},
		{name: "field two of trailing blanks", args: []string{"--field=2", "--to=si", "1000   "}},
		{name: "field all of a trailing blank", args: []string{"--field=-", "--to=si", "1000 "}},
		{name: "field all of trailing blanks", args: []string{"--field=-", "--to=si", "1000   "}},
		{name: "field all of leading blanks", args: []string{"--field=-", "--to=si", "   1000"}},
		{name: "field three past a word", args: []string{"--field=3", "--to=si", "1000   x"}},
		{name: "field all with a word first", args: []string{"--field=-", "--to=si", "x   1000"}},
		{name: "field one of empty", args: []string{"--field=1", "--to=si", ""}},
		{name: "field two of empty", args: []string{"--field=2", "--to=si", ""}},
		{name: "field one of a blank", args: []string{"--field=1", "--to=si", " "}},
		{name: "field two of a blank", args: []string{"--field=2", "--to=si", " "}},
		{name: "field two of blanks", args: []string{"--field=2", "--to=si", "  "}},
		{name: "field two comma", args: []string{"--field=2", "-d,", "--to=si", "1000,2000"}},
		{name: "field two of an empty comma field", args: []string{"--field=2", "-d,", "--to=si", "1000,,2000"}},
		{name: "field three of an empty comma field", args: []string{"--field=3", "-d,", "--to=si", "1000,,2000"}},
		{name: "field two comma with blanks", args: []string{"--field=2", "-d,", "--to=si", " 1000, 2000"}},
		{name: "field one comma with a leading blank", args: []string{"--field=1", "-d,", "--to=si", " 1000,2000"}},
		{name: "field all comma", args: []string{"--field=-", "-d,", "--to=si", "1000,2000,3000"}},
		{name: "field all comma with empties", args: []string{"--field=-", "-d,", "--to=si", ",1000,,3000,"}},
		{name: "field all comma of empty", args: []string{"--field=-", "-d,", "--to=si", ""}},
		{name: "field all comma of a comma", args: []string{"--field=-", "-d,", "--to=si", ","}},
		{name: "field all colon", args: []string{"--field=-", "-d:", "--to=si", "1000:2000"}},
		{name: "delimiter two colons", args: []string{"--field=-", "-d::", "--to=si", "1000:2000"}},
		{name: "delimiter space", args: []string{"--field=-", "-d", " ", "--to=si", "1000 2000"}},
		{name: "delimiter tab", args: []string{"--field=-", "-d", "\t", "--to=si", "1000\t2000"}},
		{name: "delimiter tab over spaces", args: []string{"--field=-", "-d", "\t", "--to=si", "1000 2000"}},
		{name: "field three of two comma fields", args: []string{"--field=3", "-d,", "--to=si", "1000,2000"}},
		{name: "delimiter before the field", args: []string{"-d,", "--field=1", "--to=si", "1000"}},
		{name: "field two comma with a trailing blank", args: []string{"--field=2", "-d,", "--to=si", "1000 ,2000 "}},
		{name: "field one comma with a trailing blank", args: []string{"--field=1", "-d,", "--to=si", "1000 ,2000 "}},
		{name: "comma field with a blank before the unit", args: []string{"-d,", "--from=si", "1000 K,2000"}},
		{name: "comma field with a word", args: []string{"-d,", "--from=si", "1000x,2000"}},
		{name: "comma field trailing blank rejected", args: []string{"-d,", "--to=si", "1000 ", "x"}},
		{name: "comma field blanks rejected", args: []string{"-d,", "--to=si", "1000  "}},
		{name: "comma field tab rejected", args: []string{"-d,", "--to=si", "1000\t"}},
		{name: "comma field around blanks", args: []string{"-d,", "--to=si", " 1000 "}},
		{name: "comma field unit and blank", args: []string{"-d,", "--to=si", "1K "}},
		{name: "comma field unit and junk", args: []string{"-d,", "--from=si", "1Kx"}},
		{name: "comma field unit blank junk", args: []string{"-d,", "--from=si", "1K x"}},
		{name: "padding and fields", args: []string{"--padding=5", "--field=-", "1 22 333"}},
		{name: "padding one field", args: []string{"--padding=5", "--field=2", "1 22 333"}},
		{name: "padding one field of doubled blanks", args: []string{"--padding=5", "--field=2", "1  22  333"}},
		{name: "padding a comma field", args: []string{"--padding=5", "-d,", "--field=2", "1,22,333"}},
		{name: "padding a field after a blank", args: []string{"--padding=5", "--field=2", " 1 22 333"}},
		{name: "padding narrower than the field", args: []string{"--padding=2", "--field=2", "1 22 333"}},
		{name: "padding left a field", args: []string{"--padding=-5", "--field=2", "1 22 333"}},
		{name: "padding left a field of doubled blanks", args: []string{"--padding=-5", "--field=2", "1  22  333"}},
		{name: "padding two fields", args: []string{"--padding=5", "--field=2", "1 2", "1 2 "}},
		{name: "padding all comma fields", args: []string{"--padding=5", "-d,", "--field=-", "1,22,333"}},
		{name: "padding comma fields with blanks", args: []string{"--padding=5", "-d,", "--field=2", " 1, 22,333"}},
		{name: "fields of tabs and spaces", args: []string{"--padding=6", "--field=2", "1\t22\t333", "1\t \t22\t\t333"}},
		{name: "fields with a trailing tab", args: []string{"--padding=6", "--field=3", "1 22 333\t"}},
		{name: "auto padding keeps the column", args: []string{"--field=2", "--to=si", "1000 100000", "1000    100000"}},
		{name: "auto padding with a word after", args: []string{"--field=1", "--to=si", "100000 x", "100000  x", " 100000  x", "  1  x"}},
		{name: "auto padding all fields", args: []string{"--field=-", "--to=si", "   1000   100000   "}},

		// --header, --grouping, --debug and --invalid.
		{name: "header with operands", args: []string{"--header", "1"}},
		{name: "header two with operands", args: []string{"--header=2", "1", "2", "3"}},
		{name: "header zero", args: []string{"--header=0", "1"}},
		{name: "header word", args: []string{"--header=x", "1"}},
		{name: "header empty", args: []string{"--header=", "1"}},
		{name: "header negative", args: []string{"--header=-1", "1"}},
		{name: "header trailing letter", args: []string{"--header=1x", "1"}},
		{name: "header huge", args: []string{"--header=99999999999999999999", "1"}},
		{name: "header converts operands anyway", args: []string{"--header", "--to=si", "1000", "2000"}},
		{name: "grouping", args: []string{"--grouping", "1000000"}},
		{name: "grouping with a scale", args: []string{"--grouping", "--to=si", "1000000"}},
		{name: "grouping with a format", args: []string{"--grouping", "--format=%f", "1"}},
		{name: "grouping with a format and a scale", args: []string{"--grouping", "--to=si", "--format=%f", "1000"}},
		{name: "format quote with a scale", args: []string{"--format=%'f", "--to=si", "1000"}},
		{name: "format quote with a scale after it", args: []string{"--to=si", "--format=%'f", "1000"}},
		{name: "format quote with a width and a scale", args: []string{"--format=%'10f", "--to=si", "1000"}},
		{name: "format quote with scale none", args: []string{"--format=%'f", "--to=none", "1000"}},
		{name: "format quote with a from scale", args: []string{"--format=%'f", "--from=si", "1K"}},
		{name: "debug format quote", args: []string{"--debug", "--format=%'f", "1000000"}},
		{name: "debug format quote with a scale", args: []string{"--debug", "--format=%'f", "--to=si", "1000"}},
		{name: "debug format quote padding", args: []string{"--debug", "--format=%'5f", "--padding=3", "1"}},
		{name: "debug format quote zero padding", args: []string{"--debug", "--format=%'05f", "--padding=3", "1"}},
		{name: "debug grouping padding", args: []string{"--debug", "--grouping", "--padding=3", "1"}},
		{name: "grouping with padding", args: []string{"--grouping", "--padding=5", "1"}},
		{name: "debug plain", args: []string{"--debug", "1"}},
		{name: "debug with a scale", args: []string{"--debug", "--to=si", "1000"}},
		{name: "debug with from", args: []string{"--debug", "--from=si", "1K"}},
		{name: "debug with a field", args: []string{"--debug", "--field=2", "1 2"}},
		{name: "debug with padding", args: []string{"--debug", "--padding=5", "1"}},
		{name: "debug with a format", args: []string{"--debug", "--format=%f", "1"}},
		{name: "debug with grouping", args: []string{"--debug", "--grouping", "1"}},
		{name: "debug with a header", args: []string{"--debug", "--header", "1"}},
		{name: "debug with a suffix", args: []string{"--debug", "--suffix=X", "1"}},
		{name: "debug with a from-unit", args: []string{"--debug", "--from-unit=2", "1"}},
		{name: "debug with a to-unit", args: []string{"--debug", "--to-unit=2", "1"}},
		{name: "debug a large value", args: []string{"--debug", "--to=si", "12345678901234567890"}},
		{name: "debug a large unscaled value", args: []string{"--debug", "12345678901234567890"}},
		{name: "debug a long fraction", args: []string{"--debug", "0.1234567890123456789"}},
		{name: "debug a long value and fraction", args: []string{"--debug", "1234567890123456789.5"}},
		{name: "debug a long input with from", args: []string{"--debug", "--from=si", "1.1234567890123456789K"}},
		{name: "debug format padding", args: []string{"--debug", "--format=%5f", "--padding=3", "1"}},
		{name: "debug zero format padding", args: []string{"--debug", "--format=%05f", "--padding=3", "1"}},
		{name: "debug left format padding", args: []string{"--debug", "--format=%-5f", "--padding=3", "1"}},
		{name: "debug format without a width", args: []string{"--debug", "--format=%f", "--padding=3", "1"}},
		{name: "debug format zero without a width", args: []string{"--debug", "--format=%0f", "--padding=3", "1"}},
		{name: "debug an invalid number", args: []string{"--debug", "--invalid=warn", "x"}},
		{name: "invalid warn", args: []string{"--invalid=warn", "x"}},
		{name: "invalid warn then a number", args: []string{"--invalid=warn", "x", "1"}},
		{name: "invalid warn between numbers", args: []string{"--invalid=warn", "1", "x", "2"}},
		{name: "invalid warn with a scale", args: []string{"--invalid=warn", "--to=si", "x", "1000"}},
		{name: "invalid warn over fields", args: []string{"--invalid=warn", "--field=-", "x 1000 y"}},
		{name: "invalid warn one field", args: []string{"--invalid=warn", "--field=2", "x 1000 y"}},
		{name: "invalid warn with padding", args: []string{"--invalid=warn", "--field=-", "--padding=5", "x 1000 y"}},
		{name: "invalid warn with a suffix", args: []string{"--invalid=warn", "--field=-", "--suffix=Z", "x 1000 y"}},
		{name: "invalid warn with a format", args: []string{"--invalid=warn", "--field=-", "--format=%5f", "x 1000 y"}},
		{name: "invalid warn comma fields", args: []string{"--invalid=warn", "--field=-", "-d,", "x,1000,y"}},
		{name: "invalid warn comma fields with blanks", args: []string{"--invalid=warn", "--field=-", "-d,", " x,1000, y"}},
		{name: "invalid warn blanks around fields", args: []string{"--invalid=warn", "--field=-", "  x  1000  y  "}},
		{name: "invalid warn one field of blanks", args: []string{"--invalid=warn", "--field=2", "  x  1000  y  "}},
		{name: "invalid warn too large", args: []string{"--invalid=warn", "--to=si", "1000000000000000000000000000000000000"}},
		{name: "invalid warn a forbidden suffix", args: []string{"--invalid=warn", "1K"}},
		{name: "invalid warn an unknown suffix", args: []string{"--invalid=warn", "--from=si", "1KB"}},
		{name: "invalid warn a missing i", args: []string{"--invalid=warn", "--from=iec-i", "1K"}},
		{name: "invalid warn an empty operand", args: []string{"--invalid=warn", ""}},
		{name: "invalid warn an empty field", args: []string{"--invalid=warn", "--field=-", ""}},
		{name: "invalid warn a trailing blank", args: []string{"--invalid=warn", "--field=2", "1 "}},
		{name: "invalid warn all fields trailing blank", args: []string{"--invalid=warn", "--field=-", "1 "}},
		{name: "invalid warn empty comma fields", args: []string{"--invalid=warn", "--field=-", "-d,", ",1,,"}},
		{name: "invalid warn mixed fields", args: []string{"--invalid=warn", "--to=si", "--field=-", "1000 x 2000 y"}},
		{name: "invalid ignore", args: []string{"--invalid=ignore", "x", "1"}},
		{name: "invalid ignore trailing blanks", args: []string{"--invalid=ignore", "--field=-", "--to=si", "1000   "}},
		{name: "invalid fail", args: []string{"--invalid=fail", "x"}},
		{name: "invalid fail then a number", args: []string{"--invalid=fail", "x", "1"}},
		{name: "invalid fail between numbers", args: []string{"--invalid=fail", "1", "x", "2"}},
		{name: "invalid fail over fields", args: []string{"--invalid=fail", "--field=-", "x 1000 y"}},
		{name: "invalid abort", args: []string{"--invalid=abort", "x", "1"}},
		{name: "invalid abort between numbers", args: []string{"--invalid=abort", "1", "x", "2"}},
		{name: "invalid prefixes", args: []string{"--invalid=a", "1"}},
		{name: "invalid prefix f", args: []string{"--invalid=f", "1"}},
		{name: "invalid prefix w", args: []string{"--invalid=w", "1"}},
		{name: "invalid prefix i", args: []string{"--invalid=i", "1"}},
		{name: "invalid unknown", args: []string{"--invalid=x", "1"}},
		{name: "invalid empty", args: []string{"--invalid=", "1"}},
		{name: "zero terminated", args: []string{"-z", "1"}},
		{name: "zero terminated with a scale", args: []string{"-z", "--to=si", "1000"}},
		{name: "zero terminated long option", args: []string{"--zero-terminated", "1"}},
		{name: "zero terminated fields", args: []string{"--zero-terminated", "--field=2", "1 2"}},
		{name: "zero terminated converts", args: []string{"--zero-terminated", "--field=2", "--to=si", "1 2000"}},
		{name: "zero terminated header", args: []string{"--zero-terminated", "--header", "1", "2"}},
		{name: "zero terminated all fields", args: []string{"--zero-terminated", "--field=-", "--to=si", "1000 2000"}},
		{name: "zero terminated invalid", args: []string{"-z", "--invalid=warn", "x"}},
		{name: "zero terminated invalid field", args: []string{"-z", "--invalid=warn", "--field=-", "x 1000"}},
		{name: "zero terminated comma field", args: []string{"-d", ",", "-z", "--field=2", "1,2"}},

		// --format.
		{name: "format plain", args: []string{"--format=%f", "1000", "1.5", "1.55", "0.001", "1000000"}},
		{name: "format precision", args: []string{"--format=%.1f", "1.55", "1.54", "1.56"}},
		{name: "format zero precision", args: []string{"--format=%.0f", "1.5", "2.5"}},
		{name: "format two places", args: []string{"--format=%.2f", "1", "1.005", "1.015", "1.025", "1.035", "1.045"}},
		{name: "format two places nearest", args: []string{"--format=%.2f", "--round=nearest", "1.005", "1.015", "1.025", "1.035", "1.045"}},
		{name: "format two places down", args: []string{"--format=%.2f", "--round=down", "1.005", "1.015", "1.025", "1.035", "1.045", "1.006"}},
		{name: "format three places", args: []string{"--format=%.3f", "1.0004", "1.0005", "1.0006", "1.5", "1.0005"}},
		{name: "format three places down", args: []string{"--format=%.3f", "--round=down", "1.0005"}},
		{name: "format with a scale", args: []string{"--format=%.1f", "--to=si", "1500", "1550", "1555"}},
		{name: "format two places with a scale", args: []string{"--format=%.2f", "--to=si", "1555", "1555555"}},
		{name: "format no places with a scale", args: []string{"--format=%.0f", "--to=si", "1555"}},
		{name: "format three places with a scale", args: []string{"--format=%.3f", "--to=si", "1555", "1555.5"}},
		{name: "format four places with a scale", args: []string{"--format=%.4f", "--to=si", "1555.5", "15555", "155555"}},
		{name: "format four places near the base", args: []string{"--format=%.4f", "--to=si", "999.99", "999.9", "999", "998.99", "999.98", "999.995"}},
		{name: "format five places near the base", args: []string{"--format=%.5f", "--to=si", "999999.9", "999999", "999990"}},
		{name: "format two places near the base", args: []string{"--format=%.2f", "--to=si", "999.99", "999.9", "9.999", "9.99", "9.991"}},
		{name: "format one place near ten", args: []string{"--format=%.1f", "--to=si", "9.99", "9.94", "9.95"}},
		{name: "format no places near ten", args: []string{"--format=%.0f", "--to=si", "9.5", "8.5", "9.4"}},
		{name: "format rounding with a scale", args: []string{"--format=%.2f", "--round=down", "--to=si", "1555"}},
		{name: "format rounding up with a scale", args: []string{"--format=%.2f", "--round=up", "--to=si", "1555"}},
		{name: "format rounding nearest with a scale", args: []string{"--format=%.2f", "--round=nearest", "--to=si", "1555"}},
		{name: "format three places rounding down", args: []string{"--format=%.3f", "--round=down", "--to=si", "1555"}},
		{name: "format one place rounding down", args: []string{"--format=%.1f", "--round=down", "--to=si", "1555", "999.99"}},
		{name: "format one place rounding up", args: []string{"--format=%.1f", "--round=up", "--to=si", "999.91"}},
		{name: "format four places rounding down", args: []string{"--format=%.4f", "--round=down", "--to=si", "999.99", "999999"}},
		{name: "format many places", args: []string{"--format=%.6f", "--to=si", "1234567"}},
		{name: "format seven places", args: []string{"--format=%.7f", "--to=si", "1234567"}},
		{name: "format ten places", args: []string{"--format=%.10f", "--to=si", "1234567"}},
		{name: "format fifteen places", args: []string{"--format=%.15f", "--to=si", "1234567"}},
		{name: "format seventeen places", args: []string{"--format=%.17f", "--to=si", "1234567"}},
		{name: "format nineteen places", args: []string{"--format=%.19f", "--to=si", "1234567"}},
		{name: "format twenty places", args: []string{"--format=%.20f", "--to=si", "1234567"}},
		{name: "format nine places", args: []string{"--format=%.9f", "--to=si", "123456", "1234567"}},
		{name: "format five places", args: []string{"--format=%.5f", "--to=si", "999999", "9999999", "1", "0"}},
		{name: "format five places unscaled", args: []string{"--format=%.5f", "0"}},
		{name: "format too wide", args: []string{"--format=%.19f", "1"}},
		{name: "format eighteen places", args: []string{"--format=%.18f", "1"}},
		{name: "format eighteen places of ten", args: []string{"--format=%.18f", "10"}},
		{name: "format seventeen places of ten", args: []string{"--format=%.17f", "10"}},
		{name: "format twenty places of a half", args: []string{"--format=%.20f", "0.5"}},
		{name: "format thirty places of a half", args: []string{"--format=%.30f", "0.5"}},
		{name: "format width", args: []string{"--format=%10f", "1"}},
		{name: "format zero width", args: []string{"--format=%010f", "1"}},
		{name: "format left width", args: []string{"--format=%-10f", "1"}},
		{name: "format plus width", args: []string{"--format=%+10f", "1"}},
		{name: "format plus", args: []string{"--format=%+f", "1"}},
		{name: "format hash", args: []string{"--format=%#f", "1"}},
		{name: "format grouping quote", args: []string{"--format=%'f", "1000000"}},
		{name: "format grouping quote and width", args: []string{"--format=%'10f", "1000000"}},
		{name: "format grouping quote and precision", args: []string{"--format=%'.2f", "1000000"}},
		{name: "format d", args: []string{"--format=%d", "1"}},
		{name: "format s", args: []string{"--format=%s", "1"}},
		{name: "format g", args: []string{"--format=%g", "1"}},
		{name: "format e", args: []string{"--format=%e", "1"}},
		{name: "format upper F", args: []string{"--format=%F", "1"}},
		{name: "format length modifier", args: []string{"--format=%lf", "1"}},
		{name: "format long modifier", args: []string{"--format=%Lf", "1"}},
		{name: "format percent only", args: []string{"--format=%%", "1"}},
		{name: "format percent f", args: []string{"--format=%%f", "1"}},
		{name: "format percent then a directive", args: []string{"--format=%%%f", "1"}},
		{name: "format two directives", args: []string{"--format=%f%f", "1"}},
		{name: "format directive then percents", args: []string{"--format=%f%%", "1"}},
		{name: "format directive then a percent", args: []string{"--format=%f%", "1"}},
		{name: "format bare percent", args: []string{"--format=%", "1"}},
		{name: "format width alone", args: []string{"--format=%5", "1"}},
		{name: "format precision alone", args: []string{"--format=%.5", "1"}},
		{name: "format point alone", args: []string{"--format=%.", "1"}},
		{name: "format zero alone", args: []string{"--format=%0", "1"}},
		{name: "format minus alone", args: []string{"--format=%-", "1"}},
		{name: "format plus alone", args: []string{"--format=%+", "1"}},
		{name: "format plus width alone", args: []string{"--format=%+5", "1"}},
		{name: "format width and point", args: []string{"--format=%5.", "1"}},
		{name: "format width and precision alone", args: []string{"--format=%5.2", "1"}},
		{name: "format unknown conversion", args: []string{"--format=%x", "1"}},
		{name: "format text", args: []string{"--format=abc", "1"}},
		{name: "format empty", args: []string{"--format=", "1"}},
		{name: "format around the directive", args: []string{"--format=x%fy", "1"}},
		{name: "format with spaces around", args: []string{"--format=x %f y", "1"}},
		{name: "format with an escape", args: []string{"--format=%f\\n", "1"}},
		{name: "format in brackets", args: []string{"--format=[%f]", "1"}},
		{name: "format width in brackets", args: []string{"--format=[%10f]", "1"}},
		{name: "format left width in brackets", args: []string{"--format=[%-10f]", "1"}},
		{name: "format width and precision in brackets", args: []string{"--format=[%10.2f]", "--to=si", "1500"}},
		{name: "format left width and precision", args: []string{"--format=[%-10.2f]", "--to=si", "1500"}},
		{name: "format zero width and precision", args: []string{"--format=[%010.2f]", "--to=si", "1500"}},
		{name: "format two places with iec-i", args: []string{"--format=%.2f", "--to=iec-i", "2048"}},
		{name: "format with iec-i", args: []string{"--format=%f", "--to=iec-i", "2048", "2047", "1"}},
		{name: "format double f", args: []string{"--format=%ff", "1"}},
		{name: "format text between directives", args: []string{"--format=%fx%f", "1"}},
		{name: "format percents after", args: []string{"--format=%f%%f", "1"}},
		{name: "format percents before", args: []string{"--format=%%f%f", "1"}},
		{name: "format negative precision", args: []string{"--format=%.-1f", "1"}},
		{name: "format minus zero", args: []string{"--format=%-0f", "1"}},
		{name: "format zero minus width", args: []string{"--format=%0-5f", "1"}},
		{name: "format minus zero width", args: []string{"--format=%-05f", "1"}},
		{name: "format zero blank width", args: []string{"--format=%0 5f", "1"}},
		{name: "format quote blank width", args: []string{"--format=%' 5f", "1000000"}},
		{name: "format blank quote width", args: []string{"--format=% '5f", "1000000"}},
		{name: "format blank width", args: []string{"--format=% 5f", "1"}},
		{name: "format width blank f", args: []string{"--format=%5 f", "1"}},
		{name: "format width point blank precision", args: []string{"--format=%5. 2f", "1"}},
		{name: "format width blank point precision", args: []string{"--format=%5 .2f", "1"}},
		{name: "format left width and precision plain", args: []string{"--format=%-5.2f", "1"}},
		{name: "format zero width and precision plain", args: []string{"--format=%05.2f", "1"}},
		{name: "format precision then a minus", args: []string{"--format=%.2-f", "1"}},
		{name: "format trailing blank", args: []string{"--format=%f ", "1"}},
		{name: "format leading blank", args: []string{"--format= %f", "1"}},
		{name: "format three directives", args: []string{"--format=%f%f%f", "1"}},
		{name: "format point f", args: []string{"--format=%.f", "1"}},
		{name: "format then a point", args: []string{"--format=%f.", "1"}},
		{name: "format two zeros", args: []string{"--format=%00f", "1"}},
		{name: "format many zeros", args: []string{"--format=%000000000000000000005f", "1"}},
		{name: "format precision with many zeros", args: []string{"--format=%.00000000000000000005f", "1"}},
		{name: "format width overrides padding", args: []string{"--format=%10f", "--padding=3", "--to=si", "1500"}},
		{name: "format narrow width overrides padding", args: []string{"--format=%3f", "--padding=10", "--to=si", "1500"}},
		{name: "format width with a suffix", args: []string{"--format=%10f", "--suffix=X", "--to=si", "1500"}},
		{name: "format width in brackets with a suffix", args: []string{"--format=[%5f]", "--suffix=X", "1"}},
		{name: "format width over fields", args: []string{"--format=%10f", "--field=-", "1 2"}},
		{name: "format left width over fields", args: []string{"--format=%-10f", "--field=-", "1 2"}},
		{name: "format width with a scale", args: []string{"--format=%10f", "--to=si", "1500"}},
		{name: "format zero width with a scale", args: []string{"--format=%010f", "--to=si", "1500"}},
		{name: "format left width with a scale", args: []string{"--format=%-10f", "--to=si", "1500"}},
		{name: "format zero width and precision with a scale", args: []string{"--format=%05.1f", "--to=si", "1500"}},
		{name: "format zero width negative", args: []string{"--format=%05.1f", "--to=si", "--", "-1500"}},
		{name: "format with to-unit", args: []string{"--to-unit=1000", "--format=%.3f", "1234", "1235"}},
		{name: "format with from-unit", args: []string{"--from-unit=1000", "--format=%.3f", "1"}},

		// GNU formats into a fixed 128-byte buffer: the conversion is
		// refused when it fills, --suffix takes only the room the
		// conversion left, and --padding is applied outside it. The
		// buffer is GNU's own, so unlike the unscaled path's LDBL_DIG
		// limit these boundaries are the same on every host.
		//
		// GNU <= 9.4 only, per docs/COREUTILS.md's version rule: from 9.5
		// prepare_padded_number grows the buffer with xpalloc, so these
		// boundary rows do not hold against a newer reference. #8765.
		{name: "scaled buffer fits", args: []string{"--to=si", "--format=%.123f", "1000"}},
		{name: "scaled buffer overflows", args: []string{"--to=si", "--format=%.124f", "1000"}},
		{name: "scaled buffer two integer digits", args: []string{"--to=si", "--format=%.122f", "12000"}},
		{name: "scaled buffer two integer digits over", args: []string{"--to=si", "--format=%.123f", "12000"}},
		{name: "scaled buffer three integer digits", args: []string{"--to=si", "--format=%.121f", "123000"}},
		{name: "scaled buffer three integer digits over", args: []string{"--to=si", "--format=%.122f", "123000"}},
		{name: "scaled buffer rounded thousands", args: []string{"--to=si", "--format=%.121f", "999999"}},
		{name: "scaled buffer rounded thousands over", args: []string{"--to=si", "--format=%.122f", "999999"}},
		{name: "scaled buffer without a unit", args: []string{"--to=iec", "--format=%.121f", "1000"}},
		{name: "scaled buffer without a unit over", args: []string{"--to=iec", "--format=%.122f", "1000"}},
		{name: "scaled buffer iec", args: []string{"--to=iec", "--format=%.123f", "1024"}},
		{name: "scaled buffer iec over", args: []string{"--to=iec", "--format=%.124f", "1024"}},
		{name: "scaled buffer iec-i", args: []string{"--to=iec-i", "--format=%.123f", "1048576"}},
		{name: "scaled buffer iec-i over", args: []string{"--to=iec-i", "--format=%.124f", "1048576"}},
		{name: "scaled buffer iec-i three integer digits", args: []string{"--to=iec-i", "--format=%.121f", "1000000"}},
		{name: "scaled buffer iec-i three integer digits over", args: []string{"--to=iec-i", "--format=%.122f", "1000000"}},
		{name: "scaled buffer negative", args: []string{"--to=si", "--format=%.122f", "--", "-1000"}},
		{name: "scaled buffer negative over", args: []string{"--to=si", "--format=%.123f", "--", "-1000"}},
		{name: "scaled buffer negative without a unit", args: []string{"--to=si", "--format=%.123f", "--", "-1"}},
		{name: "scaled buffer negative without a unit over", args: []string{"--to=si", "--format=%.124f", "--", "-1"}},
		{name: "scaled buffer zero", args: []string{"--to=si", "--format=%.124f", "0"}},
		{name: "scaled buffer zero over", args: []string{"--to=si", "--format=%.125f", "0"}},
		{name: "scaled buffer with a whole suffix", args: []string{"--to=si", "--suffix=BBBBB", "--format=%.119f", "1000"}},
		{name: "scaled buffer suffix truncated", args: []string{"--to=si", "--suffix=BBBBB", "--format=%.121f", "1000"}},
		{name: "scaled buffer suffix down to one byte", args: []string{"--to=si", "--suffix=BBBBB", "--format=%.123f", "1000"}},
		{name: "scaled buffer suffix does not move it", args: []string{"--to=si", "--suffix=BBBBB", "--format=%.124f", "1000"}},
		{name: "scaled buffer iec-i suffix dropped", args: []string{"--to=iec-i", "--suffix=BBBBB", "--format=%.123f", "1048576"}},
		{name: "scaled buffer padding does not move it", args: []string{"--to=si", "--padding=40", "--format=%.123f", "1000"}},
		{name: "scaled buffer padding over", args: []string{"--to=si", "--padding=40", "--format=%.124f", "1000"}},
		{name: "scaled buffer zero width", args: []string{"--to=si", "--format=%0125.0f", "1000"}},
		{name: "scaled buffer zero width over", args: []string{"--to=si", "--format=%0126.0f", "1000"}},
		{name: "scaled buffer zero width without a unit", args: []string{"--to=iec", "--format=%0126.0f", "1000"}},
		{name: "scaled buffer zero width without a unit over", args: []string{"--to=iec", "--format=%0127.0f", "1000"}},
		{name: "scaled buffer zero width and precision", args: []string{"--to=si", "--format=%0120.4f", "1000"}},
		{name: "scaled buffer huge precision", args: []string{"--to=si", "--format=%.2000000000f", "1000"}},
		{name: "scaled buffer precision past an int", args: []string{"--to=si", "--format=%.5000000000f", "1000"}},
		{name: "scaled buffer huge zero width", args: []string{"--to=si", "--format=%02000000000.0f", "1000"}},
		{name: "unscaled buffer zero width", args: []string{"--format=%0127.0f", "1000"}},
		{name: "unscaled buffer zero width over", args: []string{"--format=%0128.0f", "1000"}},
		{name: "unscaled buffer zero width negative over", args: []string{"--format=%0128.0f", "--", "-1000"}},
		{name: "unscaled buffer zero width suffix dropped", args: []string{"--suffix=BBBBB", "--format=%0127.0f", "1000"}},
		{name: "unscaled buffer zero width and precision", args: []string{"--format=%0127.15f", "1000"}},
		{name: "unscaled buffer zero width and precision over", args: []string{"--format=%0128.15f", "1000"}},
		{name: "unscaled buffer huge zero width", args: []string{"--format=%02000000000.0f", "1000"}},
		{name: "unscaled buffer huge precision", args: []string{"--format=%.2000000000f", "1000"}},
		{name: "refusal ignores invalid ignore", args: []string{"--invalid=ignore", "--to=si", "--format=%.124f", "1000"}},
		{name: "refusal ignores invalid warn", args: []string{"--invalid=warn", "--to=si", "--format=%.124f", "1000"}},
		{name: "refusal ignores invalid fail", args: []string{"--invalid=fail", "--to=si", "--format=%.124f", "1000"}},
		{name: "refusal ignores invalid abort", args: []string{"--invalid=abort", "--to=si", "--format=%.124f", "1000"}},
		{name: "refusal flushes what came before", args: []string{"--to=si", "--format=%.123f", "1000", "999999"}},
		{name: "refusal stops at the first field", args: []string{"--field=-", "--to=si", "--format=%.123f", "1000 999999 1000"}},
		{name: "refusal from stdin flushes", args: []string{"--to=si", "--format=%.123f"}, stdin: "1000\n999999\n"},
		{name: "refusal with stdout closed", args: []string{"--to=si", "--format=%.124f", "1000"}, stdout: stdoutClosed},
		{name: "refusal with stdout full", args: []string{"--to=si", "--format=%.124f", "1000"}, stdout: stdoutFull},

		// Numbers that are not numbers, and suffixes that are not.
		{name: "not a number", args: []string{"x"}},
		{name: "two points", args: []string{"--from=si", "1..5"}},
		{name: "point twice over", args: []string{"--from=si", "1.5.5"}},
		{name: "point then a letter", args: []string{"--from=si", "1.x"}},
		{name: "point then a unit", args: []string{"--from=si", "1.K"}},
		{name: "point then a comma", args: []string{"--from=si", "1.,"}},
		{name: "point then a sign", args: []string{"--from=si", "1.-5"}},
		{name: "point then a unit and a digit", args: []string{"--from=si", "1.K5"}},
		{name: "point then a unit and an i", args: []string{"--from=si", "1.Ki"}},
		{name: "point alone with from", args: []string{"--from=si", "."}},
		{name: "point then a unit only", args: []string{"--from=si", ".K"}},
		{name: "two points only", args: []string{"--from=si", "1.."}},
		{name: "unit after a point", args: []string{"--from=si", "1.5K"}},
		{name: "trailing point with a scale", args: []string{"-d,", "--to=si", "1000."}},
		{name: "trailing e", args: []string{"-d,", "--to=si", "1000e"}},
		{name: "trailing letter", args: []string{"-d,", "--to=si", "1000x"}},
		{name: "double unit", args: []string{"--from=si", "1KK"}},
		{name: "two different units", args: []string{"--from=si", "1KM"}},
		{name: "unit then i twice", args: []string{"--from=si", "1Kii"}},
		{name: "iec-i then a unit", args: []string{"--from=iec-i", "1KiK"}},
		{name: "auto then a letter", args: []string{"--from=auto", "1Kx"}},
		{name: "auto then i and a letter", args: []string{"--from=auto", "1Kix"}},
		{name: "zero with a unit", args: []string{"--from=si", "0K", "0.0K", "00K", ".0K", "00.00K"}},
		{name: "zeros", args: []string{"--from=si", "000", "000.000"}},
		{name: "negative zeros", args: []string{"--from=si", "--", "-000", "-0K"}},
		{name: "negative fractions with a unit", args: []string{"--from=si", "--", "-.5K", "-0.5K", "-0.0005K", "-0.0004K"}},
		{name: "small fractions with a unit", args: []string{"--from=si", "0.0005K", "0.0004K", "0.0015K", "0.00049K"}},
		{name: "negative small fractions", args: []string{"--from=si", "--", "-0.00049K", "-0.0005K", "-0.4", "-0.5", "-0.6"}},
		{name: "negative fractions of a unit", args: []string{"--from=si", "--", "-0.4K", "-1.4K", "-1.5K", "-1.6K"}},
		{name: "negative nearest with a unit", args: []string{"--from=si", "--round=nearest", "--", "-1.0005K", "-1.0015K", "-1.0025K"}},
		{name: "negative rounding with a unit", args: []string{"--from=si", "--round=down", "--", "-1.0001K"}},
		{name: "negative rounding up with a unit", args: []string{"--from=si", "--round=up", "--", "-1.0001K"}},
		{name: "negative rounding toward zero", args: []string{"--from=si", "--round=towards-zero", "--", "-1.0001K", "-1.9999K"}},
		{name: "halves and their neighbours", args: []string{"0.4", "0.5", "0.6", "1.4", "1.5", "1.6", "2.5", "0.45", "0.55"}},
		{name: "negative halves", args: []string{"--", "-0.5", "-0.4", "-0", "-0.0"}},
		{name: "to-unit one", args: []string{"--to-unit=1", "0.4", "0.5", "0.6"}},
		{name: "to-unit one negative", args: []string{"--to-unit=1", "--", "-0.5", "-0.4", "-0.6"}},
		{name: "from-unit fractions", args: []string{"--from-unit=2", "0.25", "0.5", "0.75", "0.3", "0.2"}},
		{name: "to si halves and fractions", args: []string{"--to=si", "0.5", "1.5", "2.5", "1.4", "1.6", "10.5", "100.5", "999.5", "999.4", "999.49", "999.499"}},
		{name: "to iec near the base", args: []string{"--to=iec", "1023.5", "1023.4"}},
		{name: "to iec-i near the base", args: []string{"--to=iec-i", "1023.5", "1023.4"}},
		{name: "non UTF-8 with a scale", args: []string{"--to=si", "\xff\xfe"}},
		{name: "non UTF-8 field", args: []string{"--field=2", "--to=si", "1000 \xff"}},
		{name: "non UTF-8 delimiter", args: []string{"-d", "\xff", "--field=2", "--to=si", "1000\xff2000"}},
		{name: "non UTF-8 suffix", args: []string{"--suffix=\xff", "--to=si", "1000"}},

		// stdin.
		{name: "stdin two lines", args: []string{"--to=si"}, stdin: "1000\n2000\n"},
		{name: "stdin without a newline", args: []string{"--to=si"}, stdin: "1000"},
		{name: "stdin empty", args: []string{"--to=si"}, stdin: ""},
		{name: "stdin a newline", args: []string{"--to=si"}, stdin: "\n"},
		{name: "stdin two newlines", args: []string{"--to=si"}, stdin: "\n\n"},
		{name: "stdin a blank line between", args: []string{"--to=si"}, stdin: "1000\n\n2000\n"},
		{name: "stdin header", args: []string{"--header", "--to=si"}, stdin: "1000\n2000\n"},
		{name: "stdin two headers", args: []string{"--header=2", "--to=si"}, stdin: "1000\n2000\n3000\n"},
		{name: "stdin more headers than lines", args: []string{"--header=5", "--to=si"}, stdin: "1000\n2000\n"},
		{name: "stdin header without a newline", args: []string{"--header", "--to=si"}, stdin: "1000"},
		{name: "stdin invalid", args: []string{"--to=si"}, stdin: "x\n1000\n"},
		{name: "stdin invalid warn", args: []string{"--invalid=warn", "--to=si"}, stdin: "x\n1000\n"},
		{name: "stdin invalid fail", args: []string{"--invalid=fail", "--to=si"}, stdin: "x\n1000\n"},
		{name: "stdin invalid ignore", args: []string{"--invalid=ignore", "--to=si"}, stdin: "x\n1000\n"},
		{name: "stdin zero terminated", args: []string{"-z", "--to=si"}, stdin: "1000\x002000\x00"},
		{name: "stdin zero terminated newlines", args: []string{"-z", "--to=si"}, stdin: "1000\n2000\n"},
		{name: "stdin zero terminated header", args: []string{"-z", "--header", "--to=si"}, stdin: "1000\x002000\x00"},
		{name: "stdin zero terminated two headers", args: []string{"-z", "--header=2", "--to=si"}, stdin: "1000\x002000\x003000\x00"},
		{name: "stdin zero terminated one value", args: []string{"-z", "--to=si"}, stdin: "1000\x00"},
		{name: "stdin zero terminated unterminated", args: []string{"-z", "--to=si"}, stdin: "1000"},
		{name: "stdin carriage return", args: []string{"--to=si"}, stdin: "1000\r\n"},
		{name: "stdin vertical tab", args: []string{"-z", "--to=si"}, stdin: "1000\v2000\x00"},
		{name: "stdin form feed", args: []string{"-z", "--to=si"}, stdin: "1000\f2000\x00"},
		{name: "stdin fields", args: []string{"--field=2", "--to=si"}, stdin: "a 1000\nb 2000\n"},
		{name: "stdin all fields", args: []string{"--field=-", "--to=si"}, stdin: "1000 2000\n3000 4000\n"},
		{name: "stdin debug", args: []string{"--debug", "--to=si"}, stdin: "1000\n"},
		{name: "stdin padding", args: []string{"--padding=8", "--to=si"}, stdin: "1000\n2000\n"},
		{name: "stdin suffix", args: []string{"--suffix=B", "--to=si"}, stdin: "1000\n"},
		{name: "stdin blanks around", args: []string{"--to=si"}, stdin: "  1000  \n"},
		{name: "stdin two fields", args: []string{"--to=si"}, stdin: "1000 2000\n"},
		{name: "stdin tab separated", args: []string{"--field=-", "--to=si"}, stdin: "1000\t2000\n"},
		{name: "stdin a NUL", args: []string{"--to=si"}, stdin: "\x00"},
		{name: "stdin a NUL in a line", args: []string{"--to=si"}, stdin: "1200\x0034\n"},
		{name: "stdin a NUL then more lines", args: []string{"--to=si"}, stdin: "12\x0034\n5000\n"},
		{name: "stdin last line unterminated", args: []string{"--to=si"}, stdin: "1000\n2000"},

		// The write-failure paths.
		{name: "closed stdout", args: []string{"1"}, stdout: stdoutClosed},
		{name: "closed stdout with a scale", args: []string{"--to=si", "1000"}, stdout: stdoutClosed},
		{name: "closed stdout with an invalid number", args: []string{"x"}, stdout: stdoutClosed},
		{name: "closed stdout warning", args: []string{"--invalid=warn", "x"}, stdout: stdoutClosed},
		{name: "closed stdout ignoring", args: []string{"--invalid=ignore", "x"}, stdout: stdoutClosed},
		{name: "closed stdout failing", args: []string{"--invalid=fail", "x", "1"}, stdout: stdoutClosed},
		{name: "closed stdout with nothing to write", args: []string{}, stdout: stdoutClosed},
		{name: "closed stdout header", args: []string{"--header", "1"}, stdout: stdoutClosed},
		{name: "full stdout", args: []string{"1"}, stdout: stdoutFull},
		{name: "full stdout with a scale", args: []string{"--to=si", "1000"}, stdout: stdoutFull},
		{name: "full stdout with an invalid number", args: []string{"x"}, stdout: stdoutFull},
		{name: "full stdout warning", args: []string{"--invalid=warn", "x"}, stdout: stdoutFull},
		{name: "full stdout ignoring", args: []string{"--invalid=ignore", "x"}, stdout: stdoutFull},
		{name: "full stdout failing", args: []string{"--invalid=fail", "x", "1"}, stdout: stdoutFull},
		{name: "full stdout with nothing to write", args: []string{}, stdout: stdoutFull},
	}
}

func TestNumfmtParity(t *testing.T) {
	requireParity(t, "numfmt", numfmtCases(t))
}

func TestNumfmtHelp(t *testing.T) {
	requireHelp(t, "numfmt", []string{"--help"}, 0)
	requireHelp(t, "numfmt", []string{"--hel"}, 0)
	requireHelp(t, "numfmt", []string{"x", "--help"}, 0)
	requireVersion(t, "numfmt", []string{"--version"}, 0)
	requireVersion(t, "numfmt", []string{"--v"}, 0)
	requireVersion(t, "numfmt", []string{"--vers", "x"}, 0)
}
