package coreutils

import (
	"strings"
	"testing"
)

func TestPrintfParity(t *testing.T) {
	long := strings.Repeat("x", 10000)
	requireParity(t, "printf", []invocation{
		// printf(1) does not use getopt: only a sole --help / --version
		// is an option, a leading `--` is skipped, and everything else
		// is the format.
		{name: "no arguments"},
		{name: "dashdash alone"},
		{name: "dashdash then format", args: []string{"--", `%s\n`, "a"}},
		{name: "dashdash is skipped once", args: []string{"--", "--"}},
		{name: "dashdash twice then operand", args: []string{"--", "--", "a"}},
		{name: "help with an operand is a format", args: []string{"--help", "x"}},
		{name: "help after an operand is an operand", args: []string{"x", "--help"}},
		{name: "abbreviated help is a format", args: []string{"--hel"}},
		{name: "help with a value is a format", args: []string{"--help=x"}},
		{name: "abbreviated version is a format", args: []string{"--v"}},
		{name: "version with an operand is a format", args: []string{"--version", "x"}},
		{name: "dashdash then help is a format", args: []string{"--", "--help"}},
		{name: "lone dash is a format", args: []string{"-"}},
		{name: "unknown short is a format", args: []string{"-n"}},
		{name: "format starting with a dash", args: []string{`-%s\n`, "a"}},
		{name: "unknown long is a format", args: []string{"--x"}},
		{name: "dashdash as an operand", args: []string{`%s\n`, "--", "a"}},
		{name: "posix help is still help", args: []string{"--help", "x"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix operands", args: []string{`%s\n`, "a", "b"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix dashdash", args: []string{"--", `%s\n`, "a"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix excess warning", args: []string{"abc", "x"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix bad number", args: []string{`%d\n`, "1.5"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix char constant warning", args: []string{`%d\n`, "'ab"}, env: []string{"POSIXLY_CORRECT=1"}},

		// The format is reused while arguments remain; a format that
		// consumes none warns about the excess.
		{name: "one directive three arguments", args: []string{`%s\n`, "a", "b", "c"}},
		{name: "two directives three arguments", args: []string{`%s %s\n`, "a", "b", "c"}},
		{name: "missing argument is empty", args: []string{`%s\n`}},
		{name: "missing numeric argument is zero", args: []string{`%d %d\n`, "1"}},
		{name: "mixed cycling", args: []string{`%s %d`, "abc", "123", "def", "456"}},
		{name: "numbers cycle", args: []string{`%d\n`, "1", "2", "3"}},
		{name: "empty operand", args: []string{`%s\n`, ""}},
		{name: "excess arguments warning", args: []string{`abc\n`, "a"}},
		{name: "excess arguments warning names the first", args: []string{`abc\n`, "a", "b"}},
		{name: "percent percent consumes nothing", args: []string{`%%\n`, "a"}},
		{name: "empty format with an argument", args: []string{"", "a"}},
		{name: "empty format", args: []string{""}},
		{name: "plain text", args: []string{"x"}},
		{name: "plain text newline", args: []string{`x\n`}},
		{name: "newline only", args: []string{`\n`}},
		{name: "percent percent", args: []string{"%%"}},
		{name: "percent percent s", args: []string{"%%s"}},
		{name: "backslash percent", args: []string{`\%d`, "1"}},
		{name: "percent between strings", args: []string{`%s%%%s\n`, "a", "b"}},
		{name: "many operands", args: []string{`%s\n`, "a", "b", "c", "d", "e", "f", "g", "h", "i", "j"}},
		{name: "bench shape", args: []string{`%d %s %5.2f\n`, "1", "a", "2.5", "2", "b", "3.5", "3", "c"}},
		{name: "non UTF-8 operand", args: []string{`%s\n`, "\xff\xfe"}},
		{name: "non UTF-8 format", args: []string{"\xff%s\xfe\n", "x"}},
		{name: "long operand", args: []string{`%s\n`, long}},
		{name: "excess warning quotes control bytes", args: []string{"x", "a\tb\x01\xff'\\"}},

		// Escapes in the format.
		{name: "named escapes", args: []string{`a\ab\bc\ed\ff\nn\rr\tt\vv\\\"\'\z\q\8\9\'`}},
		{name: "trailing backslash", args: []string{`x\`}},
		{name: "octal with leading zero in format is three digits", args: []string{`\0101\n`}},
		{name: "octal three digits", args: []string{`\101\n`}},
		{name: "octal stops at three", args: []string{`\1017\n`}},
		{name: "octal wraps at a byte", args: []string{`\0777\n`}},
		{name: "octal 400 wraps", args: []string{`\400\n`}},
		{name: "eight is not octal", args: []string{`\08\n`}},
		{name: "hex escapes", args: []string{`\x41A\x4\xff\xFf\n`}},
		{name: "hex without a digit is fatal", args: []string{`\x41\x\n`}},
		{name: "hex with a non digit is fatal", args: []string{`\xGG\n`}},
		{name: "unicode escapes", args: []string{`A\U0001F600 \U00000041Aé€\n`}},
		{name: "unicode short is fatal", args: []string{`\u004\n`}},
		{name: "unicode surrogate is fatal", args: []string{`\uD800\n`}},
		{name: "unicode big surrogate is fatal", args: []string{`\U0000DFFF\n`}},
		{name: "unicode empty is fatal", args: []string{`\u\n`}},
		{name: "unicode beyond range prints the escape", args: []string{`\U0011FFFF\n`}},
		{name: "unicode max prints the escape", args: []string{`\U0010FFFF\n`}},
		{name: "unicode lowercase hex prints upper", args: []string{`ÿĀ\Uabcdef01\n`}},
		{name: "backslash c alone", args: []string{`\c`}},
		{name: "backslash c drops the rest", args: []string{`a\cb`, "c"}},
		{name: "backslash c between directives", args: []string{`%s\c%s`, "a", "b"}},
		{name: "backslash c after an error exits zero", args: []string{`%d\c`, "abc"}},
		{name: "backslash c after a range error exits zero", args: []string{`%d\c`, "99999999999999999999"}},
		{name: "backslash c with arguments left warns not", args: []string{`\c`, "a", "b"}},

		// %b: the argument with escapes, octal as \0NNN.
		{name: "b octal forms", args: []string{`%b\n`, `\0101`, `\101`, `\0`, `\00`, `\000`, `\0000`, `\01234`, `\x41`, "A", `x\`, `\q`, `\"`, `\'`, "\xc3\xa9", `\e`}},
		{name: "b backslash c", args: []string{`%b|`, `a\cb`}},
		{name: "b backslash c ends everything", args: []string{`%b|%s\n`, `a\cb`, "d"}},
		{name: "b in a later directive", args: []string{`%b`, `\c`, "a"}},
		{name: "b nul", args: []string{"%b", `\0`}},
		{name: "b missing argument", args: []string{`%b|%q|\n`}},
		{name: "b with a width is invalid", args: []string{`%5b|`, "a"}},
		{name: "b with a length modifier is invalid", args: []string{`%lb|`, "a"}},
		{name: "b hex without digit is fatal", args: []string{`%b`, `\x`}},

		// %q: shell quoting.
		{name: "q bare words", args: []string{`%q\n`, "abc", "1", "a,b", "a/b", "a-b", "-a", "%", "a%b", "@", "+", "a:b", "x#", "a~", "{}", "a{b}", "a}b", "a]b", ".", "..", "_", "a_b", "/", "-", "--", "+a", "a=", "=a", "a."}},
		{name: "q single quoted", args: []string{`%q\n`, "a b", "a$b", "#x", "~", "{", "}", "a=b", "a^b", "a[b", "a`b", "a!b", "a?b", "a*b", "a(b", "a|b", "a<b", "a&b", "a;b", `a\b`, "]", "[", "!", "^", "*", "?", "#", "~a", "a~b", "#a", " ", "  ", "a  b", "a b~", "=", ":", "a{", "{a", "a}", "a>b", "a)b"}},
		{name: "q double quoted", args: []string{`%q\n`, "it's", "a'b c", "#it's", "~it's", "it's:x", "it's,x", "it's@x", "it's%x", "it's a", "'", "''", "a'", "'a", "a''b", "'a'"}},
		{name: "q quote forces single", args: []string{`%q\n`, "it's {", "a'b$", "it's#", "it's}", "it's\\", "it's\"", "it's=x", "it's~"}},
		{name: "q empty", args: []string{`%q`, ""}},
		{name: "q missing argument", args: []string{`%q`}},
		{name: "q missing argument with a following directive", args: []string{`%q|%q|`, "a"}},
		{name: "q control bytes", args: []string{`%q\n`, "a\tb", "\x01x", "it's\n", "\xff", "a\nb\n", "\x1b[0m", "a\x7fb", "x\ty'z", "a\tb\tc", "\t", "\t\x01", "a\t'", "'\t", "\xc3\xa9", "a\xc3\xa9b", "\n", "\r\n", "\a\b\f\v", " \x01 ", "\x01 \x02", "a\x80b\xff"}},
		{name: "q rescan quirk", args: []string{`%q\n`, "\x01'\x02", "'\x01'", "a'\x01", "'\x01", "\x01\x02'\x03", "\x01a'\x02", "\x01'a\x02", "x\x01'\x02", "\x01'\x02x", "\xff'\xff", "\x01'", "ab'\x01", "\x01\x02'", "\x01''\x02", "'\x01'\x02", "\x01'\x02'\x03", "\t'\t", "\x01 '\x02", " \x01'\x02", "a\x01b'\x02", "\x01a'\x02\x03", "'\x01\x02", "''\x01", "a''\x01", "\x01'\x02'\x03'"}},
		{name: "q with a flag is invalid", args: []string{`%-q|`, "a"}},
		{name: "q with a precision is invalid", args: []string{`%.1q|`, "ab"}},
		{name: "q cycles", args: []string{`%q\n`, "a", "b c", ""}},

		// Integer arguments: strtoimax / strtoumax with base 0.
		{name: "d out of range clamps", args: []string{`%d\n`, "99999999999999999999"}},
		{name: "d negative out of range clamps", args: []string{`%d\n`, "-99999999999999999999"}},
		{name: "d at the limits", args: []string{`%d\n`, "9223372036854775807", "9223372036854775808", "-9223372036854775808", "-9223372036854775809"}},
		{name: "u negative wraps", args: []string{`%u\n`, "-1"}},
		{name: "u out of range", args: []string{`%u\n`, "99999999999999999999", "-99999999999999999999", "18446744073709551615", "18446744073709551616"}},
		{name: "octal hex and binary prefixes", args: []string{`%d\n`, "010", "0x1f", "0X1F", "0b101", "0B11", "0b", "0x", "0xg", "08", "0"}},
		{name: "d with a fraction", args: []string{`%d\n`, "1.5"}},
		{name: "d with trailing space", args: []string{`%d\n`, "5 "}},
		{name: "d with leading space", args: []string{`%d\n`, " 5", " -5", "\t+5", "\n5"}},
		{name: "d empty", args: []string{`%d\n`, ""}},
		{name: "d not a number", args: []string{`%d\n`, "abc", "-", "- 5", "+", "0x1p3", "1e3"}},
		{name: "d explicit plus", args: []string{`%d\n`, "+5"}},
		{name: "x o X of minus one", args: []string{`%x %o %X\n`, "-1", "-1", "-1"}},
		{name: "i of 0x", args: []string{`%i\n`, "0x"}},
		{name: "error then continue", args: []string{`%d %s\n`, "1.5", "a"}},
		{name: "error status persists across cycles", args: []string{`%d\n`, "1.5", "2"}},
		{name: "error then bad directive", args: []string{`%d %z\n`, "abc"}},
		{name: "out of range with trailing junk", args: []string{`%d\n`, "99999999999999999999x"}},

		// Character constants.
		{name: "char constant", args: []string{`%d\n`, "'a"}},
		{name: "char constant double quote", args: []string{`%d\n`, `"a`}},
		{name: "char constant with trailing bytes warns", args: []string{`%d\n`, "'ab"}},
		{name: "char constant with a space", args: []string{`%d\n`, "'a b"}},
		{name: "char constant with control bytes", args: []string{`%d\n`, "'a\tb"}},
		{name: "char constant multibyte", args: []string{`%d\n`, "'\xc3\xa9"}},
		{name: "char constant one high byte", args: []string{`%d\n`, "'\xc3"}},
		{name: "char constant newline", args: []string{`%d\n`, "'\n"}},
		{name: "char constant quote in quote", args: []string{`%d\n`, "'a'", `"a"`, `'"`, `"'`}},
		{name: "lone quote is not a number", args: []string{`%d\n`, "'"}},
		{name: "char constant everywhere", args: []string{`%c|%s|%d|%f|%x\n`, "'a", "'a", "'a", "'a", "'a"}},
		{name: "char constant as star width", args: []string{`%*d`, "'a", "1"}},

		// Float arguments: strtold.
		{name: "f words", args: []string{`%f\n`, "1e3", "inf", "nan", "-inf", "0x1p3", "INF", "Infinity", "nan(abc)", "nan(", "-nan", "nan(a-b)", "nanx", "infx", "infinit", "infinityx", "-INFINITY", "+inf", "nan()", "NAN(12_a)"}},
		{name: "f syntax edges", args: []string{`%f\n`, "1.5", "1.5x", "", "abc", ".5", "5.", ".", "e5", "1e", "1e+", "1e5x", "0x", "0x.", "0x.8", "0x8.", "0x1p", "0x1p+", "0x1P3", "0X1p3", "1E3", "0x.8p1", "0x1.8p-1", ".e5", "0x1pz"}},
		{name: "f spacing and zeros", args: []string{`%f\n`, "'a", "", " 1.5", "1.5 ", "00012.5", "1_0", "+.5", "-.5", "-0", "+0", "-0.0"}},
		{name: "f range", args: []string{`%f\n`, "1e-4950", "1e-5000", "1e5000", "1e4932", "1e4933", "1.18973149535723176502e4932", "1.18973149535723176503e4932"}},
		{name: "f e g of overflow", args: []string{`%f %e %g\n`, "1e400", "1e400", "1e400"}},
		{name: "f big", args: []string{`%f\n`, "1e30", "1e20", "123456789012345678901234567890", "1e-7", "1e-6", "0.000001", "0.0000005", "0.0000015", "0.0000025", "9223372036854775807", "9223372036854775808", "18446744073709551615", "18446744073709551616", "1e19", "1e-1"}},
		{name: "f rounds half to even", args: []string{`%.0f %.0f %.0f %.0f %.0f\n`, "0.5", "1.5", "2.5", "3.5", "-0.5"}},
		{name: "f rounds on the exact value", args: []string{`%.2f\n`, "2.675", "1.005", "0.125", "0.375", "-0.0", "-0.001", "0.001", "-0.005", "-0.0049"}},
		{name: "f tenth", args: []string{`%f\n`, "0.1", "-0", "-0.0", "0", "-1e-20", "1e-20"}},
		{name: "f long precision", args: []string{`%.20f\n`, "0.1", "1e-20", "123.456"}},
		{name: "f longer precision", args: []string{`%.30f\n`, "0.1", "1e-30", "1e30"}},
		{name: "f forty digits", args: []string{`%.40f\n`, "0.1"}},
		{name: "f sixty five digits", args: []string{`%.65f\n`, "1e-64"}},
		{name: "f exact tail", args: []string{`%.25f\n`, "0.1", "0.2", "0.3", "1.1", "2.2", "3.3", "1e-25"}},
		{name: "f half at the boundary", args: []string{`%.0f %.0f %.0f %.0f %.0f %.0f\n`, "0.4999999999999999999999", "0.5", "0.50000000000000000001", "1", "1e19", "1e20"}},
		{name: "e values", args: []string{`%e\n`, "0.1", "123456789", "0.000123", "0", "-0", "1", "10", "1e100", "1e-100", "9.9999995", "9.9999996", "999999.5", "1e400", "1e-400", "1e-4950"}},
		{name: "e precisions", args: []string{`%.0e %.0e %.0e %.0e %#.0e %.1e %.3e\n`, "1", "15", "25", "35", "1", "0.95", "99995"}},
		{name: "E", args: []string{`%E\n`, "1e-100", "1e5"}},
		{name: "g values", args: []string{`%g\n`, "0.1", "123456789", "0.000123", "100000", "1000000", "0.0001", "0.00001", "999999.5", "0.00009999995", "0", "-0", "1", "10", "100", "1e-5", "1e-4", "1e5", "1e6", "123456", "1234567", "0.5", "1e100", "1e-100", "1e400", "1e-4950", "12345.6789"}},
		{name: "g precisions", args: []string{`%.0g %.1g %.2g %.10g %.20g %.25g %.30g\n`, "1234.5", "1234.5", "1234.5", "1234.5", "0.1", "0.1", "0.1"}},
		{name: "g alternate", args: []string{`%#g %#.0g %#.1g %#.3g %#.10g %#g %#g %#g\n`, "1", "1", "1", "1", "1", "0.1", "1e10", "123456"}},
		{name: "g rounding chooses style before rounding", args: []string{`%.3g %#.3g %#.3g %.3g %.3g %.3g\n`, "999.5", "999.5", "1", "9995", "99.95", "0.0009995"}},
		{name: "g rounding carries", args: []string{`%.3g %.3g %.2g %.1g %#.1g %#.2g\n`, "99.95", "9.995", "9.95", "9.5", "9.5", "99.5"}},
		{name: "g near the style switch", args: []string{`%g %g %g %g\n`, "99999.5", "999999", "9999995", "0.000099999"}},
		{name: "G", args: []string{`%G\n`, "1e-10", "1e10", "0.5"}},
		{name: "alternate forms", args: []string{`%#.0f %#.0e %#g %#e %#f %#a\n`, "1", "1", "1", "1", "1", "1"}},
		{name: "F E G A of specials", args: []string{`%F %E %G %A %F %F\n`, "inf", "nan", "1e-10", "0.5", "-inf", "-nan"}},
		{name: "negative nan", args: []string{`%f %e %g %a\n`, "-nan", "-nan", "-nan", "-nan"}},
		{name: "nan spellings", args: []string{`%f %e %g %a\n`, "nan(123)", "-nan(x)", "NaN", "nAn"}},
		{name: "ten digit precisions", args: []string{`%.10f %.10e %.10g\n`, "1e-10", "1e-10", "1e-10"}},
		{name: "g digits of a tenth", args: []string{`%.17g %.18g %.19g %.20g %.21g %.22g\n`, "0.1", "0.1", "0.1", "0.1", "0.1", "0.1"}},
		{name: "e digits of a tenth", args: []string{`%.19e %.20e %.21e\n`, "0.1", "0.1", "0.1"}},
		{name: "pi in g", args: []string{`%.15g %.16g %.17g %.18g %.19g\n`, "3.141592653589793238462643", "3.141592653589793238462643", "3.141592653589793238462643", "3.141592653589793238462643", "3.141592653589793238462643"}},
		{name: "pi in every style", args: []string{`%f %e %g %a\n`, "3.141592653589793238462643", "3.141592653589793238462643", "3.141592653589793238462643", "3.141592653589793238462643"}},
		{name: "tiny values", args: []string{`%e %g %f\n`, "4e-4951", "4e-4951", "4e-4951"}},
		{name: "tiny value long e", args: []string{`%.30e\n`, "4e-4951"}},

		// %a: hex floats from the x87 significand.
		{name: "a of one", args: []string{`%a %A\n`, "1", "1"}},
		{name: "a values", args: []string{`%a\n`, "0", "0.5", "2", "3", "0.1", "-1", "1e400", "1e-4950", "1e-4940", "1e-4930", "10", "255", "256", "1.5", "0.75", "1e300", "1e-300", "4e-4951", "3e-4951"}},
		{name: "a precisions", args: []string{`%.0a %.1a %.2a %.20a %#.0a %#a %.3a\n`, "1", "1", "1", "1", "1", "1", "0.1"}},
		{name: "a rounds half to even", args: []string{`%.0a %.1a %.0a %.0a %.1a\n`, "1.5", "1.03125", "0.9375", "3", "0.96875"}},
		{name: "a rounds fractions", args: []string{`%.0a %.0a %.0a %.0a\n`, "0.5", "0.75", "0.875", "0.9999"}},
		{name: "a subnormals", args: []string{`%a\n`, "1e-4951", "5e-4952", "3e-4951"}},
		{name: "a subnormals with precision", args: []string{`%.3a\n`, "4e-4951", "3e-4951", "1e-4951"}},
		{name: "A", args: []string{`%A\n`, "0.1", "255", "1e-5"}},
		{name: "a of pi", args: []string{`%a\n`, "3.141592653589793238462643", "1e-1", "0.2", "0.3", "1e10", "12345678901234567890", "1.0000000000000000001", "1.00000000000000000001"}},
		{name: "a of pi with precision", args: []string{`%.1a %.2a %.3a\n`, "3.141592653589793238462643", "3.141592653589793238462643", "3.141592653589793238462643"}},
		{name: "a of a tenth with precisions", args: []string{`%.5a %.10a %.14a %.15a %.16a %.17a\n`, "0.1", "0.1", "0.1", "0.1", "0.1", "0.1"}},
		{name: "a rounding at zero precision", args: []string{`%.0a\n`, "0.1", "0.9", "1.9", "0x1.8p0", "0x1.7p0", "0x1.9p0", "0x0.8p0", "0x1.fp0", "0x1.ffffffffffffffffp0", "0xf.fp0", "0xf.8p0", "0xe.8p0"}},
		{name: "a hex inputs at the precision edge", args: []string{`%a\n`, "0x1.ffffffffffffffffp0", "0xf.fffffffffffffffp0", "0x1.fffffffffffffffffp0", "0x1.00000000000000001p0", "0x8.000000000000001p-3", "0x8.0000000000000008p-3", "0x8.0000000000000018p-3"}},
		{name: "a rounding the last digit", args: []string{`%.15a %.14a %.13a\n`, "0x8.0000000000000008p-3", "0x8.0000000000000008p-3", "0x8.00000000000000f8p-3"}},
		{name: "a rounding carries through", args: []string{`%.3a %.3a %.3a\n`, "0xf.ffp0", "0xf.ff8p0", "0xf.fffp0"}},
		{name: "a carry into the lead", args: []string{`%.0a %.0a\n`, "0xf.8p0", "0xf.8000001p0"}},
		{name: "a two digit rounding", args: []string{`%.2a %.2a %.2a %.2a\n`, "0x1.008p0", "0x1.018p0", "0x1.028p0", "0x1.038p0"}},

		// %c and %s.
		{name: "c of empty is NUL", args: []string{`%c\n`, "", "abc"}},
		{name: "c of empty alone", args: []string{`%c|`, ""}},
		{name: "c widths", args: []string{`%5c|%-5c|`, "a", "b"}},
		{name: "s precisions", args: []string{`%.2s|%.0s|%.5s|`, "abc", "abc", "abc"}},
		{name: "s widths", args: []string{`%3s|%-3s|%3.1s|%.10s|%10.3s|%-10.3s|\n`, "abcde", "abcde", "abcde", "abcde", "abcde", "abcde"}},
		{name: "s with tab", args: []string{`%s`, "a\tb"}},
		{name: "s zero flag is invalid", args: []string{`%0s\n`, "a"}},
		{name: "c zero flag is invalid", args: []string{`%0c\n`, "a"}},
		{name: "c precision is invalid", args: []string{`%.1c\n`, "a"}},
		{name: "s hash flag is invalid", args: []string{`%#s\n`, "1"}},
		{name: "c hash flag is invalid", args: []string{`%#c\n`, "a"}},
		{name: "d hash flag is invalid", args: []string{`%#d\n`, "1"}},
		{name: "u i hash flags are invalid", args: []string{`%#u %#i\n`, "1", "1"}},

		// Flags, width and precision on integers.
		{name: "hash on x o", args: []string{`%#x %#o %#X %#x\n`, "0", "0", "15", "15"}},
		{name: "hash o forms", args: []string{`%#o %#.0o %#.1o %#.3o %#5o %#05o %#-5o|\n`, "8", "8", "8", "8", "8", "8", "8"}},
		{name: "hash x forms", args: []string{`%#x %#.0x %#.1x %#.3x %#5x %#05x %#-5x|\n`, "15", "15", "15", "15", "15", "15", "15"}},
		{name: "sign flags", args: []string{`%+d % d %+u % u %+x % o %+ d % +d\n`, "1", "1", "1", "1", "1", "1", "1", "1"}},
		{name: "sign flags negative", args: []string{`%+d % d %+i\n`, "-1", "-1", "-1"}},
		{name: "zero flag", args: []string{`%05d %-05d %+05d %05.2d %05.0d %0-5d|\n`, "1", "1", "1", "1", "0", "1"}},
		{name: "zero flag negative", args: []string{`%05d %05d\n`, "-1", "-12345678"}},
		{name: "zero precision of zero", args: []string{`%.0d|%.0x|%.0o|%#.0o|%#.0x|%.0u|%.0i|%5.0d|%-5.0d|\n`, "0", "0", "0", "0", "0", "0", "0", "0", "0"}},
		{name: "precision pads digits", args: []string{`%.3d %.3x %5.3d %-5.3d %05.3d %.3d %.3o\n`, "7", "7", "7", "7", "7", "-7", "-1"}},
		{name: "precision with negative", args: []string{`%.3d %.5d\n`, "-7", "-7"}},
		{name: "width and precision", args: []string{`%3d|%-3d|%03d|%3.1d|%3.4d|%-3.4d|%03.4d|\n`, "5", "5", "5", "5", "5", "5", "5"}},
		{name: "length modifiers are ignored", args: []string{`%hd %ld %lld %qd %jd %zd %td %Ld\n`, "1", "2", "3", "4", "5", "6", "7", "8"}},
		{name: "hh is two modifiers", args: []string{`%hhd\n`, "1"}},
		{name: "length modifiers on floats", args: []string{`%lf %Lf %llf %hf %jf\n`, "1.5", "1.5", "1.5", "1.5", "1.5"}},
		{name: "length modifiers on c and s", args: []string{`%lc %ls %Lc %hs\n`, "a", "b", "c", "d"}},

		// Flags, width and precision on floats.
		{name: "float sign flags", args: []string{`%+.3e % .3E %+g %+a % a % g\n`, "1", "1", "1", "1", "1", "1"}},
		{name: "float widths", args: []string{`%08.3f %-8.3f %+8.3f % 8.3f %08.3f %+08.3f\n`, "1.5", "1.5", "1.5", "1.5", "-1.5", "-1.5"}},
		{name: "specials are not zero padded", args: []string{`%08f %08e %08g %08a %-8f| %+8f % 8f\n`, "-inf", "-inf", "nan", "nan", "inf", "inf", "inf"}},
		{name: "nan is not zero padded", args: []string{`%08f %08e %08g %08a\n`, "nan", "nan", "-nan", "-nan"}},
		{name: "float width mix", args: []string{`%5.1f|%-8g|%08.3a|%#8.0f|%#08.0f|%#08.0e|%#08.0g|\n`, "inf", "nan", "1", "1", "1", "1", "1"}},
		{name: "bench float shape", args: []string{`%5.2f|%-8.3e|%+g\n`, "3.14159", "2.71828", "1.5"}},

		// `*` width and precision.
		{name: "star width", args: []string{`%*d|%-*d|%*d|\n`, "5", "1", "5", "1", "-5", "1"}},
		{name: "star precision", args: []string{`%.*f\n`, "2", "3.14159", "-1", "3.14159"}},
		{name: "star both", args: []string{`%*.*f|\n`, "10", "2", "3.14159"}},
		{name: "star both left", args: []string{`%-*.*f|\n`, "10", "2", "3.14159"}},
		{name: "star on s", args: []string{`%*s|%.*s|\n`, "5", "a", "2", "abc"}},
		{name: "star not a number", args: []string{`%*d\n`, "x", "1"}},
		{name: "star not a number then value", args: []string{`%*d`, "abc", "1"}},
		{name: "star width too large", args: []string{`%*d\n`, "99999999999", "1"}},
		{name: "star width just too large", args: []string{`%*d`, "2147483648", "1"}},
		{name: "star width just too negative", args: []string{`%*d`, "-2147483649", "1"}},
		{name: "star width out of range", args: []string{`%*d\n`, "-99999999999999999999", "5"}},
		{name: "star precision negative is omitted", args: []string{`%.*d\n`, "-1", "5"}},
		{name: "star precision very negative is omitted", args: []string{`%.*d`, "-2147483648", "1"}},
		{name: "star precision below int min is omitted", args: []string{`%.*d`, "-2147483649", "1"}},
		{name: "star precision out of range negative", args: []string{`%.*d\n`, "-99999999999999999999", "5"}},
		{name: "star precision out of range positive", args: []string{`%.*d\n`, "99999999999999999999", "5"}},
		{name: "star precision just too large", args: []string{`%.*d`, "2147483648", "1"}},
		{name: "star hex", args: []string{`%*d`, "0x10", "1"}},
		{name: "star fraction", args: []string{`%*d`, "1.5", "1"}},
		{name: "star empty", args: []string{`%*d`, "", "1"}},
		{name: "star missing", args: []string{`%*d`}},
		{name: "star precision missing", args: []string{`%.*d`}},
		{name: "star missing after width", args: []string{`%*d`, "5"}},
		{name: "star both missing value", args: []string{`%*.*d|`, "5"}},
		{name: "star both missing last", args: []string{`%*.*d|`, "5", "3"}},
		{name: "star both complete", args: []string{`%*.*d|`, "5", "3", "1"}},
		{name: "star precision negative five", args: []string{`%.*d|`, "-5", "1"}},
		{name: "star cycles", args: []string{`%*d|%*d|`, "3", "1"}},
		{name: "star negative with minus", args: []string{`%-*d|`, "-3", "1"}},
		{name: "star with zero flag negative", args: []string{`%0*d|`, "-3", "1"}},
		{name: "star zero width", args: []string{`%*d|`, "0", "1"}},
		{name: "star zero precision of zero", args: []string{`%.*d|`, "0", "0"}},
		{name: "star precision on s", args: []string{`%.*s|`, "0", "abc"}},
		{name: "star negative precision on s", args: []string{`%.*s|`, "-1", "abc"}},
		{name: "star precision on c is invalid", args: []string{`%.*c|`, "1", "a"}},
		{name: "star width on c", args: []string{`%*c|`, "3", "a"}},

		// Invalid conversion specifications.
		{name: "unknown conversion", args: []string{`%z\n`}},
		{name: "lone percent", args: []string{"%"}},
		{name: "positional is invalid", args: []string{`%1$s\n`, "a"}},
		{name: "width then end", args: []string{"%5"}},
		{name: "flag then end", args: []string{"%-"}},
		{name: "dot then end", args: []string{"%."}},
		{name: "precision then end", args: []string{"%.5"}},
		{name: "percent after width", args: []string{`%5%|`}},
		{name: "percent after flag", args: []string{`%-%|`}},
		{name: "percent after precision", args: []string{`%.5%|`}},
		{name: "percent after modifier", args: []string{`%l%|`}},
		{name: "q after modifier", args: []string{`%lq\n`, "a"}},
		{name: "invalid after output", args: []string{`%s\n%z`, "a"}},

		// glibc refuses a conversion whose output would reach INT_MAX-1
		// bytes: nothing is printed for it, `write error`, exit 1.
		{name: "width at int max", args: []string{"%2147483647d", "1"}},
		{name: "width one under int max", args: []string{"%2147483646d", "1"}},
		{name: "width far too large", args: []string{"%99999999999d", "1"}},
		{name: "precision at int max", args: []string{"%.2147483647d", "1"}},
		{name: "precision one under int max", args: []string{"%.2147483646d", "1"}},
		{name: "precision far too large", args: []string{"%.99999999999d", "1"}},
		{name: "e precision refused", args: []string{"%.2147483640e", "1"}},
		{name: "a precision refused", args: []string{"%.2147483640a", "1"}},
		{name: "g precision is fine", args: []string{"%.2147483640g", "1"}},
		{name: "star width at int max", args: []string{"%*d", "2147483647", "1"}},
		{name: "star width at int min", args: []string{"%*d", "-2147483648", "1"}},
		{name: "refused directive between text", args: []string{`a%2147483647db\n`, "1"}},
		{name: "refused directive then cycle", args: []string{`a%2147483647db\n`, "1", "2"}},
		{name: "refused directive then another", args: []string{`a%2147483647d\n%d`, "1", "2"}},
		{name: "refused precision between text", args: []string{`a%.2147483647d\n`, "1"}},
		{name: "refused star width between text", args: []string{`a%*db\n`, "2147483647", "1"}},
		{name: "refused then invalid", args: []string{`%2147483647d\n%z`, "1"}},
		{name: "refused then backslash c in b", args: []string{`%2147483647d%b`, "1", `x\c`}},
		{name: "refused then backslash c", args: []string{`%2147483647d\c`, "1"}},
		{name: "refused then bad number", args: []string{`%2147483647d%d\n`, "1", "abc"}},
		{name: "bad number then refused", args: []string{`%d%2147483647d\n`, "abc", "1"}},

		// Write failures: what close_stdout reports depends on whether a
		// diagnostic flushed stdout first (#8265).
		{name: "stdout full", args: []string{"%s", "a", "b"}, stdout: stdoutFull},
		{name: "stdout closed", args: []string{"%s", "a"}, stdout: stdoutClosed},
		{name: "stdout full nothing written", args: []string{"%z"}, stdout: stdoutFull},
		{name: "stdout closed nothing written", args: []string{"%z"}, stdout: stdoutClosed},
		{name: "stdout full then fatal", args: []string{`%s\n%z`, "a"}, stdout: stdoutFull},
		{name: "stdout closed then fatal", args: []string{`%s\n%z`, "a"}, stdout: stdoutClosed},
		{name: "stdout full warning first", args: []string{`%d\n`, "abc"}, stdout: stdoutFull},
		{name: "stdout closed warning first", args: []string{`%d\n`, "abc"}, stdout: stdoutClosed},
		{name: "stdout full warning nothing after", args: []string{"%d", "abc"}, stdout: stdoutFull},
		{name: "stdout closed warning nothing after", args: []string{"%d", "abc"}, stdout: stdoutClosed},
		{name: "stdout full flushed at warning", args: []string{"x%d", "abc"}, stdout: stdoutFull},
		{name: "stdout closed flushed at warning", args: []string{"x%d", "abc"}, stdout: stdoutClosed},
		{name: "stdout full output after warning", args: []string{`%d\nxyz\n`, "abc"}, stdout: stdoutFull},
		{name: "stdout closed output after warning", args: []string{`%d\nxyz\n`, "abc"}, stdout: stdoutClosed},
		{name: "stdout full output around warning", args: []string{`x%d\nxyz\n`, "abc"}, stdout: stdoutFull},
		{name: "stdout closed output around warning", args: []string{`x%d\nxyz\n`, "abc"}, stdout: stdoutClosed},
		{name: "stdout full excess warning", args: []string{"abc", "x"}, stdout: stdoutFull},
		{name: "stdout closed excess warning", args: []string{"abc", "x"}, stdout: stdoutClosed},
		{name: "stdout closed empty format", args: []string{""}, stdout: stdoutClosed},
		{name: "stdout full empty format", args: []string{""}, stdout: stdoutFull},
		{name: "stdout full backslash c", args: []string{`\c`}, stdout: stdoutFull},
		{name: "stdout closed backslash c", args: []string{`\c`}, stdout: stdoutClosed},
		{name: "stdout closed output then backslash c", args: []string{`a\c`}, stdout: stdoutClosed},
		{name: "stdout full output then backslash c", args: []string{`%s\c`, "a"}, stdout: stdoutFull},
		{name: "stdout full cycling", args: []string{`%s\n`, "a", "b", "c", "d"}, stdout: stdoutFull},
		{name: "stdout full refused", args: []string{"%2147483647d", "1"}, stdout: stdoutFull},
		{name: "stdout closed refused with output", args: []string{`%2147483647d\n`, "1"}, stdout: stdoutClosed},
		{name: "stdout full refused with output", args: []string{`%2147483647d\n`, "1"}, stdout: stdoutFull},
		{name: "stdout closed output before refusal", args: []string{`x\n%2147483647d`, "1"}, stdout: stdoutClosed},
		{name: "stdout full output before refusal", args: []string{`x\n%2147483647d`, "1"}, stdout: stdoutFull},
		{name: "stdout full refused then bad number", args: []string{`%2147483647d%d\n`, "1", "abc"}, stdout: stdoutFull},
		{name: "stdout closed refused then bad number", args: []string{`%2147483647d%d\n`, "1", "abc"}, stdout: stdoutClosed},
		{name: "stdout full bad number then refused", args: []string{`%d%2147483647d\n`, "abc", "1"}, stdout: stdoutFull},
		{name: "stdout full long output", args: []string{`%s\n`, long}, stdout: stdoutFull},
		{name: "stdout closed long output", args: []string{`%s\n`, long}, stdout: stdoutClosed},
		{name: "stdout full long output then warning", args: []string{`%s\n%d\n`, long, "abc"}, stdout: stdoutFull},
		{name: "stdout full warning then long output", args: []string{`%d\n%s\n`, "abc", long}, stdout: stdoutFull},
		{name: "stdout full long output around warning", args: []string{`%s\n%d\n%s\n`, long, "abc", "x"}, stdout: stdoutFull},
		{name: "stdout closed long output around warning", args: []string{`%s\n%d\n%s\n`, long, "abc", "x"}, stdout: stdoutClosed},
		{name: "stdout full short then long around warning", args: []string{`%s\n%d\n%s\n`, "xxxxxxxxxx", "abc", long}, stdout: stdoutFull},
		{name: "stdout full warning then fatal", args: []string{`%d\n%z`, "abc"}, stdout: stdoutFull},
		{name: "stdout closed warning then fatal", args: []string{`%d\n%z`, "abc"}, stdout: stdoutClosed},
		{name: "stdout full warning then fatal no newline", args: []string{`%d%z`, "abc"}, stdout: stdoutFull},
	})
}

func TestPrintfHelpVersion(t *testing.T) {
	requireHelp(t, "printf", []string{"--help"}, 0)
	requireVersion(t, "printf", []string{"--version"}, 0)
}
