package coreutils

import "testing"

func TestSeqParity(t *testing.T) {
	requireParity(t, "seq", []invocation{
		// The three synopses, and the empty ranges between them.
		{name: "one operand", args: []string{"5"}},
		{name: "one operand zero", args: []string{"0"}},
		{name: "one operand negative", args: []string{"-1"}},
		{name: "two operands", args: []string{"2", "5"}},
		{name: "two operands descending", args: []string{"5", "2"}},
		{name: "three operands", args: []string{"1", "2", "10"}},
		{name: "negative increment", args: []string{"10", "-3", "1"}},
		{name: "increment overshoots", args: []string{"1", "2", "1"}},
		{name: "negative increment overshoots", args: []string{"1", "-1", "1"}},
		{name: "first equals last", args: []string{"1", "1", "1"}},
		{name: "last below first", args: []string{"1", "1", "0"}},
		{name: "descending needs a negative increment", args: []string{"1", "-1", "3"}},
		{name: "descending with a positive one", args: []string{"3", "1"}},
		{name: "wide descending", args: []string{"5", "-5"}},

		// Fractional sequences: the precision comes from the spelling.
		{name: "tenths", args: []string{"0", "0.1", "1"}},
		{name: "three tenths", args: []string{"1", "0.3", "2"}},
		{name: "leading dot increment", args: []string{"1", ".1", "1.3"}},
		{name: "half step", args: []string{"0.5", "1.5"}},
		{name: "one decimal from the first", args: []string{"1.0", "3"}},
		{name: "one decimal from the last", args: []string{"0.0", "1", "2"}},
		{name: "two decimals", args: []string{"1.00", "1", "3"}},
		{name: "trailing point", args: []string{"1."}},
		{name: "leading dot", args: []string{".5"}},
		{name: "negative leading dot", args: []string{"-.5"}},
		{name: "plus sign", args: []string{"+5"}},
		{name: "leading blank", args: []string{" 5"}},
		{name: "trailing blank is invalid", args: []string{"5 "}},
		{name: "quarters", args: []string{"1", "2.5e-1", "2"}},
		{name: "two decimal operands", args: []string{"0.10", "0.20", "0.5"}},
		{name: "tenths through a third", args: []string{"0.1", "0.1", "0.3"}},
		{name: "tenths to a long last", args: []string{"1", "0.1", "1.30000000001"}},
		{name: "tenths crossing one", args: []string{"0.9", "0.1", "1.1"}},
		{name: "tenths descending", args: []string{"1.1", "-0.1", "0.9"}},
		{name: "thirds", args: []string{"0", ".3", ".9"}},
		{name: "fifths", args: []string{"0.1", "0.2", "0.7"}},
		{name: "hundred thousandths", args: []string{"0", "1e-5", "1e-4"}},
		{name: "last between terms", args: []string{"1", "0.1", "1.05"}},
		{name: "last just under a term", args: []string{"0", "0.1", "0.2999999"}},
		{name: "last just over a term", args: []string{"0", "0.1", "0.30000000000000000001"}},
		{name: "last just under in the last bit", args: []string{"0", "0.1", "0.29999999999999999999"}},
		{name: "descending thirds", args: []string{"2", "-0.3", "1.1"}},
		{name: "sevenths", args: []string{"0", "0.7", "2.1"}},
		{name: "descending tenths", args: []string{"1", "-0.1", "0.7"}},
		{name: "tenths to seven tenths", args: []string{"0.1", "0.1", "0.7"}},
		{name: "integer steps to a half", args: []string{"1", "1", "3.5"}},
		{name: "integer steps just short", args: []string{"1", "1", "2.5"}},
		{name: "descending to a half", args: []string{"5", "-1", "2.5"}},
		{name: "step of three to a half", args: []string{"1", "3", "6.5"}},
		{name: "last rounds up to an integer", args: []string{"1", "1", "2.9999999999999999999"}},
		{name: "last stays below an integer", args: []string{"1", "1", "2.999999999999"}},
		{name: "thirtieths", args: []string{"1e-30", "1e-30", "3e-30"}},

		// Exponents: the precision moves with them.
		{name: "exponent last", args: []string{"1e2"}},
		{name: "exponent both ends", args: []string{"1e-3", "1e-2"}},
		{name: "fractional exponent", args: []string{"1.5e1"}},
		{name: "exponent one", args: []string{"1e1"}},
		{name: "exponent with a decimal", args: []string{"1.0e1"}},
		{name: "capital exponent", args: []string{"1E0", "2"}},
		{name: "capital exponent with a decimal", args: []string{"1.5E0", "2"}},
		{name: "positive exponent sign", args: []string{"5e0", "1e1"}},
		{name: "exponent as the increment", args: []string{"1", "1e0", "3"}},
		{name: "exponent operands", args: []string{"1e2", "1", "1e2"}},
		{name: "exponent last equals first", args: []string{"100", "1", "1e2"}},
		{name: "big exponent", args: []string{"1e30"}, limit: 4096},
		{name: "tiny exponent", args: []string{"1e-400"}},

		// Hex operands: no precision of their own.
		{name: "hex last", args: []string{"0x10"}},
		{name: "hex range", args: []string{"0xa", "0xf"}},
		{name: "hex capital", args: []string{"0X10"}},
		{name: "hex fraction", args: []string{"0x1.8"}},
		{name: "hex power", args: []string{"0x1p3"}},
		{name: "hex power with a sign", args: []string{"+0x1p3"}},
		{name: "hex power negative", args: []string{"0x1p-1", "0.25", "1"}},
		{name: "hex first with a float last", args: []string{"0xa", "1", "12.5"}},
		{name: "hex everywhere", args: []string{"0x10", "0x10", "0x40"}},
		{name: "hex increment", args: []string{"1", "0x2", "5"}},
		{name: "hex with a fractional step", args: []string{"0x1", "1.5", "4"}},
		{name: "hex fraction first", args: []string{"0x1.8", "1", "4"}},
		{name: "hex half first", args: []string{"0x1p-1", "1", "3"}},
		{name: "hex half last", args: []string{"1", "1", "0x1p-1"}},
		{name: "hex last power", args: []string{"0xa", "3", "0x1p4"}},
		{name: "hex increment of one", args: []string{"1e2", "0x1", "103"}},
		{name: "hex and a fractional first", args: []string{"1.5", "0x1", "4"}},
		{name: "hex fraction and a fractional step", args: []string{"0x1.8", "1.25", "5"}},
		{name: "hex power and a fractional step", args: []string{"0x1p0", "1.5", "4"}},
		{name: "capital hex power", args: []string{"0X1P1", "1.5", "5"}},
		{name: "capital P is not a hex float", args: []string{"0x1P1", "1.5", "5"}},
		{name: "lowercase p is", args: []string{"0X1p1", "1.5", "5"}},
		{name: "hex power plus sign", args: []string{"0x1p+1", "1.5", "5"}},
		{name: "hex e is not an exponent", args: []string{"0x1e-1", "1.5", "40"}},
		{name: "hex leading point", args: []string{"0x.8", "1.25", "5"}},
		{name: "hex trailing point", args: []string{"0x1.", "1.5", "4"}},
		{name: "hex point zero", args: []string{"0x1.0", "1", "3"}},
		{name: "hex digits look like an exponent", args: []string{"0x1e1", "1.5", "485"}},
		{name: "hex power increment", args: []string{"0x1p1", "0x1p1", "8"}},
		{name: "hex half increment", args: []string{"1.5", "0x1p-1", "4"}},
		{name: "hex capital digit", args: []string{"0xA.8", "1", "12"}},
		{name: "hex everywhere with a step", args: []string{"0x1", "0x1", "0xc"}},
		{name: "fractional first hex step", args: []string{"1.25", "0x1", "4"}},
		{name: "capital P half", args: []string{"0x1P-1", "1", "3"}},
		{name: "capital P fraction", args: []string{"0X1.8P0", "1", "4"}},
		{name: "capital P counts whole", args: []string{"0X3P-1", "1", "5"}},
		{name: "capital P quarter", args: []string{"0X1P-2", "1", "3"}},
		{name: "negative capital P halves", args: []string{"--", "-0X1P-1", "1", "3"}},

		// A LAST with no precision of its own sends the whole sequence to
		// %g, though its precision never RAISES the derived one — that is
		// what separates `seq 0.5 0.5 0x1.8` from `seq 0.5 0.5 0x2`, whose
		// LAST is a hex integer and asks for precision 0, and both from
		// `seq 1 1 1.5`, whose one decimal is ignored.
		{name: "hex power last gives up the precision", args: []string{"1", "0.5", "0x1p2"}},
		{name: "hex fraction last gives up the precision", args: []string{"0.5", "0.5", "0x1.8"}},
		{name: "hex last with a long increment", args: []string{"-0.3", "0.35000005", "0x1.8"}},
		{name: "hex integer last keeps the precision", args: []string{"0.5", "0.5", "0x2"}},
		{name: "hex integer last keeps two decimals", args: []string{"1", "0.25", "0x2"}},
		{name: "equal width hex fraction last", args: []string{"-w", "0.5", "0.5", "0x1.8"}},
		{name: "equal width hex power last", args: []string{"-w", "1", "0.5", "0x1p2"}},

		// -w: the width the spellings ask for.
		{name: "equal width", args: []string{"-w", "1", "10"}},
		{name: "equal width across zero", args: []string{"-w", "-5", "5"}},
		{name: "equal width with decimals", args: []string{"-w", "0.5", "0.25", "2"}},
		{name: "equal width exponent", args: []string{"-w", "1e2"}},
		{name: "equal width tiny exponents", args: []string{"-w", "-1e-2", "1e-2", "3e-2"}},
		{name: "equal width descending", args: []string{"-w", "10", "-1", "1"}},
		{name: "equal width one term", args: []string{"-w", "0.1", "1"}},
		{name: "equal width halves", args: []string{"-w", "1", "0.5", "3"}},
		{name: "equal width leading zeros", args: []string{"-w", "010", "2", "20"}},
		{name: "equal width three digits", args: []string{"-w", "001", "003"}},
		{name: "equal width leading dot", args: []string{"-w", ".1", "1"}},
		{name: "equal width negative half", args: []string{"-w", "-0.5", "0.5"}},
		{name: "equal width nine to ten", args: []string{"-w", "9", "10"}},
		{name: "equal width ninety nine", args: []string{"-w", "99", "100"}},
		{name: "equal width descending negatives", args: []string{"-w", "-9", "-10"}},
		{name: "equal width ascending negatives", args: []string{"-w", "-10", "-9"}},
		{name: "equal width exponent first", args: []string{"-w", "1e1", "12"}},
		{name: "equal width decimal exponent", args: []string{"-w", "1.0e1", "12"}},
		{name: "equal width negative exponent", args: []string{"-w", "1e-1", "1"}},
		{name: "equal width negative zero", args: []string{"-w", "-0", "1"}},
		{name: "equal width negative zeros", args: []string{"-w", "-00", "1", "2"}},
		{name: "equal width plus zeros", args: []string{"-w", "+00", "1", "2"}},
		{name: "equal width descending halves", args: []string{"-w", "0", "-0.5", "-1"}},
		{name: "equal width to a negative", args: []string{"-w", "1", "-1", "-1"}},
		{name: "equal width from a negative", args: []string{"-w", "-1", "1"}},
		{name: "equal width exponent last", args: []string{"-w", "100", "1e2"}},
		{name: "equal width trailing zero", args: []string{"-w", "1.50", "2"}},
		{name: "equal width two decimals", args: []string{"-w", "1.5", "0.50", "2"}},
		{name: "equal width three decimals", args: []string{"-w", "1", "0.001", "1.003"}},
		{name: "equal width zero", args: []string{"-w", "0.0"}},
		{name: "equal width negative zero alone", args: []string{"-w", "-0"}},
		{name: "equal width exponent increment", args: []string{"-w", "1", "1e-1", "1.2"}},
		{name: "equal width thousandths", args: []string{"-w", "1e-3", "1e-3", "3e-3"}},
		{name: "equal width hundred thousandths", args: []string{"-w", "0", "1e-5", "3e-5"}},
		{name: "equal width mixed exponents", args: []string{"-w", "1e-2", "1", "1.5"}},
		{name: "equal width three decimal first", args: []string{"-w", "1.000", "2"}},
		{name: "equal width halves to three", args: []string{"-w", "1.5", "0.5", "3"}},
		{name: "equal width negative halves", args: []string{"-w", "-1.5", "0.5", "0"}},
		{name: "equal width half first", args: []string{"-w", "0.5", "1", "3"}},
		{name: "equal width descending to a half", args: []string{"-w", "3", "-1", "0.5"}},
		{name: "equal width negative exponent zero", args: []string{"-w", "-1e0", "1"}},
		{name: "equal width plus exponent", args: []string{"-w", "1e+0", "2"}},
		{name: "equal width minus exponent", args: []string{"-w", "1e-0", "2"}},
		{name: "equal width shifted exponent", args: []string{"-w", "10e-1", "2"}},
		{name: "equal width shifted exponent range", args: []string{"-w", "10e-1", "1", "3"}},
		{name: "equal width shifted increment", args: []string{"-w", "1", "10e-1", "3"}},
		{name: "equal width hex", args: []string{"-w", "0x10", "20"}},
		{name: "equal width hex power", args: []string{"-w", "0x1p4", "17"}},
		{name: "equal width hex half", args: []string{"-w", "0x1p-1", "1"}},
		{name: "equal width hex increment", args: []string{"-w", "1", "0x1p-1", "2"}},
		{name: "equal width hex fraction", args: []string{"-w", "0x1.8p0", "2"}},
		{name: "equal width hex integer", args: []string{"-w", "0x1", "5"}},
		{name: "equal width hex integer wider", args: []string{"-w", "0x1", "99"}},
		{name: "equal width hex sixteen", args: []string{"-w", "0x10", "999"}},
		{name: "equal width hex ff", args: []string{"-w", "0xff", "999"}},
		{name: "equal width hex capital power", args: []string{"-w", "0X1P4", "999"}},
		{name: "equal width hex last", args: []string{"-w", "1", "1", "0x5"}},
		{name: "equal width hex both", args: []string{"-w", "0x1", "0x5"}},
		{name: "equal width hex negative", args: []string{"-w", "-0x1", "2"}},
		{name: "equal width hex first with a step", args: []string{"-w", "0x1", "1", "12"}},
		{name: "equal width hex step", args: []string{"-w", "1", "0x1", "12"}},
		{name: "equal width hex big last", args: []string{"-w", "1", "1", "0x3e8"}},
		{name: "equal width big step", args: []string{"-w", "1", "100", "5"}},
		{name: "equal width big step range", args: []string{"-w", "1", "100", "500"}},
		{name: "equal width negative big step", args: []string{"-w", "1", "-100", "-5"}},
		{name: "equal width negative big step empty", args: []string{"-w", "5", "-100", "1"}},
		{name: "equal width quarter step", args: []string{"-w", "1.5", "0.25", "2"}},
		{name: "equal width fractional step", args: []string{"-w", "1", "1.25", "3"}},
		{name: "equal width eighth step", args: []string{"-w", "1", "0.125", "1.5"}},
		{name: "equal width negative exponent first", args: []string{"-w", "-.5e1", "1", "-3"}},
		{name: "equal width shifted negative", args: []string{"-w", "-12e-1", "1", "0"}},
		{name: "equal width leading zero exponent", args: []string{"-w", "01e1", "1", "12"}},
		{name: "equal width big negative", args: []string{"-w", "-1e5", "1", "-99998"}},
		{name: "equal width plus exponent first", args: []string{"-w", "+1e2", "1", "102"}},
		{name: "equal width negative leading zero", args: []string{"-w", "-01e1", "1", "-8"}},
		{name: "equal width leading dot exponent", args: []string{"-w", ".5e1", "1", "7"}},
		{name: "equal width leading zeros decimal", args: []string{"-w", "00.5", "1", "2"}},
		{name: "equal width negative leading zeros", args: []string{"-w", "-00.5", "1", "2"}},
		{name: "equal width trailing point exponent", args: []string{"-w", "1.e1", "1", "12"}},
		{name: "equal width trailing point negative exponent", args: []string{"-w", "1.e-1", "1", "2"}},
		{name: "equal width shifted trailing point", args: []string{"-w", "10.e-1", "1", "2"}},
		{name: "equal width zero exponent halves", args: []string{"-w", "1e-0", "0.5", "2"}},
		{name: "equal width decimal zero exponent", args: []string{"-w", "1.0e-0", "0.5", "2"}},
		{name: "equal width negative zero exponent", args: []string{"-w", "-1e-0", "0.5", "0"}},
		{name: "equal width last exponent", args: []string{"-w", "1", "1", "1e1"}},
		{name: "equal width last trailing point exponent", args: []string{"-w", "1", "1", "1.e1"}},
		{name: "equal width last shifted", args: []string{"-w", "1", "1", "100e-1"}},
		{name: "equal width last shifted twice", args: []string{"-w", "1", "1", "0.1e2"}},
		{name: "equal width last leading dot", args: []string{"-w", "1", "1", ".1e2"}},
		{name: "equal width last leading zeros", args: []string{"-w", "1", "1", "00.1e2"}},
		{name: "equal width last many leading zeros", args: []string{"-w", "1", "1", "000.01e3"}},
		{name: "equal width last fractional exponent", args: []string{"-w", "1", "1", "12.5e-1"}},
		{name: "equal width last shifted up", args: []string{"-w", "1", "1", "1.25e1"}},
		{name: "equal width last shifted down", args: []string{"-w", "1", "1", "125e-2"}},
		{name: "equal width last plus", args: []string{"-w", "1", "1", "+10"}},
		{name: "equal width last trailing point", args: []string{"-w", "1", "1", "10."}},
		{name: "equal width last decimal", args: []string{"-w", "1", "1", "10.0"}},
		{name: "equal width first decimal", args: []string{"-w", "1.0", "1", "10"}},
		{name: "equal width first two decimals", args: []string{"-w", "1.00", "1", "10"}},
		{name: "equal width first half", args: []string{"-w", "1.5", "1", "10"}},
		{name: "equal width fractional step to ten", args: []string{"-w", "1", "1.5", "10"}},
		{name: "equal width half step to ten", args: []string{"-w", "1", "0.5", "10."}},
		{name: "equal width half first and step", args: []string{"-w", "1.5", "0.5", "010"}},
		{name: "equal width last has a half", args: []string{"-w", "1", "1", "1.5"}},
		{name: "equal width last has a half wider", args: []string{"-w", "1", "1", "100.5"}},
		{name: "equal width last has quarters", args: []string{"-w", "1", "1", "1000.25"}},
		{name: "equal width tiny", args: []string{"-w", "1e-30", "1e-30", "3e-30"}},
		{name: "equal width tiny to one", args: []string{"-w", "1e-30", "1"}},
		{name: "equal width big last", args: []string{"-w", "1", "1e+05"}, limit: 4096},

		// -f: one printf float conversion, and every way to get it wrong.
		{name: "format g", args: []string{"-f", "%g", "3"}},
		{name: "format f with a precision", args: []string{"-f", "%.3f", "1", "0.5", "2"}},
		{name: "format e with a width", args: []string{"-f", "%5.2e", "1", "3"}},
		{name: "format with literal text", args: []string{"-f", "x%gy", "2"}},
		{name: "format is only percents", args: []string{"-f", "%%", "2"}},
		{name: "format d is not a float", args: []string{"-f", "%d", "3"}},
		{name: "format is empty", args: []string{"-f", "", "3"}},
		{name: "format s is not a float", args: []string{"-f", "%s", "3"}},
		{name: "format has two directives", args: []string{"-f", "%g %g", "3"}},
		{name: "format ends in a percent", args: []string{"-f", "%", "3"}},
		{name: "format left justified", args: []string{"-f", "%-5g|", "3"}},
		{name: "format zero padded", args: []string{"-f", "%010.3f", "3"}},
		{name: "format plus flag", args: []string{"-f", "%+g", "3"}},
		{name: "format space flag", args: []string{"-f", "% g", "3"}},
		{name: "format hash flag", args: []string{"-f", "%#g", "3"}},
		{name: "format quote flag", args: []string{"-f", "%'g", "3"}},
		{name: "format long modifier", args: []string{"-f", "%Lg", "3"}},
		{name: "format l modifier is not allowed", args: []string{"-f", "%lg", "3"}},
		{name: "format a", args: []string{"-f", "%a", "3"}},
		{name: "format capital A", args: []string{"-f", "%A", "3"}},
		{name: "format capital E", args: []string{"-f", "%E", "3"}},
		{name: "format capital G", args: []string{"-f", "%G", "3"}},
		{name: "format capital F", args: []string{"-f", "%F", "3"}},
		{name: "format star width", args: []string{"-f", "%*g", "3"}},
		{name: "format star precision", args: []string{"-f", "%.*g", "3"}},
		{name: "format positional", args: []string{"-f", "%1$g", "3"}},
		{name: "format percent after", args: []string{"-f", "%g%%", "2"}},
		{name: "format percent before", args: []string{"-f", "%%%g", "2"}},
		{name: "format trailing bare percent", args: []string{"-f", "%g%", "2"}},
		{name: "format width then percent", args: []string{"-f", "%5%", "2"}},
		{name: "format zero flag alone", args: []string{"-f", "%0g", "2"}},
		{name: "format empty precision", args: []string{"-f", "%.g", "2"}},
		{name: "format minus alone", args: []string{"-f", "%-g", "2"}},
		{name: "format two minuses", args: []string{"-f", "%--g", "2"}},
		{name: "format every flag", args: []string{"-f", "%-+ #0g", "2"}},
		{name: "format two precisions", args: []string{"-f", "%1.1.1g", "2"}},
		{name: "format width beyond an int", args: []string{"-f", "%9999999999g", "1"}},
		{name: "format width one past an int", args: []string{"-f", "%2147483648g", "1"}},
		{name: "format precision past an int", args: []string{"-f", "%.2147483648g", "1"}},
		{name: "format two long modifiers", args: []string{"-f", "%LLg", "1.5"}},
		{name: "format h modifier", args: []string{"-f", "%hg", "1.5"}},
		{name: "format q modifier", args: []string{"-f", "%qg", "1.5"}},
		{name: "format width and nothing else", args: []string{"-f", "%5", "1.5"}},
		{name: "format point and nothing else", args: []string{"-f", "%.", "1.5"}},
		{name: "format long modifier alone", args: []string{"-f", "%L", "1.5"}},
		{name: "format long x", args: []string{"-f", "%Lx", "1.5"}},
		{name: "format width then long", args: []string{"-f", "%5L", "1.5"}},
		{name: "format long d", args: []string{"-f", "%Ld", "1.5"}},
		{name: "format four percents then g", args: []string{"-f", "%%%%%g", "1.5"}},
		{name: "format escaped percent g", args: []string{"-f", "%%g", "1.5"}},
		{name: "format percents around", args: []string{"-f", "%%%g%%", "1.5"}},
		{name: "format two g directives", args: []string{"-f", "%g%g", "1.5"}},
		{name: "format a with no precision digits", args: []string{"-f", "%.0a", "1.5"}},
		{name: "format a with a hash", args: []string{"-f", "%#a", "1.5"}},
		{name: "format long f with a width", args: []string{"-f", "%15.3Lf", "1.5"}},
		{name: "format rounds to even", args: []string{"-f", "%.0f", "0.5", "1", "2.5"}},
		{name: "format e over a range", args: []string{"-f", "%e", "100", "100", "300"}},
		{name: "format e across zero", args: []string{"-f", "%5.1e", "-1", "1", "1"}},
		{name: "format g over halves", args: []string{"-f", "%g", "1", "0.5", "2"}},
		{name: "format thirty decimals", args: []string{"-f", "%.30f", "0.1", "0.1", "0.3"}},
		{name: "format g over a big range", args: []string{"-f", "%g", "1e18", "1e18", "3e18"}},
		{name: "format too coarse to advance", args: []string{"-f", "%g", "1000000", "1", "1000002"}},
		{name: "format a over halves", args: []string{"-f", "%a", "1", "0.5", "3"}},
		{name: "format e with no decimals", args: []string{"-f", "%.0e", "1", "0.5", "3"}},
		{name: "format g over tenths", args: []string{"-f", "%g", "0", "0.1", "0.3"}},
		{name: "format e over thirds", args: []string{"-f", "%.1e", "0", "0.3", "0.9"}},
		{name: "format g across zero", args: []string{"-f", "%g", "-1", "1"}},
		{name: "format g over tenths again", args: []string{"-f", "%g", "0.1", "0.1", "0.3"}},
		{name: "format with a newline", args: []string{"-f", "%g\n", "2"}},
		{name: "format left justified loses the last term", args: []string{"-f", "%-8.1f", "0", "0.3", "0.9"}},
		{name: "format right justified keeps it", args: []string{"-f", "%5.1f", "0", "0.3", "0.9"}},
		{name: "format twenty decimals stops early", args: []string{"-f", "%.20f", "0", "0.3", "0.9"}},
		{name: "format no decimals stops early", args: []string{"-f", "%.0f", "0", "0.3", "0.9"}},
		{name: "format two decimals keeps it", args: []string{"-f", "%.2f", "0", "0.3", "0.9"}},

		// A term past LAST is printed only when its own text reads back
		// as LAST ITSELF and differs, AS TEXT, from the text just
		// printed.
		//
		// Reading back merely inside the range does not do it, which is
		// what separates `%.1f 0 0.36 0.7` from `%.1f 0 0.36 0.71` —
		// same terms, same text, and only the first prints its 0.72 as
		// `0.7`. A hex conversion therefore never prints this term at
		// all: at full precision it reads back as the out-of-range
		// value, and cut short it lands under LAST.
		//
		// The second half is a text comparison and not a value one in
		// both directions: two terms that print the same bytes end the
		// sequence even though their values differ, and `0.0` followed
		// by `-0.0` does not even though the two values are equal.
		{name: "extra term reads back as last", args: []string{"-f", "%.1f", "0", "0.36", "0.7"}},
		{name: "extra term reads back short of last", args: []string{"-f", "%.1f", "0", "0.36", "0.71"}},
		{name: "extra term short of a fractional last", args: []string{"-f", "%.1f", "0", "0.36", "0.715"}},
		{name: "extra term reads back as an integer last", args: []string{"-f", "%.0f", "0", "0.6", "1.2"}},
		{name: "extra term short of an integer last", args: []string{"-f", "%.0f", "0", "0.6", "1.1"}},
		{name: "extra term short with a rounded step", args: []string{"-f", "%.0f", "0", "0.7000005", "1.4"}},
		{name: "extra term short in e", args: []string{"-f", "%.0e", "0", "0.7000005", "1.4"}},
		{name: "extra term short in g", args: []string{"-f", "%.1g", "0", "0.7000005", "1.4"}},
		{name: "extra term short of a quarter last", args: []string{"-f", "%.1f", "0", "0.26", "0.51"}},
		{name: "extra term as a quarter last", args: []string{"-f", "%.1f", "0", "0.26", "0.5"}},
		{name: "a cuts the extra term under last", args: []string{"-f", "%.3a", "0", "0.3", "0.9"}},
		{name: "a cuts it under a lower last", args: []string{"-f", "%.3a", "0", "0.3", "0.8999999"}},
		{name: "a with no digits cuts it too", args: []string{"-f", "%.0a", "0", "0.3", "0.88"}},
		{name: "a at full precision keeps the term out", args: []string{"-f", "%a", "0", "0.3", "0.9"}},
		{name: "extra term reads back as last but repeats it", args: []string{"-f", "%.1f", "1", "1e-18", "1"}},
		{name: "a step too small to advance at all", args: []string{"-f", "%g", "1", "1e-18", "1"}},
		{name: "extra term repeats a whole number", args: []string{"-f", "%.0f", "0.71", "0.35000005", "5"}},
		{name: "extra term repeats one below last", args: []string{"-f", "%.0f", "0.71", "0.35000005", "4.9"}},
		{name: "the same term inside the range", args: []string{"-f", "%.0f", "0.71", "0.35000005", "5.3"}},
		{name: "extra term differs only in its sign", args: []string{"-f", "%.1f", "0", "-1e-18", "0"}},
		{name: "extra term repeats a signed zero", args: []string{"-f", "%.1f", "0", "1e-18", "0"}},
		{name: "extra term after a negative zero first", args: []string{"-f", "%.1f", "-0.0", "1e-18", "0"}},
		{name: "extra term after a negative zero both ends", args: []string{"-f", "%.1f", "-0.0", "1e-18", "-0.0"}},
		{name: "extra term descending reads back as last", args: []string{"-f", "%.1f", "0.72", "-0.36", "0"}},
		{name: "extra term descending short of last", args: []string{"-f", "%.1f", "0.72", "-0.36", "0.01"}},
		{name: "format glued to the option", args: []string{"-f%g", "3"}},
		{name: "format that is not valid UTF-8", args: []string{"-f", "%g\xff", "2"}},

		// -s: any string between the numbers.
		{name: "separator comma", args: []string{"-s,", "5"}},
		{name: "separator empty", args: []string{"-s", "", "3"}},
		{name: "separator percent", args: []string{"-s", "%", "3"}},
		{name: "separator two letters", args: []string{"-s", "ab", "1", "0"}},
		{name: "separator with equal width", args: []string{"-w", "-s,", "8", "12"}},
		{name: "separator long option", args: []string{"--separator=,", "3"}},
		{name: "format long option", args: []string{"--format=%g", "3"}},
		{name: "equal width long option", args: []string{"--equal-width", "10"}},
		{name: "equal width and format conflict", args: []string{"-w", "-f", "%g", "10"}},
		{name: "format and equal width conflict", args: []string{"-f", "%g", "-w", "10"}},
		{name: "separator colon", args: []string{"-s:", "3"}},
		{name: "separator starting with a dash", args: []string{"-s-5", "3"}},
		{name: "separator over three terms", args: []string{"-s", ",", "1", "1", "3"}},
		{name: "separator with no terms", args: []string{"-s", ",", "0"}},
		{name: "separator tab", args: []string{"-s", "\t", "3"}},
		{name: "separator then equal width", args: []string{"-s,", "-w", "1", "5"}},
		{name: "separator newline over halves", args: []string{"-s", "\n", "0.5", "0.5", "1.5"}},
		{name: "separator two newlines", args: []string{"-s", "\n\n", "3"}},
		{name: "separator that is not valid UTF-8", args: []string{"-s", "\xff", "2"}},

		// Operands that are not numbers, and the ones that are out of range.
		{name: "not a number", args: []string{"x"}},
		{name: "not a number as the last", args: []string{"1", "x"}},
		{name: "not a number as the increment", args: []string{"1", "2", "x"}},
		{name: "empty operand", args: []string{""}},
		{name: "lone dash", args: []string{"-"}},
		{name: "dashdash then a negative", args: []string{"--", "-1"}},
		{name: "too many operands", args: []string{"1", "2", "3", "4"}},
		{name: "five operands name the fourth", args: []string{"1", "2", "3", "4", "5"}},
		{name: "five non-numbers name the fourth", args: []string{"a", "b", "c", "d", "e"}},
		{name: "no operands"},
		{name: "hex prefix with no digits", args: []string{"0x"}},
		{name: "underscore separator", args: []string{"1_000"}},
		{name: "comma separator", args: []string{"1,5"}},
		{name: "exponent with no digits", args: []string{"1e"}},
		{name: "exponent with only a sign", args: []string{"1e+"}},
		{name: "point alone", args: []string{"."}},
		{name: "dash point alone", args: []string{"-."}},
		{name: "dash point with a last", args: []string{"-.", "3"}},
		{name: "overflowing exponent", args: []string{"1e5000"}},
		{name: "overflowing exponent past the max", args: []string{"1.2e4932"}},
		{name: "largest exponent", args: []string{"1e4932", "1"}},
		{name: "overflowing hex power", args: []string{"0x1p16384", "1"}},
		{name: "largest hex power", args: []string{"0x1p16383", "1"}},
		{name: "underflow to zero", args: []string{"1e-4951", "1"}},
		{name: "underflow to a subnormal", args: []string{"4e-4951", "1"}},
		{name: "underflow to a subnormal five", args: []string{"5e-4951", "1"}},
		{name: "underflow past the smallest", args: []string{"1e-4950"}},
		{name: "smallest subnormal", args: []string{"0x1p-16445", "1"}},
		{name: "half the smallest subnormal", args: []string{"0x1p-16446", "1"}},
		{name: "smallest normal", args: []string{"0x1p-16382", "1"}},
		{name: "inexact subnormal", args: []string{"0x1.8p-16445", "1"}},
		{name: "increment underflows to zero", args: []string{"1", "1e-4951", "2"}},
		{name: "last underflows to zero", args: []string{"1", "1", "1e-4951"}},
		{name: "zero increment", args: []string{"1", "0", "3"}},
		{name: "zero increment descending", args: []string{"5", "0", "1"}},
		{name: "zero increment with decimals", args: []string{"1", "0.0", "3"}},
		{name: "negative zero increment", args: []string{"1", "-0.0", "1"}},
		{name: "all zeros", args: []string{"0", "0", "0"}},
		{name: "not a number word", args: []string{"nan"}},
		{name: "not a number as the increment word", args: []string{"1", "nan", "3"}},
		{name: "not a number as the first", args: []string{"nan", "1"}},
		{name: "not a number as the last word", args: []string{"1", "1", "nan"}},
		{name: "not a number with equal width", args: []string{"-w", "nan"}},
		{name: "not a number before a zero increment", args: []string{"nan", "0", "3"}},
		{name: "operand count is checked first", args: []string{"x", "2", "3", "4"}},
		{name: "increment is checked before the last", args: []string{"1", "0", "x"}},
		{name: "conflict is checked before the operands", args: []string{"-w", "-f", "%g", "x"}},
		{name: "operand count before the conflict", args: []string{"-w", "-f", "%g", "1", "2", "3", "4"}},
		{name: "format is checked before the operands", args: []string{"-f", "%d", "x"}},
		{name: "format before the zero increment", args: []string{"-f", "%d", "1", "0", "3"}},
		{name: "format before a missing operand", args: []string{"-f", "%d"}},
		{name: "conflict before a missing operand", args: []string{"-w", "-f", "%g"}},
		{name: "format before the conflict", args: []string{"-w", "-f", "%d", "x"}},
		{name: "format before the conflict either order", args: []string{"-f", "%d", "-w", "x"}},
		{name: "format and conflict with no operands", args: []string{"-w", "-f", "%d"}},
		{name: "operand count over four names", args: []string{"x", "y", "z", "w"}},
		{name: "operand count with a bad second", args: []string{"1", "x", "3", "4"}},
		{name: "operand count with a bad third", args: []string{"1", "2", "x", "4"}},
		{name: "format before a nan operand", args: []string{"-f", "%d", "1", "nan"}},
		{name: "format with no directive before operands", args: []string{"-f", "x", "1", "0", "3"}},
		{name: "operand that is not valid UTF-8", args: []string{"\xff"}},
		{name: "last that is not valid UTF-8", args: []string{"1", "\xff"}},
		{name: "blank operand", args: []string{"5", " "}},
		{name: "blank first operand", args: []string{" ", "5"}},
		{name: "trailing letter", args: []string{"5x"}},

		// The option scan: in order, and a negative number ends it.
		{name: "option after an operand is an operand", args: []string{"1", "--foo"}},
		{name: "invalid short option", args: []string{"-x"}},
		{name: "abbreviated format needs an argument", args: []string{"--form"}},
		{name: "abbreviated format with a value", args: []string{"--f", "3"}},
		{name: "abbreviated equal width", args: []string{"--e", "3"}},
		{name: "abbreviated separator", args: []string{"--s", ",", "3"}},
		{name: "format without a value", args: []string{"-f"}},
		{name: "separator without a value", args: []string{"-s"}},
		{name: "long format without a value", args: []string{"--format"}},
		{name: "equal width does not take a value", args: []string{"--equal-width=x"}},
		{name: "digit after a flag is an option", args: []string{"-w5"}},
		{name: "negative number ends the options", args: []string{"-5"}},
		{name: "negative number after a flag", args: []string{"-w", "-1"}},
		{name: "dashdash then operands", args: []string{"--", "1", "3"}},
		{name: "dashdash as an operand", args: []string{"1", "3", "--"}},
		{name: "negative float operands", args: []string{"-1.5", "-0.5"}},
		{name: "option after the first operand", args: []string{"2", "-w", "4"}},
		{name: "separator after an operand", args: []string{"3", "-s,"}},
		{name: "empty long option is ambiguous", args: []string{"--=x"}},
		{name: "empty long option with no value", args: []string{"--="}},
		{name: "three dashes", args: []string{"---w"}},
		{name: "negative number then options are operands", args: []string{"-5", "-f", "%g", "1"}},
		{name: "negative number then help is an operand", args: []string{"-5", "--help"}},
		{name: "flag glued to a negative", args: []string{"-w-5"}},
		{name: "format glued to a negative", args: []string{"-f-5"}},
		{name: "negative with a trailing letter", args: []string{"-1x"}},
		{name: "option after two operands", args: []string{"-1", "1", "-w"}},
		{name: "negative half then a last", args: []string{"-.5e1", "1"}},
		{name: "negative width", args: []string{"-w", "-.5", "1"}},
		{name: "negative descending", args: []string{"-w", "-1", "-3", "-9"}},
		{name: "posix does not permute", args: []string{"2", "-w", "4"}, env: []string{"POSIXLY_CORRECT=1"}},
		{name: "posix options before operands", args: []string{"-w", "1", "5"}, env: []string{"POSIXLY_CORRECT=1"}},

		// Infinities: a bound that is never reached, and one already past.
		{name: "infinite last", args: []string{"1", "inf", "2"}},
		{name: "negative infinite increment", args: []string{"1", "-inf", "-2"}},
		{name: "infinite increment with equal width", args: []string{"-w", "1", "inf", "2"}},
		{name: "infinite increment with a format", args: []string{"-f", "%g", "1", "inf", "2"}},
		{name: "negative infinite increment to zero", args: []string{"-w", "1", "-inf", "0"}},
		{name: "infinite first", args: []string{"inf", "1", "5"}},
		{name: "negative infinite first", args: []string{"--", "-inf", "1", "5"}, limit: 4096},
		{name: "negative infinite first with equal width", args: []string{"-w", "--", "-inf", "1", "5"}, limit: 4096},
		{name: "negative infinite last", args: []string{"1", "-inf"}},
		{name: "infinite last alone", args: []string{"inf", "1"}},
		{name: "infinite increment past the last", args: []string{"-w", "1", "inf", "100"}},
		{name: "negative infinite increment past", args: []string{"-w", "1", "-inf", "-100"}},
		{name: "descending to negative infinity", args: []string{"1", "1", "-inf"}},
		{name: "infinite increment between", args: []string{"-w", "100", "inf", "200"}},
		{name: "infinite bound", args: []string{"1", "1", "inf"}, limit: 4096},
		{name: "infinite bound with equal width", args: []string{"-w", "5", "1", "inf"}, limit: 4096},
		{name: "infinite bound with halves", args: []string{"-w", "1", "0.5", "inf"}, limit: 4096},
		{name: "infinite last operand", args: []string{"inf"}, limit: 4096},
		{name: "nan as the last", args: []string{"1", "nan"}},

		// Integers past what a long double holds exactly: the digit engine.
		{name: "past sixty four bits", args: []string{"18446744073709551615", "18446744073709551616"}},
		{name: "past sixty three bits negative", args: []string{"-9223372036854775809", "-9223372036854775808"}},
		{name: "ten to the twenty", args: []string{"100000000000000000000", "100000000000000000002"}},
		{name: "ten to the twenty by two", args: []string{"100000000000000000000", "2", "100000000000000000004"}},
		{name: "equal width gives up the digits", args: []string{"-w", "99999999999999999999", "100000000000000000001"}},
		{name: "one byte separator keeps them", args: []string{"-s,", "99999999999999999999", "100000000000000000001"}},
		{name: "two operands keep them", args: []string{"99999999999999999999", "100000000000000000001"}},
		{name: "explicit increment keeps them", args: []string{"99999999999999999999", "1", "100000000000000000001"}},
		{name: "increment of two", args: []string{"99999999999999999999", "2", "100000000000000000003"}},
		{name: "increment of three", args: []string{"99999999999999999999", "3", "100000000000000000002"}},
		{name: "a plus sign gives up the digits", args: []string{"+99999999999999999999", "1", "100000000000000000001"}},
		{name: "a plus increment gives up the digits", args: []string{"99999999999999999999", "+1", "100000000000000000001"}},
		{name: "leading zeros keep them", args: []string{"099999999999999999999", "1", "100000000000000000001"}},
		{name: "leading zero increment keeps them", args: []string{"99999999999999999999", "01", "100000000000000000001"}},
		{name: "a decimal increment gives up the digits", args: []string{"99999999999999999999", "1.0", "100000000000000000001"}},
		{name: "an exponent increment gives up the digits", args: []string{"99999999999999999999", "1e0", "100000000000000000001"}},
		{name: "negative range", args: []string{"-100000000000000000001", "1", "-99999999999999999999"}},
		{name: "negative range two operands", args: []string{"-100000000000000000001", "-99999999999999999999"}},
		{name: "descending past the range", args: []string{"100000000000000000001", "-1", "99999999999999999999"}},
		{name: "two byte separator gives up the digits", args: []string{"-s", "ab", "99999999999999999999", "1", "100000000000000000001"}},
		{name: "empty separator gives up the digits", args: []string{"-s", "", "99999999999999999999", "1", "100000000000000000001"}},
		{name: "a format gives up the digits", args: []string{"-f", "%.0f", "99999999999999999999", "1", "100000000000000000001"}},
		{name: "sixty four bit boundary", args: []string{"18446744073709551615", "1", "18446744073709551617"}},
		{name: "hundred and twenty eight bits", args: []string{"340282366920938463463374607431768211455", "1", "340282366920938463463374607431768211457"}},
		{name: "increment larger than the range", args: []string{"99999999999999999999", "100000000000000000001", "100000000000000000001"}},
		{name: "zeros only", args: []string{"000", "1", "3"}},
		{name: "many leading zeros in the last", args: []string{"1", "1", "000000000000000000000000000005"}},
		{name: "first equals last past the range", args: []string{"99999999999999999999", "1", "99999999999999999999"}},
		{name: "first past the last", args: []string{"100000000000000000001", "1", "99999999999999999999"}},
		{name: "increment of three past the range", args: []string{"5", "3", "99999999999999999999999999999999999"}, limit: 4096},
		{name: "increment at the limit", args: []string{"99999999999999999999", "200", "999999999999999999999"}, limit: 4096},
		{name: "increment past the limit", args: []string{"99999999999999999999", "201", "999999999999999999999"}, limit: 4096},
		{name: "increment well past the limit", args: []string{"99999999999999999999", "255", "999999999999999999999"}, limit: 4096},
		{name: "increment of a thousand", args: []string{"99999999999999999999", "1000", "999999999999999999999"}, limit: 4096},
		{name: "just past sixty four bits by a hundred", args: []string{"18446744073709551617", "100", "18446744073709551617"}},
		{name: "just past sixty four bits by a thousand", args: []string{"18446744073709551617", "1000", "18446744073709551617"}},
		{name: "ten to the twenty nine", args: []string{"100000000000000000000000000000", "100", "100000000000000000000000000000"}},
		{name: "ten to the twenty nine by a thousand", args: []string{"100000000000000000000000000000", "1000", "100000000000000000000000000000"}},
		{name: "either side of sixty four bits", args: []string{"18446744073709551614", "18446744073709551618"}},
		{name: "either side of sixty three bits", args: []string{"9223372036854775806", "9223372036854775810"}},
		{name: "equal width either side of sixty three bits", args: []string{"-w", "9223372036854775806", "9223372036854775810"}},
		{name: "separator either side of sixty four bits", args: []string{"-s,", "18446744073709551614", "18446744073709551618"}},
		{name: "exponent first past the range", args: []string{"1e19", "1", "10000000000000000002"}},
		{name: "digits first past the range", args: []string{"10000000000000000000", "1", "10000000000000000002"}},
		{name: "exponent increment past the range", args: []string{"1e19", "1e19", "4e19"}},
		{name: "a half past the range", args: []string{"12345678901234567890.5", "1", "12345678901234567892"}},
		{name: "leading zeros", args: []string{"007", "9"}},
		{name: "leading zero ten", args: []string{"010", "12"}},
		{name: "negative zero first", args: []string{"-00", "1"}},
		{name: "plus increment", args: []string{"1", "+1", "3"}},
		{name: "leading zero increment", args: []string{"1", "01", "3"}},
		{name: "equal width plus and zeros", args: []string{"-w", "+05", "7"}},
		{name: "equal width leading blank", args: []string{"-w", " 5", "7"}},
		{name: "equal width plus a half", args: []string{"-w", "+.5", "1"}},
		{name: "equal width plus zero point five", args: []string{"-w", "+0.5", "1"}},
		{name: "plus first", args: []string{"+5", "7"}},
		{name: "equal width plus first", args: []string{"-w", "+5", "7"}},
		{name: "big exponent range", args: []string{"1e18", "1e18", "3e18"}},
		{name: "equal width big exponent range", args: []string{"-w", "1e18", "1e18", "3e18"}},
		{name: "increment too small to advance", args: []string{"1", "1e-40", "1.0000000000000000000000000001"}, limit: 4096},
		{name: "tiny everything", args: []string{"1e-400", "1e-400", "1e-400"}},
		{name: "equal width tiny to one long", args: []string{"-w", "1e-400", "1"}},
		{name: "largest finite", args: []string{"1e4932", "1", "1e4932"}},
		// A term of zero carries the LONG DOUBLE's sign, which exact
		// decimal arithmetic cannot produce: 3 x 0.3 rounds to a hair
		// above 0.9, so the term that lands on zero is a hair below it
		// and prints `-0.0`. The same sequence one step shorter cancels
		// exactly and prints `0.0`.
		{name: "zero term is negative", args: []string{"-f", "%.1f", "0.9", "-0.3", "0"}},
		{name: "zero term is negative by default", args: []string{"0.9", "-0.3", "0"}},
		{name: "zero term is negative with equal width", args: []string{"-w", "0.9", "-0.3", "0"}},
		{name: "zero term is negative at two decimals", args: []string{"-f", "%.2f", "0.9", "-0.3", "0"}},
		{name: "zero term is negative mid sequence", args: []string{"-f", "%.1f", "0.9", "-0.3", "-0.3"}},
		{name: "zero term cancels exactly", args: []string{"-f", "%.1f", "0.6", "-0.3", "0"}},
		{name: "zero term cancels from a longer run", args: []string{"-f", "%.1f", "1.2", "-0.3", "0"}},
		{name: "zero term ascending", args: []string{"-f", "%.1f", "-0.9", "0.3", "0"}},
		{name: "zero term ascending in tenths", args: []string{"-f", "%.1f", "-0.3", "0.1", "0"}},
		{name: "negative zero", args: []string{"-0"}},
		{name: "negative zero to one", args: []string{"-0.0", "1"}},
		{name: "negative zero increment of zero", args: []string{"-0", "0"}},
		{name: "zero to negative zero", args: []string{"0", "-0"}},

		// One per long double a target can have. seq computes and prints
		// in C's `long double`, which is x87 80-bit extended on x86-64,
		// IEEE binary128 on arm64 and wasm32, and binary64 on Darwin
		// (#8513), so the corpus above only ever proves the format of the
		// host it runs on. These are the invocations whose bytes differ
		// between the three, measured against GNU on both an x86-64 and an
		// aarch64 host: how many hex digits `%a` carries and where its
		// point sits, how far the exact decimal tail of a tenth runs, which
		// precisions survive the round trip (LDBL_DIG is 18, 33 or 15),
		// where the subnormals stop, and the largest whole number the
		// format holds — which is the edge the digit and scaled-decimal
		// engines hand over at.
		{name: "a signature of each format", args: []string{"-f", "%a", "0.1", "0.1", "0.3"}},
		{name: "a of a tenth to three digits", args: []string{"-f", "%.3a", "0.1", "0.1", "0.3"}},
		{name: "decimal tail of a tenth", args: []string{"-f", "%.40f", "0.1", "0.1", "0.3"}},
		{name: "decimal tail of a tenth in e", args: []string{"-f", "%.30e", "0.1", "0.1", "0.3"}},
		{name: "decimal tail of a tenth in g", args: []string{"-f", "%.25g", "0.1", "0.1", "0.3"}},
		{name: "one past the x87 digit count", args: []string{"-f", "%.20f", "0.1", "0.1", "0.3"}},
		{name: "two past the x87 digit count", args: []string{"-f", "%.21f", "0.1", "0.1", "0.3"}},
		{name: "at the binary128 digit count", args: []string{"-f", "%.33f", "0.1", "0.1", "0.3"}},
		{name: "one past the binary128 digit count", args: []string{"-f", "%.34f", "0.1", "0.1", "0.3"}},
		{name: "a precision only a wide format carries", args: []string{"-f", "%.19f", "0.0000000000000000001", "0.0000000000000000001", "0.0000000000000000003"}},
		{name: "where each format's subnormals stop", args: []string{"6.5e-4966", "1"}},
		{name: "least binary128 subnormal", args: []string{"0x1p-16494", "1"}},
		{name: "equal width past the subnormals", args: []string{"-w", "6.5e-4966", "1"}},
		{name: "largest exactly held integer", args: []string{"-f", "%.0f", "18446744073709551615", "1", "18446744073709551617"}},
		{name: "rendered past the exactly held integer", args: []string{"+18446744073709551615", "1", "18446744073709551617"}},

		// Write failures: a closed descriptor and a full device.
		{name: "stdout closed", args: []string{"3"}, stdout: stdoutClosed},
		{name: "stdout full", args: []string{"3"}, stdout: stdoutFull},
		{name: "stdout closed with nothing to write", args: []string{"0"}, stdout: stdoutClosed},
		{name: "stdout full with nothing to write", args: []string{"0"}, stdout: stdoutFull},
		{name: "stdout closed on a usage error", args: []string{"x"}, stdout: stdoutClosed},
		{name: "stdout full on a usage error", args: []string{"x"}, stdout: stdoutFull},
		{name: "stdout closed over a float range", args: []string{"1", "0.5", "3"}, stdout: stdoutClosed},
		{name: "stdout full over a float range", args: []string{"1", "0.5", "3"}, stdout: stdoutFull},
		{name: "stdout closed with a format", args: []string{"-f", "%g", "1", "3"}, stdout: stdoutClosed},
		{name: "stdout full with a format", args: []string{"-f", "%g", "1", "3"}, stdout: stdoutFull},
		{name: "stdout closed with equal width", args: []string{"-w", "1", "10"}, stdout: stdoutClosed},
		{name: "stdout full with equal width", args: []string{"-w", "1", "10"}, stdout: stdoutFull},
		{name: "stdout closed over many blocks", args: []string{"100000"}, stdout: stdoutClosed},
		{name: "stdout full over many blocks", args: []string{"100000"}, stdout: stdoutFull},
		{name: "stdout closed on a refused format", args: []string{"-f", "%2147483648g", "1"}, stdout: stdoutClosed},
		{name: "stdout full on a refused format", args: []string{"-f", "%2147483648g", "1"}, stdout: stdoutFull},
		{name: "stdout closed past the digit engine", args: []string{"99999999999999999999", "100000000000000000001"}, stdout: stdoutClosed},

		// A bounded read of an endless sequence: both sides meet SIGPIPE.
		{name: "endless integers", args: []string{"1", "1", "inf"}, limit: 65536},
		{name: "endless with a separator", args: []string{"-s,", "inf"}, limit: 65536},
	})
}

func TestSeqHelpVersion(t *testing.T) {
	requireHelp(t, "seq", []string{"--help"}, 0)
	requireHelp(t, "seq", []string{"--h"}, 0)
	requireHelp(t, "seq", []string{"--help", "1"}, 0)
	requireHelp(t, "seq", []string{"-w", "--help"}, 0)
	requireHelp(t, "seq", []string{"--help", "--foo"}, 0)
	requireVersion(t, "seq", []string{"--version"}, 0)
	requireVersion(t, "seq", []string{"--v"}, 0)
	requireVersion(t, "seq", []string{"--version", "1"}, 0)
}
