package x86_64ssa

func emitReaderBytesHelper(w func(string, ...any)) {
	w("%s:", fnLabel("__method_Reader_read_chunk_bytes"))
	w("\tpush rbx")
	w("\tpush r12")
	w("\tpush r13")
	w("\tmov ebx, dword ptr [rdi + 8]")
	w("\tmov r12d, esi")
	w("\ttest r12d, r12d")
	w("\tjs .Lssa_rrbytes_invalid")
	w("\tmov edi, r12d")
	w("\tcall %s", fnLabel("__alloc_u8"))
	w("\tmov r13, rax")
	w("\tmov edi, ebx")
	w("\tmov rsi, r13")
	w("\tmov edx, r12d")
	w("\txor eax, eax")
	w("\tsyscall")
	w("\ttest rax, rax")
	w("\tjs .Lssa_rrbytes_error")
	w("\tmov dword ptr [r13 - 4], eax")
	ssaOptionBox(w, 0, "r13")
	w("\tjmp .Lssa_rrbytes_return")
	w(".Lssa_rrbytes_error:")
	w("\tneg rax")
	w("\tmov rbx, rax")
	w("\tlea rdi, [r13 - 16]")
	w("\tlea rsi, [r12 + 16]")
	w("\tcall %s", fnLabel("__free"))
	w("\tjmp .Lssa_rrbytes_box_error")
	w(".Lssa_rrbytes_invalid:")
	w("\tmov ebx, 22")
	w(".Lssa_rrbytes_box_error:")
	ssaEmptyString(w, "rsi")
	w("\tmov edi, ebx")
	w("\tcall %s", fnLabel("__fern_io_error"))
	w("\tmov rbx, rax")
	ssaOptionBox(w, 1, "rbx")
	w(".Lssa_rrbytes_return:")
	w("\tpop r13")
	w("\tpop r12")
	w("\tpop rbx")
	w("\tret")
}
