package arm64

// Append a clamped range from a borrowed packed byte array, reserving once.
func (g *generator) emitBufPushBytesRangeRuntime() {
	g.line(".global __fern_buf_push_bytes_range")
	g.typeDirective("__fern_buf_push_bytes_range")
	g.label("__fern_buf_push_bytes_range")
	g.emit("stp x29, x30, [sp, #-48]!")
	g.emit("mov x29, sp")
	g.emit("stp x19, x20, [sp, #16]")
	g.emit("stp x21, x22, [sp, #32]")
	g.emit("mov x19, x0")
	g.emit("mov x20, x1")
	g.emit("sxtw x21, w2")
	g.emit("sxtw x22, w3")
	g.emit("cmp x21, #0")
	g.emit("csel x21, x21, xzr, ge")
	g.emit("ldur w9, [x20, #-4]")
	g.emit("cmp x22, x9")
	g.emit("csel x22, x22, x9, le")
	g.emit("sub x22, x22, x21")
	g.emit("cmp x22, #0")
	g.emit("b.le .Lbufbyterange_done")
	g.emit("ldr x1, [x19, #8]")
	g.emit("add x1, x1, x22")
	g.emit("ldr x9, [x19, #16]")
	g.emit("cmp x1, x9")
	g.emit("b.ls .Lbufbyterange_fits")
	g.emit("bl __fern_buf_reserve")
	g.label(".Lbufbyterange_fits")
	g.emit("ldr x0, [x19]")
	g.emit("ldr x9, [x19, #8]")
	g.emit("add x0, x0, x9")
	g.emit("add x9, x9, x22")
	g.emit("str x9, [x19, #8]")
	g.emit("add x1, x20, x21")
	g.emit("mov x2, x22")
	g.emit("bl __fern_memcpy")
	g.label(".Lbufbyterange_done")
	g.emit("mov x0, #0")
	g.emit("ldp x21, x22, [sp, #32]")
	g.emit("ldp x19, x20, [sp, #16]")
	g.emit("ldp x29, x30, [sp], #48")
	g.emit("ret")
	g.sizeDirective("__fern_buf_push_bytes_range")
}

// Extract into the ordinary owned-array layout. The builder keeps its
// capacity and the result remains independent of subsequent pushes/free.
func (g *generator) emitBufTakeBytesRuntime() {
	g.line(".global __fern_buf_take_bytes")
	g.typeDirective("__fern_buf_take_bytes")
	g.label("__fern_buf_take_bytes")
	g.emit("stp x29, x30, [sp, #-16]!")
	g.emit("mov x29, sp")
	g.emit("stp x19, x20, [sp, #-16]!")
	g.emit("stp x21, x22, [sp, #-16]!")
	g.emit("mov x19, x0")
	g.emit("ldr x20, [x19, #8]")
	// Every payload byte is copied below. Initialize ordinary array metadata
	// without zero-filling bytes that the copy immediately overwrites.
	// Keep __alloc_u8's empty sentinel and invalid-length handling.
	g.emit("cmp w20, #0")
	g.emit("b.le .Lbuftake_bytes_alloc_special")
	g.emit("add w0, w20, #16")
	g.emit("bl __fern_alloc")
	g.emit("add x0, x0, #16")
	g.emit("stur w20, [x0, #-12]")
	g.emit("mov w1, #1")
	g.emit("stur w1, [x0, #-8]")
	g.emitArrayLenStore("w20", "x0")
	g.emit("b .Lbuftake_bytes_alloc_done")
	g.label(".Lbuftake_bytes_alloc_special")
	g.emit("mov x0, x20")
	g.emit("bl __alloc_u8")
	g.label(".Lbuftake_bytes_alloc_done")
	g.emit("mov x21, x0")
	g.emit("cbz x20, .Lbuftake_bytes_done")
	g.emit("ldr x1, [x19]")
	g.emit("mov x2, x20")
	g.emit("bl __fern_memcpy")
	g.label(".Lbuftake_bytes_done")
	g.emit("str xzr, [x19, #8]")
	g.emit("mov x0, x21")
	g.emit("ldp x21, x22, [sp], #16")
	g.emit("ldp x19, x20, [sp], #16")
	g.emit("ldp x29, x30, [sp], #16")
	g.emit("ret")
	g.sizeDirective("__fern_buf_take_bytes")
}
