#!/usr/bin/env python3
"""Regenerate wbdata.txt — the UAX #29 word-segmentation source data.

The companion to gen_gcbdata.py, and it exists for the same reason:
neither Go's `unicode` package nor CPython's `unicodedata` exposes
Word_Break, and this module has zero external dependencies (see go.mod),
so the data is derived offline and checked in. `uniseg` (PyPI) is the
oracle; it is a REGENERATION-time dependency only and never a dependency
of the module.

Run:  python3 -m pip install uniseg
      python3 cmd/unicodegen/gen_wbdata.py > cmd/unicodegen/wbdata.txt

Extended_Pictographic is NOT emitted here even though rule WB3c needs
it — gcbdata.txt already carries it, and one copy of a property is
enough.

Word_Break tracks the same UCD as the grapheme data and, like it, is
not frozen by a stability policy, so the emitted header records the
version the data came from.

Only non-Other WB ranges are emitted: Other is the default and covers
the overwhelming majority of code points, so storing it would multiply
the table for no information.
"""

import sys

from uniseg import unidata_version
from uniseg.wordbreak import word_break

MAX_CP = 0x110000


def runs(value_of, skip=None):
    """Coalesce equal adjacent values into (lo, hi, value) runs."""
    out = []
    run = None
    for cp in range(MAX_CP):
        v = value_of(cp)
        if run is not None and run[2] == v and run[1] == cp - 1:
            run = (run[0], cp, v)
            continue
        if run is not None and run[2] != skip:
            out.append(run)
        run = (cp, cp, v)
    if run is not None and run[2] != skip:
        out.append(run)
    return out


def main() -> None:
    out = sys.stdout
    out.write("# Generated by gen_wbdata.py -- do not edit by hand.\n")
    out.write("# UCD %s (uniseg)\n" % unidata_version)
    out.write("#\n")
    out.write("# W;<lo>;<hi>;<class>   Word_Break (non-Other only)\n")

    for lo, hi, v in runs(lambda cp: word_break(chr(cp)).name, skip="OTHER"):
        out.write("W;%04X;%04X;%s\n" % (lo, hi, v))


if __name__ == "__main__":
    main()
