#!/usr/bin/env python3
"""Regenerate wbdata.txt — the UAX #29 word-segmentation source data.

The companion to gen_gcbdata.py, and it exists for the same reason:
neither Go's `unicode` package nor CPython's `unicodedata` exposes
Word_Break, and this module has zero external dependencies (see go.mod),
so the data is derived offline from the Unicode Character Database files
of the release named on the command line, and checked in.

Run:  python3 cmd/unicodegen/gen_wbdata.py 17.0.0 > cmd/unicodegen/wbdata.txt

The UCD file is fetched from unicode.org; `--ucd DIR` reads
WordBreakProperty.txt from DIR instead.

Extended_Pictographic is NOT emitted here even though rule WB3c needs
it — gcbdata.txt already carries it, and one copy of a property is
enough.

Word_Break tracks the same UCD as the grapheme data and, like it, is
not frozen by a stability policy, so the emitted header records the
version the data came from. Class names are the UCD's property values in
upper case.

Only non-Other WB ranges are emitted: Other is the default and covers
the overwhelming majority of code points, so storing it would multiply
the table for no information.
"""

import os
import sys
import urllib.request

MAX_CP = 0x110000


def ucd_file(version: str, ucd_dir: str, path: str) -> str:
    if ucd_dir:
        with open(os.path.join(ucd_dir, os.path.basename(path)), encoding="utf-8") as f:
            return f.read()
    url = "https://www.unicode.org/Public/%s/ucd/%s" % (version, path)
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def property_values(text: str, wanted=None):
    """Code point -> value for a UCD property file (`cps ; value # ...`),
    optionally keeping only the values in `wanted`."""
    out = {}
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        cps, value = [x.strip() for x in body.split(";")[:2]]
        if wanted is not None and value not in wanted:
            continue
        lo, _, hi = cps.partition("..")
        for cp in range(int(lo, 16), int(hi or lo, 16) + 1):
            out[cp] = value
    return out


def parse_args():
    args = sys.argv[1:]
    if len(args) == 3 and args[1] == "--ucd":
        return args[0], args[2]
    if len(args) != 1:
        sys.exit("usage: %s VERSION [--ucd DIR]" % os.path.basename(sys.argv[0]))
    return args[0], ""


def runs(value_of, skip=None):
    """Coalesce equal adjacent values into (lo, hi, value) runs."""
    out = []
    run = None
    for cp in range(MAX_CP):
        v = value_of(cp)
        if run is not None and run[2] == v and run[1] == cp - 1:
            run = (run[0], cp, v)
            continue
        if run is not None and run[2] != skip:
            out.append(run)
        run = (cp, cp, v)
    if run is not None and run[2] != skip:
        out.append(run)
    return out


def main() -> None:
    version, ucd_dir = parse_args()
    wb = property_values(ucd_file(version, ucd_dir, "auxiliary/WordBreakProperty.txt"))

    out = sys.stdout
    out.write("# Generated by gen_wbdata.py -- do not edit by hand.\n")
    out.write("# UCD %s (unicode.org)\n" % version)
    out.write("#\n")
    out.write("# W;<lo>;<hi>;<class>   Word_Break (non-Other only)\n")

    for lo, hi, v in runs(lambda cp: wb.get(cp, "Other").upper(), skip="OTHER"):
        out.write("W;%04X;%04X;%s\n" % (lo, hi, v))


if __name__ == "__main__":
    main()
