#!/usr/bin/env python3
"""Regenerate normdata.txt — the canonical-normalization source data.

Go's `unicode` package ships no canonical decompositions and no combining
classes, and this module has zero external dependencies (see go.mod), so
`golang.org/x/text/unicode/norm` is not an option. CPython's `unicodedata`
is the oracle instead — the same one the full case / fold tables in
main.go were derived from.

Run:  python3 cmd/unicodegen/gen_normdata.py > cmd/unicodegen/normdata.txt

The output is deliberately raw per-code-point data, not pre-encoded
tables: coalescing and encoding live in main.go where they are covered by
Go tests and by the generator's own verify pass.

Hangul is absent by design. Its composition/decomposition is arithmetic
(the S/L/V/T base formula in UAX #15), not table data — `unicodedata`
reports an empty decomposition for a Hangul syllable even though it does
decompose. main.go implements the formula.
"""

import sys
import unicodedata as u

# Hangul syllables decompose algorithmically, so they must not be baked
# into the table; see the module docstring.
HANGUL = range(0xAC00, 0xD7A4)


def main() -> None:
    out = sys.stdout
    out.write("# Generated by gen_normdata.py -- do not edit by hand.\n")
    out.write("# UCD %s (CPython unicodedata)\n" % u.unidata_version)
    out.write("#\n")
    out.write("# C;<cp>;<ccc>        canonical combining class (nonzero only)\n")
    out.write("# D;<cp>;<cp> ...     canonical decomposition, fully expanded (NFD)\n")
    out.write("# P;<cp>;<a> <b>      primary composite: a+b recompose to cp under NFC\n")

    for cp in range(0x110000):
        ccc = u.combining(chr(cp))
        if ccc:
            out.write("C;%04X;%d\n" % (cp, ccc))

    for cp in range(0x110000):
        if cp in HANGUL:
            continue
        d = u.decomposition(chr(cp))
        if not d or d.startswith("<"):
            # Empty, or a compatibility mapping (<compat>, <font>, ...).
            # Only canonical mappings participate in NFC/NFD.
            continue
        # Store the FULL recursive expansion rather than the one-step
        # mapping, so NFD needs a single lookup and no fixpoint loop.
        # normalize("NFD") also applies canonical ordering, so the baked
        # expansion is already correctly ordered.
        full = u.normalize("NFD", chr(cp))
        out.write("D;%04X;%s\n" % (cp, " ".join("%04X" % ord(c) for c in full)))

        # Composition is NOT the inverse of the expansion above: NFC
        # recomposes one pair at a time, so it needs the ONE-STEP
        # canonical decomposition (U+1E69 is U+1E63 + U+0307, even though
        # it expands to three code points).
        parts = [int(x, 16) for x in d.split()]
        if len(parts) != 2:
            # A singleton decomposition never recomposes.
            continue
        # Emitting only the pairs that actually recompose folds the
        # Full_Composition_Exclusion property into the table: script
        # exclusions and non-starter decompositions simply never appear.
        # Testing it this way derives the property rather than trusting
        # CompositionExclusions.txt, which alone is not sufficient.
        if u.normalize("NFC", full) == chr(cp):
            out.write("P;%04X;%04X %04X\n" % (cp, parts[0], parts[1]))


if __name__ == "__main__":
    main()
