#!/usr/bin/env python3
"""Regenerate normdata.txt — the canonical-normalization source data.

Go's `unicode` package ships no canonical decompositions and no combining
classes, and this module has zero external dependencies (see go.mod), so
`golang.org/x/text/unicode/norm` is not an option. The data is read from
the Unicode Character Database itself, at the version named on the command
line, so it tracks the same release as the case tables main.go takes from
Go's `unicode` rather than whichever release the running interpreter's
`unicodedata` happens to carry (#10472).

Run:  python3 cmd/unicodegen/gen_normdata.py 17.0.0 > cmd/unicodegen/normdata.txt

The UCD files are fetched from unicode.org; `--ucd DIR` reads
UnicodeData.txt and DerivedNormalizationProps.txt from DIR instead.

The output is deliberately raw per-code-point data, not pre-encoded
tables: coalescing and encoding live in main.go where they are covered by
Go tests and by the generator's own verify pass.

Hangul is absent by design. Its composition/decomposition is arithmetic
(the S/L/V/T base formula in UAX #15), not table data, and UnicodeData.txt
lists no decomposition for a Hangul syllable even though it does
decompose. main.go implements the formula.
"""

import os
import sys
import urllib.request

# Hangul syllables decompose algorithmically, so they must not be baked
# into the table; see the module docstring.
HANGUL = range(0xAC00, 0xD7A4)


def ucd_file(version: str, ucd_dir: str, name: str) -> str:
    if ucd_dir:
        with open(os.path.join(ucd_dir, name), encoding="utf-8") as f:
            return f.read()
    url = "https://www.unicode.org/Public/%s/ucd/%s" % (version, name)
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def parse_unicode_data(text: str):
    """Combining classes and one-step canonical decompositions by code point."""
    ccc = {}
    decomp = {}
    for line in text.splitlines():
        if not line:
            continue
        f = line.split(";")
        cp = int(f[0], 16)
        if int(f[3]):
            ccc[cp] = int(f[3])
        # Empty, or a compatibility mapping (<compat>, <font>, ...): only
        # canonical mappings participate in NFC/NFD.
        if f[5] and not f[5].startswith("<"):
            decomp[cp] = [int(x, 16) for x in f[5].split()]
    return ccc, decomp


def parse_full_composition_exclusion(text: str):
    out = set()
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        cps, prop = [x.strip() for x in body.split(";")[:2]]
        if prop != "Full_Composition_Exclusion":
            continue
        lo, _, hi = cps.partition("..")
        for cp in range(int(lo, 16), int(hi or lo, 16) + 1):
            out.add(cp)
    return out


def nfd(cp: int, ccc, decomp):
    """The full canonical decomposition, canonically ordered (UAX #15)."""
    def expand(c):
        if c in decomp:
            return [x for d in decomp[c] for x in expand(d)]
        return [c]
    seq = expand(cp)
    # Canonical ordering: a stable sort by class within each run of
    # non-starters.
    i = 0
    while i < len(seq):
        if ccc.get(seq[i], 0) == 0:
            i += 1
            continue
        j = i
        while j < len(seq) and ccc.get(seq[j], 0) != 0:
            j += 1
        seq[i:j] = sorted(seq[i:j], key=lambda c: ccc[c])
        i = j
    return seq


def main() -> None:
    args = sys.argv[1:]
    ucd_dir = ""
    if len(args) == 3 and args[1] == "--ucd":
        ucd_dir = args[2]
    elif len(args) != 1:
        sys.exit("usage: gen_normdata.py VERSION [--ucd DIR]")
    version = args[0]
    ccc, decomp = parse_unicode_data(ucd_file(version, ucd_dir, "UnicodeData.txt"))
    excluded = parse_full_composition_exclusion(ucd_file(version, ucd_dir, "DerivedNormalizationProps.txt"))

    out = sys.stdout
    out.write("# Generated by gen_normdata.py -- do not edit by hand.\n")
    out.write("# UCD %s (unicode.org)\n" % version)
    out.write("#\n")
    out.write("# C;<cp>;<ccc>        canonical combining class (nonzero only)\n")
    out.write("# D;<cp>;<cp> ...     canonical decomposition, fully expanded (NFD)\n")
    out.write("# P;<cp>;<a> <b>      primary composite: a+b recompose to cp under NFC\n")

    for cp in sorted(ccc):
        out.write("C;%04X;%d\n" % (cp, ccc[cp]))

    for cp in sorted(decomp):
        if cp in HANGUL:
            continue
        # Store the FULL recursive expansion rather than the one-step
        # mapping, so NFD needs a single lookup and no fixpoint loop.
        out.write("D;%04X;%s\n" % (cp, " ".join("%04X" % c for c in nfd(cp, ccc, decomp))))

        # Composition is NOT the inverse of the expansion above: NFC
        # recomposes one pair at a time, so it needs the ONE-STEP
        # canonical decomposition (U+1E69 is U+1E63 + U+0307, even though
        # it expands to three code points). A singleton never recomposes,
        # and Full_Composition_Exclusion names the pairs that do not
        # either: script exclusions and non-starter decompositions.
        parts = decomp[cp]
        if len(parts) == 2 and cp not in excluded:
            out.write("P;%04X;%04X %04X\n" % (cp, parts[0], parts[1]))


if __name__ == "__main__":
    main()
