#!/usr/bin/env python3
"""Regenerate gcbdata.txt — the UAX #29 grapheme-segmentation source data.

Neither Go's `unicode` package nor CPython's `unicodedata` exposes
Grapheme_Cluster_Break or Extended_Pictographic, and this module has zero
external dependencies (see go.mod), so the data is derived offline and
checked in. `uniseg` (PyPI) is the oracle; it is a REGENERATION-time
dependency only and never a dependency of the module.

Run:  python3 -m pip install uniseg
      python3 cmd/unicodegen/gen_gcbdata.py > cmd/unicodegen/gcbdata.txt

VERSION SKEW, deliberate and worth knowing: uniseg tracks a newer UCD
than the rest of the module's tables (case mapping comes from Go's
`unicode`, normalization from CPython's `unicodedata`). Segmentation is
self-contained -- grapheme boundaries do not consult the case or
normalization tables -- so a newer UCD here is internally consistent
rather than a mismatch. Unlike canonical decompositions, though, the
Grapheme_Cluster_Break assignments are NOT frozen by a stability policy,
so the emitted header records the exact version the data came from.

Only non-Other GCB ranges are emitted: Other is the default and covers
the overwhelming majority of code points, so storing it would multiply
the table for no information.
"""

import sys

from uniseg import unidata_version
from uniseg.emoji import extended_pictographic
from uniseg.graphemecluster import grapheme_cluster_break

MAX_CP = 0x110000


def runs(value_of, skip=None):
    """Coalesce equal adjacent values into (lo, hi, value) runs."""
    out = []
    run = None
    for cp in range(MAX_CP):
        v = value_of(cp)
        if run is not None and run[2] == v and run[1] == cp - 1:
            run = (run[0], cp, v)
            continue
        if run is not None and run[2] != skip:
            out.append(run)
        run = (cp, cp, v)
    if run is not None and run[2] != skip:
        out.append(run)
    return out


def main() -> None:
    out = sys.stdout
    out.write("# Generated by gen_gcbdata.py -- do not edit by hand.\n")
    out.write("# UCD %s (uniseg)\n" % unidata_version)
    out.write("#\n")
    out.write("# G;<lo>;<hi>;<class>   Grapheme_Cluster_Break (non-Other only)\n")
    out.write("# E;<lo>;<hi>           Extended_Pictographic\n")

    for lo, hi, v in runs(lambda cp: grapheme_cluster_break(chr(cp)).name, skip="OTHER"):
        out.write("G;%04X;%04X;%s\n" % (lo, hi, v))

    for lo, hi, _ in runs(lambda cp: bool(extended_pictographic(chr(cp))), skip=False):
        out.write("E;%04X;%04X\n" % (lo, hi))


if __name__ == "__main__":
    main()
