#!/usr/bin/env python3
"""Regenerate gcbdata.txt — the UAX #29 grapheme-segmentation source data.

Neither Go's `unicode` package nor CPython's `unicodedata` exposes
Grapheme_Cluster_Break or Extended_Pictographic, and this module has zero
external dependencies (see go.mod), so the data is derived offline and
checked in. It is read from the Unicode Character Database files of the
release named on the command line — the one Go's `unicode`, and so the
case tables, track (#10472).

Run:  python3 cmd/unicodegen/gen_gcbdata.py 17.0.0 > cmd/unicodegen/gcbdata.txt

The UCD files are fetched from unicode.org; `--ucd DIR` reads
GraphemeBreakProperty.txt and emoji-data.txt from DIR instead.

The Grapheme_Cluster_Break assignments are NOT frozen by a stability
policy, so the emitted header records the exact version the data came
from. Class names are the UCD's property values in upper case.

Only non-Other GCB ranges are emitted: Other is the default and covers
the overwhelming majority of code points, so storing it would multiply
the table for no information.
"""

import os
import sys
import urllib.request

MAX_CP = 0x110000


def ucd_file(version: str, ucd_dir: str, path: str) -> str:
    if ucd_dir:
        with open(os.path.join(ucd_dir, os.path.basename(path)), encoding="utf-8") as f:
            return f.read()
    url = "https://www.unicode.org/Public/%s/ucd/%s" % (version, path)
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def property_values(text: str, wanted=None):
    """Code point -> value for a UCD property file (`cps ; value # ...`),
    optionally keeping only the values in `wanted`."""
    out = {}
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        cps, value = [x.strip() for x in body.split(";")[:2]]
        if wanted is not None and value not in wanted:
            continue
        lo, _, hi = cps.partition("..")
        for cp in range(int(lo, 16), int(hi or lo, 16) + 1):
            out[cp] = value
    return out


def parse_args():
    args = sys.argv[1:]
    if len(args) == 3 and args[1] == "--ucd":
        return args[0], args[2]
    if len(args) != 1:
        sys.exit("usage: %s VERSION [--ucd DIR]" % os.path.basename(sys.argv[0]))
    return args[0], ""


def runs(value_of, skip=None):
    """Coalesce equal adjacent values into (lo, hi, value) runs."""
    out = []
    run = None
    for cp in range(MAX_CP):
        v = value_of(cp)
        if run is not None and run[2] == v and run[1] == cp - 1:
            run = (run[0], cp, v)
            continue
        if run is not None and run[2] != skip:
            out.append(run)
        run = (cp, cp, v)
    if run is not None and run[2] != skip:
        out.append(run)
    return out


def main() -> None:
    version, ucd_dir = parse_args()
    gcb = property_values(ucd_file(version, ucd_dir, "auxiliary/GraphemeBreakProperty.txt"))
    extpict = property_values(ucd_file(version, ucd_dir, "emoji/emoji-data.txt"), {"Extended_Pictographic"})

    out = sys.stdout
    out.write("# Generated by gen_gcbdata.py -- do not edit by hand.\n")
    out.write("# UCD %s (unicode.org)\n" % version)
    out.write("#\n")
    out.write("# G;<lo>;<hi>;<class>   Grapheme_Cluster_Break (non-Other only)\n")
    out.write("# E;<lo>;<hi>           Extended_Pictographic\n")

    for lo, hi, v in runs(lambda cp: gcb.get(cp, "Other").upper(), skip="OTHER"):
        out.write("G;%04X;%04X;%s\n" % (lo, hi, v))

    for lo, hi, _ in runs(lambda cp: cp in extpict, skip=False):
        out.write("E;%04X;%04X\n" % (lo, hi))


if __name__ == "__main__":
    main()
