// Command unicodegen generates internal/stdlib/std/unicode.fern — the
// Unicode simple (1:1) case-mapping tables and the case API built on
// them. The mapping data comes from the Go standard library's
// `unicode` package (unicode.ToUpper / unicode.ToLower), so the table's
// Unicode version tracks the Go toolchain used to run this generator.
//
// Usage:
//
//	go run ./cmd/unicodegen internal/stdlib/std/unicode.fern
//
// Re-run after a Go toolchain upgrade to refresh the tables; the output
// is deterministic (sorted by code point), so an unchanged Unicode
// version reproduces the file byte-for-byte.
package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
)

// emitArray writes a non-public `name(): i32[]` returning the literal
// `vals`, wrapped across lines so no single line grows unreadable.
func emitArray(b *strings.Builder, name string, vals []int) {
	fmt.Fprintf(b, "function %s(): i32[] {\n    return [", name)
	for i, v := range vals {
		if i > 0 {
			b.WriteString(", ")
		}
		if i > 0 && i%16 == 0 {
			b.WriteString("\n        ")
		}
		fmt.Fprintf(b, "%d", v)
	}
	b.WriteString("];\n}\n\n")
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: unicodegen OUTPUT.fern")
		os.Exit(2)
	}
	var upK, upV, loK, loV []int
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if u := unicode.ToUpper(r); u != r {
			upK = append(upK, int(r))
			upV = append(upV, int(u))
		}
		if l := unicode.ToLower(r); l != r {
			loK = append(loK, int(r))
			loV = append(loV, int(l))
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// std/unicode — Unicode simple (1:1) case mapping.
//
// GENERATED by cmd/unicodegen from the Go standard library's unicode
// package (Unicode %s). Do NOT edit by hand — re-run
// `+"`go run ./cmd/unicodegen internal/stdlib/std/unicode.fern`"+` to
// refresh after a Go toolchain upgrade.
//
// This is the Unicode-aware complement to std/string's byte-wise,
// ASCII-only to_upper/to_lower: it maps the full set of code points
// with a simple (single-code-point) case mapping — Latin, Greek,
// Cyrillic, Armenian, fullwidth forms, and the rest — decoding the
// input as UTF-8, mapping each code point, and re-encoding.
//
// Scope + caveats:
//   - SIMPLE mappings only (1:1). The handful of code points whose
//     full mapping expands to multiple code points (e.g. `+"`ß`"+` →
//     `+"`SS`"+`) are left unchanged — matching Go's unicode.ToUpper /
//     ToLower, which are also simple mappings.
//   - Not locale-aware (no Turkish dotless-i tailoring).
//   - The tables are rebuilt per call (the language has no const-array
//     caching yet); to_upper/to_lower build them ONCE and then loop, so
//     a whole-string map is O(table + n), fine at CLI scale.

import "std/utf8" as utf8;

`, unicode.Version)

	emitArray(&b, "_upper_keys", upK)
	emitArray(&b, "_upper_vals", upV)
	emitArray(&b, "_lower_keys", loK)
	emitArray(&b, "_lower_vals", loV)

	b.WriteString(`// _lookup binary-searches the sorted ` + "`keys`" + ` for ` + "`cp`" + ` and returns the
// parallel ` + "`vals`" + ` entry, or ` + "`cp`" + ` unchanged when it has no mapping.
function _lookup(keys: i32[], vals: i32[], cp: i32): i32 {
    var lo: i32 = 0;
    var hi: i32 = keys.len() - 1;
    while (lo <= hi) {
        var mid: i32 = lo + (hi - lo) / 2;
        var k: i32 = keys[mid];
        if (k == cp) { return vals[mid]; }
        if (k < cp) { lo = mid + 1; } else { hi = mid - 1; }
    }
    return cp;
}

// ` + "`to_upper_char(cp)`" + ` — the uppercase of a single code point (its
// simple mapping), or ` + "`cp`" + ` unchanged when it has none.
pub function to_upper_char(cp: i32): i32 {
    return _lookup(_upper_keys(), _upper_vals(), cp);
}

// ` + "`to_lower_char(cp)`" + ` — the lowercase of a single code point.
pub function to_lower_char(cp: i32): i32 {
    return _lookup(_lower_keys(), _lower_vals(), cp);
}

// ` + "`to_upper(s)`" + ` — ` + "`s`" + ` with every code point mapped to its simple
// uppercase. Decodes UTF-8, maps, re-encodes. The tables are built once
// per call, then reused across the string.
pub function to_upper(s: string): string {
    var keys: i32[] = _upper_keys();
    var vals: i32[] = _upper_vals();
    var out: i32[] = [];
    for cp in utf8.codepoints(s) {
        out = out.append(_lookup(keys, vals, cp));
    }
    return utf8.encode_all(out);
}

// ` + "`to_lower(s)`" + ` — ` + "`s`" + ` with every code point mapped to its simple
// lowercase.
pub function to_lower(s: string): string {
    var keys: i32[] = _lower_keys();
    var vals: i32[] = _lower_vals();
    var out: i32[] = [];
    for cp in utf8.codepoints(s) {
        out = out.append(_lookup(keys, vals, cp));
    }
    return utf8.encode_all(out);
}

// ` + "`eq_ignore_case(a, b)`" + ` — case-insensitive equality under simple
// lowercase folding. Folds both operands to lowercase code points and
// compares. (Simple folding, so ` + "`ß`" + ` and ` + "`SS`" + ` are NOT equal.)
pub function eq_ignore_case(a: string, b: string): boolean {
    var keys: i32[] = _lower_keys();
    var vals: i32[] = _lower_vals();
    var ca: i32[] = utf8.codepoints(a);
    var cb: i32[] = utf8.codepoints(b);
    if (ca.len() != cb.len()) { return false; }
    var i: i32 = 0;
    while (i < ca.len()) {
        if (_lookup(keys, vals, ca[i]) != _lookup(keys, vals, cb[i])) { return false; }
        i = i + 1;
    }
    return true;
}
`)

	if err := os.WriteFile(os.Args[1], []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d upper, %d lower mappings, Unicode %s)\n",
		os.Args[1], len(upK), len(loK), unicode.Version)
}
