// Command unicodegen generates internal/stdlib/std/unicode.fern — the
// Unicode simple (1:1) case-mapping tables and the case API built on
// them. The mapping data comes from the Go standard library's
// `unicode` package (unicode.ToUpper / unicode.ToLower), so the table's
// Unicode version tracks the Go toolchain used to run this generator.
//
// Usage:
//
//	go run ./cmd/unicodegen internal/stdlib/std/unicode.fern
//
// Re-run after a Go toolchain upgrade to refresh the tables; the output
// is deterministic (sorted by code point), so an unchanged Unicode
// version reproduces the file byte-for-byte.
package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
)

// emitArray writes a non-public `name(): i32[]` returning the literal
// `vals`, wrapped across lines so no single line grows unreadable.
func emitArray(b *strings.Builder, name string, vals []int) {
	fmt.Fprintf(b, "function %s(): i32[] {\n    return [", name)
	for i, v := range vals {
		if i > 0 {
			b.WriteString(", ")
		}
		if i > 0 && i%16 == 0 {
			b.WriteString("\n        ")
		}
		fmt.Fprintf(b, "%d", v)
	}
	b.WriteString("];\n}\n\n")
}

// coalesce enumerates every code point satisfying pred and merges
// contiguous runs into a flat [lo0, hi0, lo1, hi1, …] list of inclusive
// ranges. Enumerating and coalescing (rather than copying the stdlib
// RangeTable) keeps the output correct regardless of stride and yields
// the minimal set of contiguous ranges for a range binary search.
func coalesce(pred func(rune) bool) []int {
	var out []int
	inRun := false
	var lo rune
	var prev rune
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if pred(r) {
			if !inRun {
				inRun = true
				lo = r
			}
			prev = r
		} else if inRun {
			out = append(out, int(lo), int(prev))
			inRun = false
		}
	}
	if inRun {
		out = append(out, int(lo), int(prev))
	}
	return out
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: unicodegen OUTPUT.fern")
		os.Exit(2)
	}
	var upK, upV, loK, loV []int
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if u := unicode.ToUpper(r); u != r {
			upK = append(upK, int(r))
			upV = append(upV, int(u))
		}
		if l := unicode.ToLower(r); l != r {
			loK = append(loK, int(r))
			loV = append(loV, int(l))
		}
	}
	letterR := coalesce(unicode.IsLetter)
	digitR := coalesce(func(r rune) bool { return unicode.Is(unicode.Nd, r) })
	spaceR := coalesce(unicode.IsSpace)
	upperR := coalesce(unicode.IsUpper)
	lowerR := coalesce(unicode.IsLower)

	var b strings.Builder
	fmt.Fprintf(&b, `// std/unicode — Unicode simple case mapping + character classes.
//
// GENERATED by cmd/unicodegen from the Go standard library's unicode
// package (Unicode %s). Do NOT edit by hand — re-run
// `+"`go run ./cmd/unicodegen internal/stdlib/std/unicode.fern`"+` to
// refresh after a Go toolchain upgrade.
//
// The Unicode-aware complement to std/string's byte-wise, ASCII-only
// helpers. Two families:
//   - Case mapping: to_upper / to_lower / to_upper_char / to_lower_char
//     / eq_ignore_case — full-code-point SIMPLE (1:1) mapping (Latin,
//     Greek, Cyrillic, Armenian, fullwidth, …), decoding UTF-8 via
//     std/utf8 and re-encoding.
//   - Character classes: is_letter / is_digit / is_alnum / is_whitespace
//     / is_upper / is_lower over a code point, via range binary search.
//
// Scope + caveats:
//   - SIMPLE case mappings only (1:1). Multi-code-point expansions
//     (e.g. `+"`ß`"+` → `+"`SS`"+`) are left unchanged — matching Go's
//     unicode.ToUpper / ToLower.
//   - is_digit is the decimal-digit class (Unicode Nd); is_letter is the
//     full Letter category; is_whitespace matches unicode.IsSpace.
//   - Not locale-aware (no Turkish dotless-i tailoring).
//   - The tables are rebuilt per call (the language has no const-array
//     caching yet); to_upper/to_lower build them ONCE and then loop, so
//     a whole-string map is O(table + n), fine at CLI scale.

import "std/utf8" as utf8;

`, unicode.Version)

	emitArray(&b, "_upper_keys", upK)
	emitArray(&b, "_upper_vals", upV)
	emitArray(&b, "_lower_keys", loK)
	emitArray(&b, "_lower_vals", loV)
	emitArray(&b, "_letter_ranges", letterR)
	emitArray(&b, "_digit_ranges", digitR)
	emitArray(&b, "_space_ranges", spaceR)
	emitArray(&b, "_upper_ranges", upperR)
	emitArray(&b, "_lower_ranges", lowerR)

	b.WriteString(`// _lookup binary-searches the sorted ` + "`keys`" + ` for ` + "`cp`" + ` and returns the
// parallel ` + "`vals`" + ` entry, or ` + "`cp`" + ` unchanged when it has no mapping.
function _lookup(keys: i32[], vals: i32[], cp: i32): i32 {
    var lo: i32 = 0;
    var hi: i32 = keys.len() - 1;
    while (lo <= hi) {
        var mid: i32 = lo + (hi - lo) / 2;
        var k: i32 = keys[mid];
        if (k == cp) { return vals[mid]; }
        if (k < cp) { lo = mid + 1; } else { hi = mid - 1; }
    }
    return cp;
}

// ` + "`to_upper_char(cp)`" + ` — the uppercase of a single code point (its
// simple mapping), or ` + "`cp`" + ` unchanged when it has none.
pub function to_upper_char(cp: i32): i32 {
    return _lookup(_upper_keys(), _upper_vals(), cp);
}

// ` + "`to_lower_char(cp)`" + ` — the lowercase of a single code point.
pub function to_lower_char(cp: i32): i32 {
    return _lookup(_lower_keys(), _lower_vals(), cp);
}

// ` + "`to_upper(s)`" + ` — ` + "`s`" + ` with every code point mapped to its simple
// uppercase. Decodes UTF-8, maps, re-encodes. The tables are built once
// per call, then reused across the string.
pub function to_upper(s: string): string {
    var keys: i32[] = _upper_keys();
    var vals: i32[] = _upper_vals();
    var out: i32[] = [];
    for cp in utf8.codepoints(s) {
        out = out.append(_lookup(keys, vals, cp));
    }
    return utf8.encode_all(out);
}

// ` + "`to_lower(s)`" + ` — ` + "`s`" + ` with every code point mapped to its simple
// lowercase.
pub function to_lower(s: string): string {
    var keys: i32[] = _lower_keys();
    var vals: i32[] = _lower_vals();
    var out: i32[] = [];
    for cp in utf8.codepoints(s) {
        out = out.append(_lookup(keys, vals, cp));
    }
    return utf8.encode_all(out);
}

// ` + "`eq_ignore_case(a, b)`" + ` — case-insensitive equality under simple
// lowercase folding. Folds both operands to lowercase code points and
// compares. (Simple folding, so ` + "`ß`" + ` and ` + "`SS`" + ` are NOT equal.)
pub function eq_ignore_case(a: string, b: string): boolean {
    var keys: i32[] = _lower_keys();
    var vals: i32[] = _lower_vals();
    var ca: i32[] = utf8.codepoints(a);
    var cb: i32[] = utf8.codepoints(b);
    if (ca.len() != cb.len()) { return false; }
    var i: i32 = 0;
    while (i < ca.len()) {
        if (_lookup(keys, vals, ca[i]) != _lookup(keys, vals, cb[i])) { return false; }
        i = i + 1;
    }
    return true;
}

// _in_ranges binary-searches the flat inclusive-range list
// [lo0, hi0, lo1, hi1, …] (sorted, non-overlapping) for ` + "`cp`" + `.
function _in_ranges(ranges: i32[], cp: i32): boolean {
    var lo: i32 = 0;
    var hi: i32 = ranges.len() / 2 - 1;
    while (lo <= hi) {
        var mid: i32 = lo + (hi - lo) / 2;
        var rlo: i32 = ranges[mid * 2];
        var rhi: i32 = ranges[mid * 2 + 1];
        if (cp < rlo) { hi = mid - 1; }
        else if (cp > rhi) { lo = mid + 1; }
        else { return true; }
    }
    return false;
}

// ` + "`is_letter(cp)`" + ` — is ` + "`cp`" + ` in the Unicode Letter category (L*)?
pub function is_letter(cp: i32): boolean { return _in_ranges(_letter_ranges(), cp); }

// ` + "`is_digit(cp)`" + ` — is ` + "`cp`" + ` a Unicode decimal digit (category Nd)?
pub function is_digit(cp: i32): boolean { return _in_ranges(_digit_ranges(), cp); }

// ` + "`is_alnum(cp)`" + ` — a letter or a decimal digit.
pub function is_alnum(cp: i32): boolean {
    return _in_ranges(_letter_ranges(), cp) || _in_ranges(_digit_ranges(), cp);
}

// ` + "`is_whitespace(cp)`" + ` — matches Go's unicode.IsSpace (space, tab,
// newline, NBSP, the Unicode space separators, …).
pub function is_whitespace(cp: i32): boolean { return _in_ranges(_space_ranges(), cp); }

// ` + "`is_upper(cp)`" + ` / ` + "`is_lower(cp)`" + ` — Unicode upper/lowercase letters.
pub function is_upper(cp: i32): boolean { return _in_ranges(_upper_ranges(), cp); }
pub function is_lower(cp: i32): boolean { return _in_ranges(_lower_ranges(), cp); }
`)

	if err := os.WriteFile(os.Args[1], []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d upper, %d lower mappings, Unicode %s)\n",
		os.Args[1], len(upK), len(loK), unicode.Version)
}
