package printer

import (
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/jakechampion/lang/internal/ast"
)

// The structural property behind the formatter gates: render an AST so that two
// renderings compare equal exactly when the two trees are the same program.
//
// Byte-parity between formatters and a type-check of the output both miss data
// loss whose output still compiles (#6838) — a dropped `Box[i64]` instantiation
// re-infers as `Box[i32]`. A structural comparison cannot be fooled that way.
// Exported because the self-host formatter's output is checked against the same
// property from internal/e2eselfhost.

// ASTShape renders an AST as a position-free structural string. Every
// ast.Position field is skipped, as are the three whitespace-keyed side tables
// (TypeRefs / Comments / BlankLines) whose line numbers necessarily move when
// the source is re-laid-out.
//
// Generated by reflection rather than a hand-written walk: a switch over node
// kinds only covers the kinds somebody wrote a case for, which over a whole
// corpus is the difference between a gate and a false pass.
func ASTShape(prog *ast.Program) string {
	var b strings.Builder
	shapeValue(&b, reflect.ValueOf(prog))
	return b.String()
}

var positionType = reflect.TypeOf(ast.Position{})

// synthPos matches the `_<line>_<col>` a parser-synthesised name carries —
// `__discard_243_9_1` for a `_` destructure binding, `__forc_12_5` for a C-style
// for's flag. Those are positions spelled inside a string, so they move when the
// source is re-laid-out even though nothing about the program changed.
var synthPos = regexp.MustCompile(`_\d+_\d+`)

func normalizeSynthName(s string) string {
	if !strings.HasPrefix(s, "__") {
		return s
	}
	return synthPos.ReplaceAllString(s, "_#_#")
}

// skippedShapeFields are the Program side tables keyed by source whitespace.
var skippedShapeFields = map[string]bool{"TypeRefs": true, "Comments": true, "BlankLines": true}

func shapeValue(b *strings.Builder, v reflect.Value) {
	switch v.Kind() {
	case reflect.Invalid:
		b.WriteString("nil")
	case reflect.Ptr, reflect.Interface:
		if v.IsNil() {
			b.WriteString("nil")
			return
		}
		shapeValue(b, v.Elem())
	case reflect.Struct:
		if v.Type() == positionType {
			return
		}
		b.WriteString(v.Type().Name())
		b.WriteByte('{')
		for i := 0; i < v.NumField(); i++ {
			f := v.Type().Field(i)
			if f.Type == positionType || skippedShapeFields[f.Name] {
				continue
			}
			b.WriteString(f.Name)
			b.WriteByte(':')
			shapeValue(b, v.Field(i))
			b.WriteByte(' ')
		}
		b.WriteByte('}')
	case reflect.Slice, reflect.Array:
		b.WriteByte('[')
		for i := 0; i < v.Len(); i++ {
			shapeValue(b, v.Index(i))
			b.WriteByte(' ')
		}
		b.WriteByte(']')
	case reflect.Map:
		keys := make([]string, 0, v.Len())
		byKey := map[string]reflect.Value{}
		for _, k := range v.MapKeys() {
			var kb strings.Builder
			shapeValue(&kb, k)
			keys = append(keys, kb.String())
			byKey[kb.String()] = v.MapIndex(k)
		}
		sort.Strings(keys)
		b.WriteString("map[")
		for _, k := range keys {
			b.WriteString(k)
			b.WriteByte(':')
			shapeValue(b, byKey[k])
			b.WriteByte(' ')
		}
		b.WriteByte(']')
	case reflect.String:
		b.WriteString(strconv.Quote(normalizeSynthName(v.String())))
	case reflect.Bool:
		b.WriteString(strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		b.WriteString(strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		b.WriteString(strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		b.WriteString(strconv.FormatFloat(v.Float(), 'g', -1, 64))
	default:
		b.WriteString(v.Kind().String())
	}
}

// FirstShapeDiff reports the first divergence between two shape strings with a
// window of context, since the whole shape of a corpus file is megabytes.
func FirstShapeDiff(want, got string) string {
	i := 0
	for i < len(want) && i < len(got) && want[i] == got[i] {
		i++
	}
	lo := i - 200
	if lo < 0 {
		lo = 0
	}
	clip := func(s string) string {
		hi := i + 200
		if hi > len(s) {
			hi = len(s)
		}
		return s[lo:hi]
	}
	return "--- as written ---\n" + clip(want) + "\n--- after -fmt ---\n" + clip(got)
}
