// The signatures of the callees the IR does not define.
//
// A defined function carries its own parameters and ReturnType, and an
// `@import` extern carries its own signature, so the stack pass reads
// both straight off the program. The rest — the language's builtins, and
// the runtime helpers the lowering pass calls by name — are provided by
// whichever backend is emitting, and their signatures live there. This
// table is the verifier's own record of them.
//
// It is deliberately a SECOND record rather than a shared one: the point
// of a verifier is to disbelieve the compiler, and reading a signature
// out of the same place the emitter reads it would make the two agree by
// construction. What keeps it honest instead is
// TestProvidedSigsAgreeWithWasmRuntime, which compares every entry
// against the wasm backend's helper registry and fails on a
// disagreement.
//
// A name missing from the table is not an error: the calling function is
// skipped and counted, so the worst an omission costs is coverage.
package ir

// providedSig is what a backend-provided callee consumes and produces.
type providedSig struct {
	// argSlots is how many operand-stack slots the call's arguments
	// occupy under the TWO-WORD string ABI, where an argument and a
	// slot are not the same thing. Under the one-word ABI every
	// argument is exactly one slot, so the op's own argument count
	// answers the question and this field is not consulted.
	//
	// -1 means unknown: the callee is generic over its argument types
	// (the Map methods, whose key and value widths come from the
	// instantiation), so nothing static can say how many slots a
	// string key takes. Calls that carry ArgTypes still resolve; the
	// rest skip the function.
	argSlots int
	result   resultShape
}

var providedSigs = map[string]providedSig{
	"__abs_f64":                     {-1, rFloat},
	"__alloc":                       {1, rWord},
	"__alloc_reuse":                 {3, rWord},
	"__alloc_u8":                    {1, rWord},
	"__arr_idx":                     {2, rWord},
	"__arr_idx_1":                   {2, rWord},
	"__arr_idx_1_nc":                {2, rWord},
	"__arr_idx_8":                   {2, rWord},
	"__arr_idx_8_nc":                {2, rWord},
	"__arr_idx_nc":                  {2, rWord},
	"__arr_push_shared_bytes":       {-1, rWord},
	"__arr_push_shared_count":       {-1, rWord},
	"__build_io_error":              {3, rWord},
	"__bytes_to_lang_string":        {2, rString},
	"__c_call0":                     {-1, rWord},
	"__c_call0_f32":                 {-1, rFloat},
	"__c_call0_f64":                 {-1, rFloat},
	"__c_call1":                     {-1, rWord},
	"__c_call1_f32":                 {-1, rFloat},
	"__c_call1_f64":                 {-1, rFloat},
	"__c_call2":                     {-1, rWord},
	"__c_call2_f32":                 {-1, rFloat},
	"__c_call2_f64":                 {-1, rFloat},
	"__c_call3":                     {-1, rWord},
	"__c_call3_f32":                 {-1, rFloat},
	"__c_call3_f64":                 {-1, rFloat},
	"__c_call4":                     {-1, rWord},
	"__c_call4_f32":                 {-1, rFloat},
	"__c_call4_f64":                 {-1, rFloat},
	"__ceil_f64":                    {-1, rFloat},
	"__clz32":                       {-1, rWord},
	"__clz64":                       {-1, rWord},
	"__cos_f64":                     {-1, rFloat},
	"__ctz32":                       {-1, rWord},
	"__ctz64":                       {-1, rWord},
	"__exp_f64":                     {-1, rFloat},
	"__fern_abs_f64":                {1, rFloat},
	"__fern_alloc":                  {1, rWord},
	"__fern_alloc_box":              {1, rWord},
	"__fern_alloc_rc1":              {1, rWord},
	"__fern_arg_at":                 {1, rString},
	"__fern_arg_count":              {0, rWord},
	"__fern_args":                   {0, rWord},
	"__fern_arr_cow_inplace":        {2, rWord},
	"__fern_arr_cow_inplace_ptr":    {2, rWord},
	"__fern_arr_dec":                {2, rWord},
	"__fern_arr_push_grow":          {3, rWord},
	"__fern_arr_push_grow_move_ptr": {3, rWord},
	"__fern_arr_push_grow_move_str": {3, rWord},
	"__fern_arr_push_grow_ptr":      {3, rWord},
	"__fern_arr_push_grow_str":      {3, rWord},
	"__fern_arr_push_shared_bytes":  {0, rWord},
	"__fern_arr_push_shared_count":  {0, rWord},
	"__fern_box_free":               {2, rWord},
	"__fern_ceil_f64":               {1, rFloat},
	"__fern_cell_free":              {1, rWord},
	"__fern_closure_drop":           {1, rWord},
	"__fern_drop_arr_ptr":           {2, rWord},
	"__fern_drop_arr_str":           {2, rWord},
	"__fern_env":                    {2, rWord},
	"__fern_env_at":                 {1, rString},
	"__fern_env_count":              {0, rWord},
	"__fern_eprint":                 {2, rVoid},
	"__fern_exit":                   {1, rVoid},
	"__fern_floor_f64":              {1, rFloat},
	"__fern_heap_bump_bytes":        {0, rWord},
	"__fern_idiv_s32":               {2, rWord},
	"__fern_idiv_s64":               {2, rWord},
	"__fern_idiv_u32":               {2, rWord},
	"__fern_idiv_u64":               {2, rWord},
	"__fern_irem_s32":               {2, rWord},
	"__fern_irem_s64":               {2, rWord},
	"__fern_irem_u32":               {2, rWord},
	"__fern_irem_u64":               {2, rWord},
	"__fern_map_drop":               {1, rWord},
	"__fern_map_hash_seed":          {0, rWord},
	"__fern_memchr":                 {4, rWord},
	"__fern_monotonic_ns":           {0, rWord},
	"__fern_now_ns":                 {0, rWord},
	"__fern_now_unix_ms":            {0, rWord},
	"__fern_open_appender":          {2, rWord},
	"__fern_open_dir":               {2, rWord},
	"__fern_open_reader":            {2, rWord},
	"__fern_open_writer":            {2, rWord},
	"__fern_print":                  {2, rVoid},
	"__fern_putchar":                {1, rVoid},
	"__fern_random_bytes":           {1, rString},
	"__fern_random_i32":             {0, rWord},
	"__fern_rc_dec":                 {1, rWord},
	"__fern_rc_inc":                 {1, rWord},
	"__fern_rc_is_unique":           {1, rWord},
	"__fern_rc_underflow_count":     {0, rWord},
	"__fern_read_byte":              {0, rWord},
	"__fern_read_dir":               {2, rWord},
	"__fern_read_dir_raw":           {1, rWord},
	"__fern_read_file":              {2, rWord},
	"__fern_read_line":              {0, rWord},
	"__fern_reader_close":           {1, rVoid},
	"__fern_reader_close_fd":        {1, rWord},
	"__fern_reader_read_chunk":      {2, rWord},
	"__fern_reader_read_line":       {1, rWord},
	"__fern_reader_read_line_fd":    {1, rWord},
	"__fern_remove_dir_all":         {2, rWord},
	"__fern_remove_file":            {2, rWord},
	"__fern_rmdir_rec":              {2, rWord},
	"__fern_sqrt_f64":               {1, rFloat},
	"__fern_exp_f64":                {1, rFloat},
	"__fern_log_f64":                {1, rFloat},
	"__fern_sin_f64":                {1, rFloat},
	"__fern_cos_f64":                {1, rFloat},
	"__fern_pow_f64":                {2, rFloat},
	"__fern_stat":                   {2, rWord},
	"__fern_stderr":                 {0, rWord},
	"__fern_stdin":                  {0, rWord},
	"__fern_stdout":                 {0, rWord},
	"__fern_str_append":             {4, rString},
	"__fern_str_byte":               {3, rWord},
	"__fern_str_copy":               {2, rString},
	"__fern_str_dec":                {2, rWord},
	"__fern_str_inc":                {2, rString},
	"__fern_str_len":                {2, rWord},
	"__fern_string_from_bytes":      {1, rString},
	"__fern_tcp_accept":             {1, rWord},
	"__fern_tcp_close":              {1, rWord},
	"__fern_tcp_connect":            {2, rWord},
	"__fern_tcp_listen":             {1, rWord},
	"__fern_tcp_pollable":           {1, rWord},
	"__fern_tcp_recv":               {2, rString},
	"__fern_tcp_send":               {3, rWord},
	"__fern_temp_dir":               {2, rWord},
	"__fern_trunc_f64":              {1, rFloat},
	"__fern_udp_send":               {5, rWord},
	"__fern_wasm_block":             {1, rWord},
	"__fern_wasm_poll":              {1, rWord},
	"__fern_wasm_pollable_drop":     {1, rWord},
	"__fern_wasm_timer_pollable":    {1, rWord},
	"__fern_write":                  {2, rVoid},
	"__fern_write_file":             {4, rWord},
	"__fern_writer_close":           {1, rWord},
	"__fern_writer_write":           {3, rWord},
	"__floor_f64":                   {-1, rFloat},
	"__free":                        {2, rVoid},
	"__heap_bump_bytes":             {-1, rWord},
	"__heap_mark":                   {-1, rWord},
	"__heap_release_to":             {-1, rVoid},
	"__http_entry":                  {2, rVoid},
	"__load_i32":                    {1, rWord},
	"__load_i64":                    {1, rWord},
	"__load_ptr":                    {1, rWord},
	"__log_f64":                     {-1, rFloat},
	"__map_hash_seed":               {-1, rWord},
	"__memchr":                      {-1, rWord},
	"__memcpy":                      {3, rVoid},
	"__memset":                      {3, rVoid},
	"__method_Array_len":            {-1, rWord},
	"__method_Array_push":           {-1, rWord},
	"__method_Array_set":            {-1, rWord},
	"__method_Cell_get":             {-1, rWord},
	"__method_Cell_set":             {-1, rVoid},
	"__method_MapIter_advance":      {-1, rVoid},
	"__method_MapIter_has_next":     {-1, rWord},
	"__method_MapIter_key":          {-1, rWord},
	"__method_MapIter_value":        {-1, rWord},
	"__method_Map_clear":            {-1, rWord},
	"__method_Map_delete":           {-1, rWord},
	"__method_Map_get":              {-1, rWord},
	"__method_Map_get_or":           {-1, rWord},
	"__method_Map_has":              {-1, rWord},
	"__method_Map_iter":             {-1, rWord},
	"__method_Map_keys":             {-1, rWord},
	"__method_Map_len":              {-1, rWord},
	"__method_Map_set":              {-1, rWord},
	"__method_Map_values":           {-1, rWord},
	"__method_Reader_close":         {-1, rWord},
	"__method_Reader_read_chunk":    {-1, rWord},
	"__method_Reader_read_line":     {-1, rWord},
	"__method_Writer_close":         {-1, rWord},
	"__method_Writer_write":         {-1, rWord},
	"__method_slice_len":            {-1, rWord},
	"__method_string_as_bytes":      {2, rWord},
	"__method_string_len":           {-1, rWord},
	"__network_handle":              {0, rWord},
	"__popcount32":                  {-1, rWord},
	"__popcount64":                  {-1, rWord},
	"__pow_f64":                     {-1, rFloat},
	"__ptr_width":                   {0, rWord},
	"__rc_dec":                      {-1, rVoid},
	"__rc_get":                      {-1, rWord},
	"__rc_inc":                      {-1, rWord},
	"__rc_underflow_count":          {-1, rWord},
	"__round_f64":                   {-1, rFloat},
	"__sin_f64":                     {-1, rFloat},
	"__slice_idx":                   {2, rWord},
	"__slice_idx_1":                 {2, rWord},
	"__slice_idx_4":                 {2, rWord},
	"__slice_idx_8":                 {2, rWord},
	"__slice_make":                  {2, rWord},
	"__slice_range":                 {3, rWord},
	"__sqrt_f64":                    {-1, rFloat},
	"__store_i32":                   {2, rVoid},
	"__store_i64":                   {2, rVoid},
	"__store_ptr":                   {2, rVoid},
	"__str_concat":                  {4, rString},
	"__str_eq":                      {4, rWord},
	"__str_idx":                     {3, rWord},
	"__str_slice":                   {4, rString},
	"__trunc_f64":                   {-1, rFloat},
	"args":                          {-1, rWord},
	"cell_new":                      {-1, rWord},
	"env":                           {-1, rWord},
	"eprint":                        {-1, rVoid},
	"exit":                          {-1, rVoid},
	"f32_bits":                      {-1, rWord},
	"f32_from_bits":                 {-1, rFloat},
	"f64_bits":                      {-1, rWord},
	"f64_from_bits":                 {-1, rFloat},
	"map_new":                       {-1, rWord},
	"monotonic_ns":                  {-1, rWord},
	"now_ns":                        {-1, rWord},
	"now_unix_ms":                   {-1, rWord},
	"open_appender":                 {-1, rWord},
	"open_reader":                   {-1, rWord},
	"open_writer":                   {-1, rWord},
	"poll":                          {2, rWord},
	"print":                         {-1, rVoid},
	"proc_exec":                     {-1, rWord},
	"proc_fork":                     {-1, rWord},
	"proc_waitpid":                  {-1, rWord},
	"putchar":                       {-1, rVoid},
	"random_bytes":                  {-1, rString},
	"random_i32":                    {-1, rWord},
	"read_dir":                      {-1, rWord},
	"read_file":                     {-1, rWord},
	"read_line":                     {-1, rWord},
	"remove_dir_all":                {-1, rWord},
	"remove_file":                   {-1, rWord},
	"sleep_ms":                      {-1, rVoid},
	"stat":                          {-1, rWord},
	"stderr":                        {-1, rWord},
	"stdin":                         {-1, rWord},
	"stdout":                        {-1, rWord},
	"strbuf_append":                 {-1, rVoid},
	"strbuf_reset":                  {-1, rVoid},
	"strbuf_take":                   {-1, rString},
	"string_from_bytes_unchecked":   {-1, rString},
	"subprocess":                    {-1, rWord},
	"tcp_accept":                    {-1, rWord},
	"tcp_close":                     {-1, rWord},
	"tcp_connect":                   {-1, rWord},
	"tcp_listen":                    {-1, rWord},
	"tcp_pollable":                  {-1, rWord},
	"tcp_recv":                      {-1, rString},
	"tcp_send":                      {-1, rWord},
	"temp_dir":                      {-1, rWord},
	"timer_fd":                      {-1, rWord},
	"udp_send":                      {-1, rWord},
	"wasm_block":                    {-1, rWord},
	"wasm_poll":                     {-1, rWord},
	"wasm_pollable_drop":            {-1, rWord},
	"wasm_timer_pollable":           {-1, rWord},
	"write":                         {-1, rVoid},
	"write_file":                    {-1, rWord},
}

// ProvidedCallee reports the verifier's record of a backend-provided
// callee: how many operand-stack slots its arguments occupy under the
// two-word string ABI (-1 when that depends on the instantiation and no
// static answer exists), and how many its result occupies. ok is false
// for a name the table does not know.
//
// Exported so a backend that owns the real signature can be asked
// whether it agrees — see TestProvidedSigsAgreeWithWasmRuntime. Nothing
// in the compiler consults it.
func ProvidedCallee(name string, twoWordStr bool) (argSlots, resultSlots int, ok bool) {
	sig, ok := providedSigs[name]
	if !ok {
		return 0, 0, false
	}
	return sig.argSlots, len(sig.result.slots(twoWordStr)), true
}
