package sourcelint

import (
	"strings"
	"testing"
)

// pullfrog.yml is generated by the Pullfrog app and carries two edits of this
// repository's own: the two-slot review queue (its concurrency block) and a
// gate step that ends a review nobody will read before it holds a runner for
// 20-50 minutes. The gate is an ordering inside the job, so a regenerated file
// loses it silently: the reviews would still post, hours late, on merged PRs.
func TestPullfrogSkipsReviewsNobodyReads(t *testing.T) {
	src := workflowSource(t, "pullfrog.yml")

	gate := strings.Index(src, "id: gate")
	checkout := strings.Index(src, "uses: actions/checkout@")
	agent := strings.Index(src, "uses: pullfrog/pullfrog@")
	switch {
	case gate < 0:
		t.Fatal("pullfrog.yml has no `gate` step: every queued review runs, merged PR or not")
	case checkout < 0 || agent < 0:
		t.Fatal("pullfrog.yml no longer checks out and runs the agent — did the generated shape change?")
	case gate > checkout || gate > agent:
		t.Error("the gate step must come before the checkout and the agent, or it decides nothing")
	}
	if n := strings.Count(src, "if: steps.gate.outputs.skip != 'true'"); n != 2 {
		t.Errorf("the checkout and the agent step must each carry `if: steps.gate.outputs.skip != 'true'`; %d step(s) do", n)
	}

	for _, want := range []struct{ needle, why string }{
		{`pr.state === "closed"`, "a review of a merged or closed pull request is read by nobody"},
		{`workflow_id: "pullfrog.yml"`, "a newer queued review of the same pull request supersedes this one"},
		{`Date.parse(run.created_at) <= Date.parse(me.created_at)`, "only a NEWER run supersedes, or two reviews of one PR skip each other"},
		{`replace(/#\d+/, "#N")`, "only a run of the same kind supersedes, so a whole-PR review is never dropped for an incremental one"},
		{"actions: read", "the gate lists this workflow's other runs"},
		{"pull-requests: read", "the gate reads the pull request's state"},
	} {
		if !strings.Contains(src, want.needle) {
			t.Errorf("pullfrog.yml no longer contains %q — %s", want.needle, want.why)
		}
	}
}
