package x86_64

// Keep the requested capacity when a read is short, and expose only the bytes
// actually read. Both copy-on-write and reclamation use the array header.
func (g *generator) emitReaderBytesRuntime() {
	g.line(".globl __fern_reader_read_chunk_bytes")
	g.line(".type __fern_reader_read_chunk_bytes, @function")
	g.label("__fern_reader_read_chunk_bytes")
	g.emit("push rbp")
	g.emit("mov rbp, rsp")
	g.emit("push rbx")
	g.emit("push r12")
	g.emit("push r13")
	g.emit("push r14")
	g.emit("mov ebx, [rdi]")
	g.emit("mov r12d, esi")
	g.emit("test r12d, r12d")
	g.emit("js .Lrrbytes_invalid")
	g.emit("mov edi, r12d")
	g.emit("call __alloc_u8")
	g.emit("mov r13, rax")
	g.emit("mov edi, ebx")
	g.emit("mov rsi, r13")
	g.emit("mov edx, r12d")
	g.emit("xor eax, eax")
	g.emitSyscallPreloaded(sysRead)
	g.emit("test rax, rax")
	g.emit("js .Lrrbytes_error")
	g.emit("test r12d, r12d")
	g.emit("jz .Lrrbytes_ok")
	g.emit("mov [r13 - 4], eax")
	g.label(".Lrrbytes_ok")
	g.emit("mov edi, 16")
	g.emit("call __fern_alloc_rc1")
	g.emit("mov dword ptr [rax], 0")
	g.emit("mov [rax + 8], r13")
	g.emit("jmp .Lrrbytes_return")
	g.label(".Lrrbytes_error")
	g.emit("neg rax")
	g.emit("mov rbx, rax")
	g.emit("test r12d, r12d")
	g.emit("jz .Lrrbytes_box_error")
	g.emit("lea rdi, [r13 - 16]")
	g.emit("lea rsi, [r12 + 16]")
	g.emit("call __fern_free")
	g.emit("jmp .Lrrbytes_box_error")
	g.label(".Lrrbytes_invalid")
	g.emit("mov ebx, 22")
	g.label(".Lrrbytes_box_error")
	g.emit("mov edi, ebx")
	g.emit("lea rsi, [rip + .LStr_ioerr_empty]")
	g.emit("call __fern_io_error")
	g.emit("mov rbx, rax")
	g.emit("mov edi, 16")
	g.emit("call __fern_alloc_rc1")
	g.emit("mov dword ptr [rax], 1")
	g.emit("mov [rax + 8], rbx")
	g.label(".Lrrbytes_return")
	g.emit("pop r14")
	g.emit("pop r13")
	g.emit("pop r12")
	g.emit("pop rbx")
	g.emit("pop rbp")
	g.emit("ret")
	g.line(".size __fern_reader_read_chunk_bytes, .-__fern_reader_read_chunk_bytes")
}
