package x86_64

// Copy inline or addressable string bytes directly into an owned byte array.
func (g *generator) emitStringBytesRuntime() {
	g.line(".globl __fern_string_bytes_copy")
	g.line(".type __fern_string_bytes_copy, @function")
	g.label("__fern_string_bytes_copy")
	g.emit("push rbp")
	g.emit("mov rbp, rsp")
	g.emit("sub rsp, 32")
	g.emit("mov [rbp - 8], rdi")
	g.emit("test dil, 1")
	g.emit("jnz .Lbytes_copy_inline")
	g.emit("mov rsi, rdi")
	g.emit("mov ecx, [rdi - 4]")
	g.emit("jmp .Lbytes_copy_alloc")
	g.label(".Lbytes_copy_inline")
	g.emit("mov rcx, rdi")
	g.emit("shr rcx, 1")
	g.emit("and ecx, 7")
	g.emit("lea rsi, [rbp - 7]")
	g.label(".Lbytes_copy_alloc")
	g.emit("mov [rbp - 16], rsi")
	g.emit("mov [rbp - 24], rcx")
	g.emit("mov edi, ecx")
	g.emit("call __alloc_u8")
	g.emit("mov rdi, rax")
	g.emit("mov rsi, [rbp - 16]")
	g.emit("mov rcx, [rbp - 24]")
	g.emit("cld")
	g.emit("rep movsb")
	g.emit("add rsp, 32")
	g.emit("pop rbp")
	g.emit("ret")
	g.line(".size __fern_string_bytes_copy, .-__fern_string_bytes_copy")
}
