//go:build ignore

// Generate the documentation renderer's strconv.IsPrint range table.
// Run with the repository's pinned Go toolchain. Output is Fern source.
package main

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"
)

func main() {
	var ranges strings.Builder
	for r := rune(128); r <= unicode.MaxRune; {
		if !strconv.IsPrint(r) {
			r++
			continue
		}
		start := r
		for r < unicode.MaxRune && strconv.IsPrint(r+1) {
			r++
		}
		fmt.Fprintf(&ranges, "%06x%06x", start, r)
		r++
	}
	fmt.Println("// Generated by scripts/gen-doc-printable.go; do not edit.")
	fmt.Printf("// Unicode %s, matching the pinned Go reference's strconv.IsPrint.\n", unicode.Version)
	fmt.Println("// Each pair is an inclusive range of six-digit hexadecimal scalars.")
	fmt.Printf("pub function printable_ranges(): string {\n  return %q;\n}\n", ranges.String())
}
