#!/usr/bin/env python3
"""Regenerate the data behind the table-driven f64 log in std/float.

    uv run --no-project scripts/gen_log_table.py
    uv run --no-project scripts/gen_log_table.py --check

The algorithm is the one glibc (since 2.29) and ARM's optimized-routines use
when there is no fused multiply-add, which is what keeps every backend
bit-identical: wasm has no scalar fma, and the interpreter is the oracle the
compiled results are compared against.

    x = 2^k z, z in [0x1.6p-1, 0x1.6p0), split into N subintervals by the top
    log2(N) bits of the integer (bits(x) - OFF)
    log(x) = k ln2 + log(c) + log1p(r),  r = (z - c) * invc

c is the midpoint of z's subinterval, so it is itself a double that z - c
cancels against exactly, and invc = RN(1/c). log(c) is stored as a head on the
2^-43 grid plus a tail, which makes k*ln2hi + logc_hi exact for every k a
double can produce. log1p(r) is a degree-6 polynomial with |r| < 2^-8.

Near 1 the k ln2 + log(c) terms are zero or cancel and the result is as small
as the polynomial's absolute error, so x in [1 - 2^-4, 1 + 0x1.09p-4] takes a
separate path: log1p(x - 1) directly, with a degree-12 polynomial and r - r^2/2
carried in two parts.

Both polynomials are minimax, fitted here with the Remez exchange algorithm in
60-digit decimal arithmetic: the main one on absolute error (the result there
is at least 2^-4 in magnitude, so absolute error is what the last place sees),
the near-1 one on error relative to log1p(r). The table is computed at the
same precision. Nothing here is transcribed.

The output is the region between the generator's markers in
internal/stdlib/std/float.fern, whose _fd_log is the one log every target
compiles and the interpreter runs.
"""
import argparse
import decimal
import math
import os
import sys
from decimal import Decimal as D

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
TARGET = os.path.join(ROOT, "internal", "stdlib", "std", "float.fern")
BEGIN = "// >>> generated by scripts/gen_log_table.py — do not edit by hand"
END = "// <<< generated"

decimal.getcontext().prec = 60

N = 128
TABLE_BITS = 7
OFF = 0x3FE6000000000000
SUB = 1 << (52 - TABLE_BITS)  # one subinterval, in units of the integer bits
NEAR1_LO = 0x3FEE000000000000  # 1 - 2^-4
NEAR1_HI = 0x3FF1090000000000  # 1 + 0x1.09p-4
LOGC_GRID = 43  # logc_hi is a multiple of 2^-43

MAIN_DEGREE = 3  # coefficients of r^3 .. r^6
NEAR1_DEGREE = 9  # coefficients of r^3 .. r^12


def f64(bits):
    return float.fromhex("0x1.%013xp%d" % (bits & ((1 << 52) - 1), ((bits >> 52) & 0x7FF) - 1023))


def dec(x):
    """The double x, exactly."""
    n, d = x.as_integer_ratio()
    return D(n) / D(d)


def tail(r):
    """(log1p(r) - r + r^2/2) / r^3, the function both polynomials fit, by
    its series; |r| < 0.07 makes each term at least 14 times the next."""
    total = D(0)
    p = D(1)
    n = 3
    eps = D(10) ** -(decimal.getcontext().prec + 2)
    while True:
        t = p / n
        total += t if n % 2 else -t
        if abs(t) < eps:
            return total
        p *= r
        n += 1


def log1p(r):
    return r - r * r / 2 + r * r * r * tail(r)


def poly(cs, r):
    acc = D(0)
    for c in reversed(cs):
        acc = acc * r + c
    return acc


def solve(m, v):
    """Gaussian elimination with partial pivoting, in decimal."""
    n = len(v)
    a = [row[:] + [v[i]] for i, row in enumerate(m)]
    for col in range(n):
        piv = max(range(col, n), key=lambda i: abs(a[i][col]))
        a[col], a[piv] = a[piv], a[col]
        for i in range(col + 1, n):
            f = a[i][col] / a[col][col]
            for j in range(col, n + 1):
                a[i][j] -= f * a[col][j]
    x = [D(0)] * n
    for i in reversed(range(n)):
        x[i] = (a[i][n] - sum(a[i][j] * x[j] for j in range(i + 1, n))) / a[i][i]
    return x


def remez(lo, hi, degree, weight, grid=4000, rounds=30):
    """Minimise max |weight(r) * (tail(r) - P(r))| over [lo, hi] for P of the
    given degree. Returns (coefficients, levelled error)."""
    lo, hi = D(lo), D(hi)
    mid, half = (lo + hi) / 2, (hi - lo) / 2
    pi = D("3.14159265358979323846264338327950288419716939937510582097494")

    def cheb(j, n):
        return mid + half * D(math.cos(float(pi) * j / n))

    m = degree + 2
    ref = sorted(cheb(j, m - 1) for j in range(m))
    xs = sorted(cheb(j, grid) for j in range(grid + 1))
    fx = [tail(x) for x in xs]
    wx = [weight(x) for x in xs]
    for _ in range(rounds):
        rows = []
        rhs = []
        for j, x in enumerate(ref):
            rows.append([x**p for p in range(degree + 1)] + [D((-1) ** j) / weight(x)])
            rhs.append(tail(x))
        sol = solve(rows, rhs)
        cs, lev = sol[:-1], abs(sol[-1])
        err = [w * (f - poly(cs, x)) for x, f, w in zip(xs, fx, wx)]
        # One extremum per run of equal sign, then keep m alternating ones
        # around the largest.
        runs = []
        for x, e in zip(xs, err):
            if runs and (e >= 0) == (runs[-1][1] >= 0):
                if abs(e) > abs(runs[-1][1]):
                    runs[-1] = (x, e)
            else:
                runs.append((x, e))
        while len(runs) > m:
            if abs(runs[0][1]) < abs(runs[-1][1]):
                runs.pop(0)
            else:
                runs.pop()
        if len(runs) < m:
            raise SystemExit("remez: lost alternation (%d of %d extrema)" % (len(runs), m))
        peak = max(abs(e) for _, e in runs)
        ref = [x for x, _ in runs]
        if peak - lev < lev * D("1e-9"):
            return cs, peak
    raise SystemExit("remez: did not level within %d rounds" % rounds)


def round_coeffs(cs):
    return [float(c) for c in cs]


def max_err(cs, lo, hi, weight, samples=20000):
    lo, hi = D(lo), D(hi)
    worst = D(0)
    for j in range(samples + 1):
        x = lo + (hi - lo) * j / samples
        if x == 0:
            continue
        e = abs(weight(x) * (tail(x) - poly([dec(c) for c in cs], x)))
        worst = max(worst, e)
    return worst


def build_table():
    rows = []
    rmax = D(0)
    for i in range(N):
        c = f64(OFF + i * SUB + SUB // 2)
        cd = dec(c)
        zlo, zhi = dec(f64(OFF + i * SUB)), dec(f64(OFF + (i + 1) * SUB))
        rmax = max(rmax, abs((zlo - cd) / cd), abs((zhi - cd) / cd))
        invc = 1.0 / c  # IEEE division: RN(1/c)
        logc = cd.ln()
        hi_units = (logc * (D(2) ** LOGC_GRID)).to_integral_value(rounding=decimal.ROUND_HALF_EVEN)
        logc_hi = float(hi_units) / 2.0**LOGC_GRID  # exact: |hi_units| < 2^42
        assert dec(logc_hi) * D(2) ** LOGC_GRID == hi_units
        logc_lo = float(logc - dec(logc_hi))  # float(Decimal) rounds correctly
        rows.append((invc, logc_hi, logc_lo))
    return rows, rmax


def generate():
    rows, rmax = build_table()
    # r is computed with two roundings, so its reach exceeds the exact bound
    # by a relative 2^-52; fit a little wider than that.
    rfit = float(rmax * D("1.0001"))

    main_w = lambda r: abs(r) ** 3
    main_cs, main_lev = remez(-rfit, rfit, MAIN_DEGREE, main_w)
    main = round_coeffs(main_cs)
    main_err = max_err(main, -rfit, rfit, main_w)

    lo1, hi1 = f64(NEAR1_LO) - 1.0, f64(NEAR1_HI) - 1.0  # both exact
    near_w = lambda r: abs(r**3 / log1p(r))
    near_cs, near_lev = remez(lo1, hi1, NEAR1_DEGREE, near_w)
    near = round_coeffs(near_cs)
    near_err = max_err(near, lo1, hi1, near_w)

    return {
        "rows": rows,
        "rmax": rmax,
        "main": main,
        "main_err": main_err,
        "near": near,
        "near_err": near_err,
    }


def log2_of(e):
    return float(e.ln() / D(2).ln()) if e > 0 else float("-inf")


def literal(x):
    """x as a Fern float literal: Python's shortest round-trip repr, which Fern
    reads back exactly, given a decimal point where repr leaves it out."""
    r = repr(x)
    if "." not in r:
        r = r.replace("e", ".0e") if "e" in r else r + ".0"
    return r


def render_fern_region(g, indent):
    """The log kernel's data as std/float spells it: each table a zero-argument
    function returning an array literal, which the compiler makes one static
    array wherever it is called."""
    out = [indent + BEGIN]
    w = lambda ln="": out.append((indent + ln).rstrip())

    def array_fn(name, vals, per_line):
        w("function %s(): f64[] {" % name)
        w("  return [")
        for k in range(0, len(vals), per_line):
            w("    " + " ".join(literal(v) + "," for v in vals[k : k + per_line]))
        w("  ];")
        w("}")

    w("// _log_poly is the main path's coefficients of r^3 .. r^%d, minimax on absolute" % (MAIN_DEGREE + 3))
    w("// error over |r| <= %.6g. Max error after rounding: 2^%.1f." % (float(g["rmax"]), log2_of(g["main_err"])))
    array_fn("_log_poly", g["main"], 4)
    w()
    w("// _log_near1_poly is the near-1 path's coefficients of r^3 .. r^%d, minimax on" % (NEAR1_DEGREE + 3))
    w("// error relative to log1p(r). Max relative error after rounding: 2^%.1f." % log2_of(g["near_err"]))
    array_fn("_log_near1_poly", g["near"], 4)
    w()
    w("// _log_invc, _log_logc_hi and _log_logc_lo are the %d rows of the table, each" % N)
    w("// a column: row i covers the z whose bits(z) - bits(0x1.6p-1) has i in its")
    w("// top %d mantissa bits, c is the midpoint of the row's subinterval, invc =" % TABLE_BITS)
    w("// RN(1/c), and logc_hi + logc_lo is log(c) with logc_hi on the 2^-%d grid." % LOGC_GRID)
    for col, name in enumerate(["_log_invc", "_log_logc_hi", "_log_logc_lo"]):
        array_fn(name, [row[col] for row in g["rows"]], 4)
        w()
    out.append(indent + END)
    return "\n".join(out)


def regenerated(text, render):
    """text with its one generated region replaced by render(indent), or None
    when the markers are missing, repeated or out of order."""
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        return None
    start, end = text.index(BEGIN), text.index(END)
    if end < start:
        return None
    line_start = text.rfind("\n", 0, start) + 1
    indent = text[line_start:start]
    if indent.strip():
        return None
    return text[:line_start] + render(indent) + text[end + len(END) :]


def check_or_write(path, want, check):
    have = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            have = f.read()
    if have == want:
        return True
    if check:
        print("%s is out of date; run scripts/gen_log_table.py" % os.path.relpath(path, ROOT), file=sys.stderr)
        return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(want)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the output is stale instead of writing it")
    args = ap.parse_args()
    g = generate()
    with open(TARGET, encoding="utf-8") as f:
        text = f.read()
    want = regenerated(text, lambda ind: render_fern_region(g, ind))
    if want is None:
        print("%s: expected exactly one %r ... %r region" % (os.path.relpath(TARGET, ROOT), BEGIN, END), file=sys.stderr)
        return 1
    return 0 if check_or_write(TARGET, want, args.check) else 1


if __name__ == "__main__":
    sys.exit(main())
