package arm64ssa

func emitReaderBytesHelper(w func(string, ...any)) {
	w("%s:", fnLabel("__method_Reader_read_chunk_bytes"))
	w("\tstp x29, x30, [sp, #-48]!")
	w("\tmov x29, sp")
	w("\tstp x19, x20, [sp, #16]")
	w("\tstp x21, x22, [sp, #32]")
	w("\tldr w19, [x0, #8]")
	w("\tmov w20, w1")
	w("\ttbnz w20, #31, .Lssa_rrbytes_invalid")
	w("\tmov w0, w20")
	w("\tbl %s", fnLabel("__alloc_u8"))
	w("\tmov x21, x0")
	w("\tmov w0, w19")
	w("\tmov x1, x21")
	w("\tmov w2, w20")
	w("\tmov x8, #63")
	w("\tsvc #0")
	w("\ttbnz x0, #63, .Lssa_rrbytes_error")
	w("\tstur w0, [x21, #-4]")
	emitOptionBox(w, 0, "x21")
	w("\tb .Lssa_rrbytes_return")
	w(".Lssa_rrbytes_error:")
	w("\tneg x19, x0")
	w("\tsub x0, x21, #16")
	w("\tadd x1, x20, #16")
	w("\tbl %s", fnLabel("__free"))
	w("\tb .Lssa_rrbytes_box_error")
	w(".Lssa_rrbytes_invalid:")
	w("\tmov x19, #22")
	w(".Lssa_rrbytes_box_error:")
	emitEmptyString(w, "x1")
	w("\tmov x0, x19")
	w("\tbl %s", fnLabel("__fern_io_error"))
	w("\tmov x19, x0")
	emitOptionBox(w, 1, "x19")
	w(".Lssa_rrbytes_return:")
	w("\tldp x21, x22, [sp, #32]")
	w("\tldp x19, x20, [sp, #16]")
	w("\tldp x29, x30, [sp], #48")
	w("\tret")
}
