// Code generated by tools/gen_log_table.py; DO NOT EDIT.

package fdlibm

// The table-driven log behind __fern_log_f64, glibc's and ARM optimized-routines'
// algorithm in its no-fma form, so that every backend computes it with the same
// separately rounded operations. For x outside the near-1 band:
//
//     tmp = bits(x) - LogOff;  i = tmp>>45 & 127;  k = int64(tmp) >> 52
//     z = asdouble(bits(x) - tmp&(0xfff<<52))       z in [0x1.6p-1, 0x1.6p0)
//     c = asdouble(bits(z) &^ (1<<45-1) | 1<<44)    midpoint of z's subinterval
//     r = (z - c) * invc                            z - c is exact
//     w = k*ln2hi + logc_hi                         exact: both on the 2^-43 grid
//     hi = w + r;  lo = ((w - hi) + r) + (k*ln2lo + logc_lo)
//     r2 = r*r;  p = (A1 + r*A2) + r2*(A3 + r*A4)
//     log x = ((lo - r2*0.5) + (r*r2)*p) + hi
//
// For x in [1 - 2^-4, 1 + 0x1.09p-4], with B1..B10 = LogNear1Poly:
//
//     r = x - 1;  r2 = r*r;  r3 = r*r2
//     p = ((B7 + r*B8) + r2*B9) + r3*B10
//     p = ((B4 + r*B5) + r2*B6) + r3*p
//     p = ((B1 + r*B2) + r2*B3) + r3*p
//     y = r3*p
//     w = r*2^27;  rhi = (r + w) - w;  rlo = r - rhi     rhi*rhi is exact
//     h = (rhi*rhi)*0.5;  hi = r - h;  lo = (r - hi) - h
//     lo = lo - (rlo*0.5)*(rhi + r)
//     log x = (y + lo) + hi
//
// A subnormal x is scaled by 2^52 first and 52 taken off its exponent field;
// NaN returns itself, +Inf itself, ±0 -Inf, and anything negative NaN. Measured
// against a 256-bit reference over 10^6 samples the worst error is 0.53 ulp.

// LogTableBits is log2 of the number of log table rows; row i covers the
// z whose bits(z) - LogOff has i in its top LogTableBits mantissa bits.
const LogTableBits = 7

// LogOff is bits(0x1.6p-1): z = x / 2^k lands in [LogOff, 2*LogOff).
const LogOff = 0x3fe6000000000000

// LogNear1Lo and LogNear1Hi bound the near-1 path, [1 - 2^-4, 1 + 0x1.09p-4],
// as bit patterns: x takes it when bits(x) - LogNear1Lo < LogNear1Hi - LogNear1Lo
// unsigned.
const (
	LogNear1Lo = 0x3fee000000000000
	LogNear1Hi = 0x3ff1090000000000
)

// LogPoly are the main path's coefficients of r^3 .. r^6, minimax on absolute
// error over |r| <= 0.00389105. Max error after rounding: 2^-64.1.
var LogPoly = [...]float64{
	0x1.555555550b390p-2,  // 0.3333333333164825
	-0x1.ffffffff3b2fap-3, // -0.24999999997762484
	0x1.999b49b5613e9p-3,  // 0.20000321945931823
	-0x1.555719b6c2691p-3, // -0.16667003716456866
}

// LogNear1Poly are the near-1 path's coefficients of r^3 .. r^12, minimax on
// error relative to log1p(r). Max relative error after rounding: 2^-61.9.
var LogNear1Poly = [...]float64{
	0x1.5555555555577p-2,  // 0.3333333333333352
	-0x1.ffffffffffdb3p-3, // -0.24999999999998365
	0x1.999999995deb1p-3,  // 0.19999999999321497
	-0x1.555555567c82ep-3, // -0.1666666667002245
	0x1.24924a342f5ddp-3,  // 0.14285715076213892
	-0x1.fffffa24b4239p-4, // -0.12499997818236687
	0x1.c7184291e7cf5p-4,  // 0.11110712055095802
	-0x1.999ece3a42714p-4, // -0.10000496442458157
	0x1.781836340ad22p-4,  // 0.09181996510658455
	-0x1.55196561b3f0ep-4, // -0.08327617265899454
}

// LogTable rows are {invc, logc_hi, logc_lo}: c is the
// midpoint of the row's subinterval, invc = RN(1/c), and logc_hi + logc_lo
// is log(c) with logc_hi on the 2^-43 grid.
var LogTable = [128][3]float64{
	{0x1.734f0c541fe8dp+0, -0x1.7cc7f7db46800p-2, -0x1.06cf78ffb8648p-45},
	{0x1.713786d9c7c09p+0, -0x1.76feecb947000p-2, -0x1.74bb9c9852c57p-46},
	{0x1.6f26016f26017p+0, -0x1.713e33a46a000p-2, -0x1.7b9b2617e9472p-46},
	{0x1.6d1a62681c861p+0, -0x1.6b85b4cffa000p-2, -0x1.fe6750d372503p-45},
	{0x1.6b1490aa31a3dp+0, -0x1.65d558d4ce000p-2, -0x1.544fd2dc5bdc0p-51},
	{0x1.691473a88d0c0p+0, -0x1.602d08af09000p-2, -0x1.ebe9176df3f65p-46},
	{0x1.6719f3601671ap+0, -0x1.5a8cadbbee000p-2, 0x1.7c79b0af7ecf8p-48},
	{0x1.6524f853b4aa3p+0, -0x1.54f431b7be000p-2, -0x1.a8954c0910952p-46},
	{0x1.63356b88ac0dep+0, -0x1.4f637ebba9800p-2, -0x1.f539a676da36ep-51},
	{0x1.614b36831ae94p+0, -0x1.49da7f3bcc800p-2, 0x1.f099964a168cdp-45},
	{0x1.5f66434292dfcp+0, -0x1.44591e053a000p-2, 0x1.6e95892923d88p-47},
	{0x1.5d867c3ece2a5p+0, -0x1.3edf463c16800p-2, -0x1.f307ad01a7821p-49},
	{0x1.5babcc647fa91p+0, -0x1.396ce359bc000p-2, 0x1.5839c5663663dp-47},
	{0x1.59d61f123ccaap+0, -0x1.3401e12aec800p-2, -0x1.d07195523adc6p-45},
	{0x1.5805601580560p+0, -0x1.2e9e2bce12000p-2, -0x1.4300c128d1dc2p-45},
	{0x1.56397ba7c52e2p+0, -0x1.2941afb186800p-2, -0x1.bde7a919e3aebp-45},
	{0x1.54725e6bb82fep+0, -0x1.23ec5991eb800p-2, -0x1.248376eba35bcp-45},
	{0x1.52aff56a8054bp+0, -0x1.1e9e167889800p-2, -0x1.f4544b0dd2688p-46},
	{0x1.50f22e111c4c5p+0, -0x1.1956d3b9bc000p-2, -0x1.7d2f73ad1aa14p-45},
	{0x1.4f38f62dd4c9bp+0, -0x1.14167ef367800p-2, 0x1.f3f87db2550acp-48},
	{0x1.4d843bedc2c4cp+0, -0x1.0edd060b78000p-2, -0x1.019b52d8435f5p-47},
	{0x1.4bd3edda68fe1p+0, -0x1.09aa572e6c800p-2, 0x1.2bd787a32f2f6p-46},
	{0x1.4a27fad76014ap+0, -0x1.047e60cde8000p-2, -0x1.dbdf10d397f3cp-45},
	{0x1.4880522014880p+0, -0x1.feb2233ea0000p-3, -0x1.f3418de00938bp-45},
	{0x1.46dce34596066p+0, -0x1.f474b134df000p-3, -0x1.146d838821289p-46},
	{0x1.453d9e2c776cap+0, -0x1.ea4449f04b000p-3, 0x1.42dd33919ab94p-45},
	{0x1.43a2730abee4dp+0, -0x1.e020cc6236000p-3, 0x1.52b00adb91424p-45},
	{0x1.420b5265e5951p+0, -0x1.d60a17f903000p-3, -0x1.4523f207be58ep-45},
	{0x1.40782d10e6566p+0, -0x1.cc000c9db4000p-3, 0x1.d6d585d57aff9p-46},
	{0x1.3ee8f42a5af07p+0, -0x1.c2028ab180000p-3, 0x1.92e0ee55c7ac6p-45},
	{0x1.3d5d991aa75c6p+0, -0x1.b811730b82000p-3, -0x1.e90683b9cd768p-46},
	{0x1.3bd60d9232955p+0, -0x1.ae2ca6f673000p-3, 0x1.0ae54a356155fp-45},
	{0x1.3a524387ac822p+0, -0x1.a454082e6b000p-3, 0x1.3eb106fc11d1ep-45},
	{0x1.38d22d366088ep+0, -0x1.9a8778debb000p-3, 0x1.71e0b820278e0p-45},
	{0x1.3755bd1c945eep+0, -0x1.90c6db9fcc000p-3, 0x1.935f57718d7cap-46},
	{0x1.35dce5f9f2af8p+0, -0x1.871213750f000p-3, 0x1.9ae297a0ca116p-45},
	{0x1.34679ace01346p+0, -0x1.7d6903caf6000p-3, 0x1.4c06b17c301d7p-45},
	{0x1.32f5ced6a1dfap+0, -0x1.73cb9074fd000p-3, -0x1.4cab797ffd2ccp-47},
	{0x1.3187758e9ebb6p+0, -0x1.6a399dabbd000p-3, -0x1.c1b2c6657a967p-46},
	{0x1.301c82ac40260p+0, -0x1.60b3100b09000p-3, -0x1.1d7526cee0fd8p-45},
	{0x1.2eb4ea1fed14bp+0, -0x1.5737cc9019000p-3, 0x1.91561651de028p-46},
	{0x1.2d50a012d50a0p+0, -0x1.4dc7b897bc000p-3, -0x1.c79b60ae1ff0fp-47},
	{0x1.2bef98e5a3711p+0, -0x1.4462b9dc9b000p-3, -0x1.ede9d63b93e7ap-46},
	{0x1.2a91c92f3c105p+0, -0x1.3b08b6757f000p-3, -0x1.5485c35b37c15p-46},
	{0x1.293725bb804a5p+0, -0x1.31b994d3a5000p-3, 0x1.ece238b5efe06p-49},
	{0x1.27dfa38a1ce4dp+0, -0x1.28753bc11b000p-3, 0x1.16d6394d9fa33p-45},
	{0x1.268b37cd60127p+0, -0x1.1f3b925f26000p-3, 0x1.5f74e9b083633p-46},
	{0x1.2539d7e9177b2p+0, -0x1.160c8024b2000p-3, -0x1.ec2d2a9009e3dp-45},
	{0x1.23eb79717605bp+0, -0x1.0ce7ecdccc000p-3, -0x1.4652dabff5447p-46},
	{0x1.22a0122a0122ap+0, -0x1.03cdc0a51f000p-3, 0x1.f958c3a580e90p-46},
	{0x1.21579804855e6p+0, -0x1.f57bc7d900000p-4, -0x1.76a6c9ea8b04ep-46},
	{0x1.2012012012012p+0, -0x1.e3707ee304000p-4, -0x1.0f684e6766abdp-45},
	{0x1.1ecf43c7fb84cp+0, -0x1.d17978821a000p-4, 0x1.9379894208225p-45},
	{0x1.1d8f5672e4abdp+0, -0x1.bf968769fc000p-4, -0x1.4218c8d824283p-45},
	{0x1.1c522fc1ce059p+0, -0x1.adc77ee5ae000p-4, -0x1.5189bec79cdf7p-45},
	{0x1.1b17c67f2bae3p+0, -0x1.9c0c32d4d2000p-4, -0x1.520fd85f1e661p-46},
	{0x1.19e0119e0119ep+0, -0x1.8a6477a91e000p-4, 0x1.eb9fa83214905p-47},
	{0x1.18ab083902bdbp+0, -0x1.78d02263d8000p-4, -0x1.69b5794b69fb7p-47},
	{0x1.1778a191bd684p+0, -0x1.674f089366000p-4, 0x1.6199acd8b33f9p-46},
	{0x1.1648d50fc3201p+0, -0x1.55e10050e0000p-4, -0x1.c1d740c53c72ep-47},
	{0x1.151b9a3fdd5c9p+0, -0x1.4485e03dbe000p-4, 0x1.4ae45cb655244p-50},
	{0x1.13f0e8d344724p+0, -0x1.333d7f8184000p-4, 0x1.692b6a81b8848p-49},
	{0x1.12c8b89edc0acp+0, -0x1.2207b5c786000p-4, 0x1.6c4e607de7082p-45},
	{0x1.11a3019a74826p+0, -0x1.10e45b3cae000p-4, -0x1.0612daf6b9737p-45},
	{0x1.107fbbe011080p+0, -0x1.ffa6911ab8000p-5, -0x1.3008c98381a8fp-45},
	{0x1.0f5edfab325a2p+0, -0x1.dda8adc680000p-5, 0x1.1b1ac64d9e42fp-45},
	{0x1.0e40655826011p+0, -0x1.bbcebfc690000p-5, 0x1.7bf868c317c2ap-46},
	{0x1.0d24456359e3ap+0, -0x1.9a187b573c000p-5, -0x1.e7ba362764de5p-45},
	{0x1.0c0a7868b4171p+0, -0x1.788595a358000p-5, 0x1.08b0d083b3a4cp-46},
	{0x1.0af2f722eecb5p+0, -0x1.5715c4c03c000p-5, -0x1.dddc880ee2760p-46},
	{0x1.09ddba6af8360p+0, -0x1.35c8bfaa14000p-5, 0x1.f2a0a8418532bp-46},
	{0x1.08cabb37565e2p+0, -0x1.149e3e4004000p-5, -0x1.a8ceacb7d2e06p-45},
	{0x1.07b9f29b8eae2p+0, -0x1.e72bf28140000p-6, 0x1.8d75149774d47p-45},
	{0x1.06ab59c7912fbp+0, -0x1.a55f548c60000p-6, 0x1.de0709f2d03c9p-45},
	{0x1.059eea0727586p+0, -0x1.63d6178690000p-6, -0x1.7abf389596542p-47},
	{0x1.04949cc1664c5p+0, -0x1.228fb1fea0000p-6, -0x1.713e3284991fep-45},
	{0x1.038c6b78247fcp+0, -0x1.c317384c70000p-7, -0x1.7c19806208c05p-45},
	{0x1.02864fc7729e9p+0, -0x1.41929f9680000p-7, -0x1.977c755d01368p-46},
	{0x1.0182436517a37p+0, -0x1.8121214580000p-8, -0x1.ad50382973f27p-46},
	{0x1.0080402010080p+0, -0x1.0040155d40000p-9, -0x1.889de70671eefp-45},
	{0x1.fe01fe01fe020p-1, 0x1.ff00aa2b00000p-9, 0x1.0bc04a086b56ap-45},
	{0x1.fa11caa01fa12p-1, 0x1.7dc475f810000p-7, 0x1.4edba4a25e0b1p-48},
	{0x1.f6310aca0dbb5p-1, 0x1.3cea443468000p-6, 0x1.2ba779a52b7eap-45},
	{0x1.f25f644230ab5p-1, 0x1.b9fc027af8000p-6, 0x1.197fbd465b759p-46},
	{0x1.ee9c7f8458e02p-1, 0x1.1b0d98923c000p-5, 0x1.97fc2ca2eec8ap-45},
	{0x1.eae807aba01ebp-1, 0x1.58a5bafc90000p-5, -0x1.b2b739570ad39p-45},
	{0x1.e741aa59750e4p-1, 0x1.95c830ec90000p-5, -0x1.c148297c5feb8p-45},
	{0x1.e3a9179dc1a73p-1, 0x1.d276b8adb0000p-5, 0x1.6a423c78a64b0p-46},
	{0x1.e01e01e01e01ep-1, 0x1.075983598e000p-4, 0x1.1c4c06d2999e2p-46},
	{0x1.dca01dca01dcap-1, 0x1.253f62f0a2000p-4, -0x1.7d20e092cb1fep-45},
	{0x1.d92f2231e7f8ap-1, 0x1.42edcbea64000p-4, 0x1.bc0eeea7c9acdp-46},
	{0x1.d5cac807572b2p-1, 0x1.60658a9376000p-4, -0x1.e789c422c7611p-45},
	{0x1.d272ca3fc5b1ap-1, 0x1.7da766d7b2000p-4, -0x1.a66f776fe6ecap-45},
	{0x1.cf26e5c44bfc6p-1, 0x1.9ab4246204000p-4, -0x1.8a64826787061p-45},
	{0x1.cbe6d9601cbe7p-1, 0x1.b78c82bb0e000p-4, 0x1.b4210878cf032p-45},
	{0x1.c8b265afb8a42p-1, 0x1.d4313d66cc000p-4, -0x1.9454379135713p-45},
	{0x1.c5894d10d4986p-1, 0x1.f0a30c0116000p-4, 0x1.5330be64b8b77p-47},
	{0x1.c26b5392ea01cp-1, 0x1.0671512ca6000p-3, -0x1.a47579cdc0a3dp-45},
	{0x1.bf583ee868d8bp-1, 0x1.1478584674000p-3, 0x1.563451027c750p-46},
	{0x1.bc4fd65883e7bp-1, 0x1.2266f190a6000p-3, -0x1.4d20ab840e7f6p-45},
	{0x1.b951e2b18ff23p-1, 0x1.303d718e48000p-3, -0x1.680b5ce3ecb05p-50},
	{0x1.b65e2e3beee05p-1, 0x1.3dfc2b0ecc000p-3, 0x1.8a72a62b8c13fp-45},
	{0x1.b37484ad806cep-1, 0x1.4ba36f39a5000p-3, 0x1.79568981bcc36p-45},
	{0x1.b094b31d922a4p-1, 0x1.59338d9982000p-3, 0x1.0ba68b7555d4ap-48},
	{0x1.adbe87f94905ep-1, 0x1.66acd4272b000p-3, -0x1.5790900e4e1ebp-46},
	{0x1.aaf1d2f87ebfdp-1, 0x1.740f8f5403000p-3, 0x1.e9326cdfceabep-45},
	{0x1.a82e65130e159p-1, 0x1.815c0a1435000p-3, 0x1.fab5a0dbfc630p-45},
	{0x1.a574107688a4ap-1, 0x1.8e928de887000p-3, -0x1.5faad3b0a34adp-46},
	{0x1.a2c2a87c51ca0p-1, 0x1.9bb362e7e0000p-3, -0x1.1f2a8a1ce0ffcp-45},
	{0x1.a01a01a01a01ap-1, 0x1.a8becfc883000p-3, -0x1.ce7a30de4630ep-48},
	{0x1.9d79f176b682dp-1, 0x1.b5b519e8fb000p-3, 0x1.691ba27fdc19ep-45},
	{0x1.9ae24ea5510dap-1, 0x1.c2968558c2000p-3, -0x1.cfd73dee38a40p-45},
	{0x1.9852f0d8ec0ffp-1, 0x1.cf6354e09c000p-3, 0x1.771239a07d55bp-45},
	{0x1.95cbb0be377aep-1, 0x1.dc1bca0abf000p-3, -0x1.c14f9675ccce9p-46},
	{0x1.934c67f9b2ce6p-1, 0x1.e8c0252aa6000p-3, -0x1.6805b80e8e6ffp-45},
	{0x1.90d4f120190d5p-1, 0x1.f550a564b8000p-3, -0x1.323e3a09202fep-45},
	{0x1.8e6527af1373fp-1, 0x1.00e6c45ad5000p-2, 0x1.cc68d52e01203p-50},
	{0x1.8bfce8062ff3ap-1, 0x1.071b85fcd5800p-2, 0x1.0d1d1707f97bep-46},
	{0x1.899c0f601899cp-1, 0x1.0d46b579ab800p-2, -0x1.69bf04df8f0d1p-47},
	{0x1.87427bcc092b9p-1, 0x1.136870293a800p-2, 0x1.60bdb314c76e9p-47},
	{0x1.84f00c2780614p-1, 0x1.1980d2dd42000p-2, 0x1.b7b3a7a361c9ap-45},
	{0x1.82a4a0182a4a0p-1, 0x1.1f8ff9e48a000p-2, 0x1.7946c040cbe77p-45},
	{0x1.8060180601806p-1, 0x1.2596010df7800p-2, -0x1.c610f76c57076p-46},
	{0x1.7e225515a4f1dp-1, 0x1.2b9303ab8a000p-2, -0x1.6db12d6bfb0a5p-45},
	{0x1.7beb3922e017cp-1, 0x1.31871c9544000p-2, 0x1.84fab94cecfd9p-46},
	{0x1.79baa6bb6398bp-1, 0x1.3772662bfd800p-2, 0x1.6bc953ac4fdd0p-48},
	{0x1.77908119ac60dp-1, 0x1.3d54fa5c1f800p-2, -0x1.e0f1932e350e5p-47},
	{0x1.756cac201756dp-1, 0x1.432ef2a04e800p-2, 0x1.3b59b3a3a94dcp-50},
}
