#!/usr/bin/env python3
"""Regenerate the streaming digest cores in internal/stdlib/std/crypto.fern.

    python3 tools/gen_digests.py

The block functions of MD5, SHA-1, SHA-256, SHA-512 and BLAKE2b are round
loops unrolled with the working variables renamed per round and the message
schedule held as a rolling window of locals, so the hot loop touches no array
but the input and every round constant is an immediate. That is the shape a C
implementation gets from macros; Fern has none, so the source is generated
here and committed. The output replaces everything between the
`// >>> generated by tools/gen_digests.py` and `// <<< generated` markers; the
text outside the markers is hand-written.
"""
import math
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
TARGET = os.path.join(ROOT, "internal", "stdlib", "std", "crypto.fern")
BEGIN = "// >>> generated by tools/gen_digests.py — do not edit by hand"
END = "// <<< generated"

SHA256_K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

SHA512_K = [
    0x428a2f98d728ae22, 0x7137449123ef65cd, 0xb5c0fbcfec4d3b2f, 0xe9b5dba58189dbbc, 0x3956c25bf348b538,
    0x59f111f1b605d019, 0x923f82a4af194f9b, 0xab1c5ed5da6d8118, 0xd807aa98a3030242, 0x12835b0145706fbe,
    0x243185be4ee4b28c, 0x550c7dc3d5ffb4e2, 0x72be5d74f27b896f, 0x80deb1fe3b1696b1, 0x9bdc06a725c71235,
    0xc19bf174cf692694, 0xe49b69c19ef14ad2, 0xefbe4786384f25e3, 0x0fc19dc68b8cd5b5, 0x240ca1cc77ac9c65,
    0x2de92c6f592b0275, 0x4a7484aa6ea6e483, 0x5cb0a9dcbd41fbd4, 0x76f988da831153b5, 0x983e5152ee66dfab,
    0xa831c66d2db43210, 0xb00327c898fb213f, 0xbf597fc7beef0ee4, 0xc6e00bf33da88fc2, 0xd5a79147930aa725,
    0x06ca6351e003826f, 0x142929670a0e6e70, 0x27b70a8546d22ffc, 0x2e1b21385c26c926, 0x4d2c6dfc5ac42aed,
    0x53380d139d95b3df, 0x650a73548baf63de, 0x766a0abb3c77b2a8, 0x81c2c92e47edaee6, 0x92722c851482353b,
    0xa2bfe8a14cf10364, 0xa81a664bbc423001, 0xc24b8b70d0f89791, 0xc76c51a30654be30, 0xd192e819d6ef5218,
    0xd69906245565a910, 0xf40e35855771202a, 0x106aa07032bbd1b8, 0x19a4c116b8d2d0c8, 0x1e376c085141ab53,
    0x2748774cdf8eeb99, 0x34b0bcb5e19b48a8, 0x391c0cb3c5c95a63, 0x4ed8aa4ae3418acb, 0x5b9cca4f7763e373,
    0x682e6ff3d6b2b8a3, 0x748f82ee5defb2fc, 0x78a5636f43172f60, 0x84c87814a1f0ab72, 0x8cc702081a6439ec,
    0x90befffa23631e28, 0xa4506cebde82bde9, 0xbef9a3f7b2c67915, 0xc67178f2e372532b, 0xca273eceea26619c,
    0xd186b8c721c0c207, 0xeada7dd6cde0eb1e, 0xf57d4f7fee6ed178, 0x06f067aa72176fba, 0x0a637dc5a2c898a6,
    0x113f9804bef90dae, 0x1b710b35131c471b, 0x28db77f523047d84, 0x32caab7b40c72493, 0x3c9ebe0a15c9bebc,
    0x431d67c49c100d4c, 0x4cc5d4becb3e42b6, 0x597f299cfc657e2a, 0x5fcb6fab3ad6faec, 0x6c44198c4a475817,
]

SHA512_IV = [0x6a09e667f3bcc908, 0xbb67ae8584caa73b, 0x3c6ef372fe94f82b, 0xa54ff53a5f1d36f1,
             0x510e527fade682d1, 0x9b05688c2b3e6c1f, 0x1f83d9abfb41bd6b, 0x5be0cd19137e2179]
SHA384_IV = [0xcbbb9d5dc1059ed8, 0x629a292a367cd507, 0x9159015a3070dd17, 0x152fecd8f70e5939,
             0x67332667ffc00b31, 0x8eb44a8768581511, 0xdb0c2e0d64f98fa7, 0x47b5481dbefa4fa4]
SHA256_IV = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]
SHA224_IV = [0xc1059ed8, 0x367cd507, 0x3070dd17, 0xf70e5939, 0xffc00b31, 0x68581511, 0x64f98fa7, 0xbefa4fa4]
SHA1_IV = [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0]
MD5_IV = [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476]
MD5_K = [int(abs(math.sin(i + 1)) * (1 << 32)) & 0xffffffff for i in range(64)]
MD5_S = [7, 12, 17, 22] * 4 + [5, 9, 14, 20] * 4 + [4, 11, 16, 23] * 4 + [6, 10, 15, 21] * 4

BLAKE2B_SIGMA = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
    [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
    [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
    [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
    [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
    [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
    [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
    [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
]


def u64(v):
    return f"(0x{v:016x} as u64)"


def sh(n, width):
    return str(n) if width == 32 else f"({n} as u64)"


def rotr(x, n, width):
    return f"(({x} >> {sh(n, width)}) | ({x} << {sh(width - n, width)}))"


def rotl(x, n, width):
    return rotr(x, width - n, width)


def const(v, width):
    return f"0x{v:08x}" if width == 32 else u64(v)


def load_word(i, bpw, big_endian, ty, width):
    """Expression assembling word i of the block at `off` from bs."""
    parts = []
    for j in range(bpw):
        shift = 8 * (bpw - 1 - j) if big_endian else 8 * j
        pos = i * bpw + j
        idx = f"off + {pos}" if pos else "off"
        term = f"(bs[{idx}] as {ty})"
        if shift:
            term = f"({term} << {sh(shift, width)})"
        parts.append(term)
    return " | ".join(parts)


def emit_family(p, *, tag, struct, ty, width, nwords, block, len_bytes, big_endian, ivs, rounds_body, doc):
    """Everything but the block function's round body: struct, constructors,
    absorb, update, final and the one-shot wrappers. `ivs` maps a constructor
    name to (iv words, output length)."""
    zero = "0" if width == 32 else "(0 as u64)"
    p(f"// === {doc} ===")
    p("")
    p(f"pub struct {struct} {{")
    for i in range(nwords):
        p(f"    h{i}: {ty},")
    p(f"    // Pending partial block ({block} bytes, `buf_len` of them live) and the byte count.")
    p("    buf: u8[],")
    p("    buf_len: i32,")
    p("    total: u64,")
    p("    out_len: i32")
    p("}")
    p("")
    for name, (iv, out_len) in ivs.items():
        p(f"pub function {name}(): {struct} {{")
        fields = ", ".join(f"h{i}: {const(v, width)}" for i, v in enumerate(iv))
        p(f"    return {struct} {{ {fields},")
        p(f"        buf: __zero_u8({block}), buf_len: 0, total: 0 as u64, out_len: {out_len} }};")
        p("}")
        p("")
    p(f"// __{tag}_blocks folds `nblocks` {block}-byte blocks of `bs`, starting at byte")
    p(f"// `from`, into the state. Generated: the rounds are unrolled with the working")
    p(f"// variables renamed per round and the message schedule a rolling window of")
    p(f"// locals, so the loop touches no array but the input.")
    p(f"function __{tag}_blocks(st: {struct}, bs: [u8], from: i32, nblocks: i32): {struct} {{")
    rounds_body(p)
    fields = ", ".join(f"h{i}: {'abcdefgh'[i]}" for i in range(nwords))
    p(f"    return {struct} {{ ...st, {fields} }};")
    p("}")
    p("")
    p(f"function __{tag}_absorb(own h: {struct}, bs: [u8]): {struct} {{")
    p("    var n: i32 = bs.len();")
    p("    var pos: i32 = 0;")
    p("    var bl: i32 = h.buf_len;")
    p("    if (bl > 0) {")
    p(f"        var take: i32 = {block} - bl;")
    p("        if (take > n) { take = n; }")
    p(f"        h = {struct} {{ ...h, buf: __copy_in(h.buf, bl, bs, 0, take) }};")
    p("        bl = bl + take;")
    p("        pos = take;")
    p(f"        if (bl == {block}) {{")
    p(f"            h = __{tag}_blocks(h, h.buf, 0, 1);")
    p("            bl = 0;")
    p("        }")
    p("    }")
    p(f"    var nb: i32 = (n - pos) / {block};")
    p("    if (nb > 0) {")
    p(f"        h = __{tag}_blocks(h, bs, pos, nb);")
    p(f"        pos = pos + nb * {block};")
    p("    }")
    p("    if (pos < n) {")
    p(f"        h = {struct} {{ ...h, buf: __copy_in(h.buf, bl, bs, pos, n - pos) }};")
    p("        bl = bl + (n - pos);")
    p("    }")
    p(f"    return {struct} {{ ...h, buf_len: bl, total: h.total + (n as u64) }};")
    p("}")
    p("")
    emit_update(p, struct, tag)
    p(f"pub function (h: {struct}) final_bytes(): u8[] {{")
    p("    var bl: i32 = h.buf_len;")
    p(f"    var plen: i32 = {block};")
    p(f"    if (bl >= {block - len_bytes}) {{ plen = {2 * block}; }}")
    p("    var pad: u8[] = __copy_in(__zero_u8(plen), 0, h.buf, 0, bl);")
    p("    pad = pad.with(bl, 0x80 as u8);")
    p("    var bits: u64 = h.total << (3 as u64);")
    if big_endian:
        p("    pad = __put_be64(pad, plen - 8, bits);")
    else:
        p("    pad = __put_le64(pad, plen - 8, bits);")
    p(f"    var st: {struct} = __{tag}_blocks(h, pad, 0, plen / {block});")
    p("    var out: u8[] = __alloc_u8(st.out_len);")
    bpw = width // 8
    put = ("__put_be" if big_endian else "__put_le") + str(width)
    for i in range(nwords):
        line = f"out = {put}(out, {i * bpw}, st.h{i});"
        if (i + 1) * bpw > min(v[1] for v in ivs.values()):
            p(f"    if (st.out_len >= {(i + 1) * bpw}) {{ {line} }}")
        else:
            p(f"    {line}")
    p("    return out;")
    p("}")
    p("")
    p(f"pub function (h: {struct}) final_hex(): string {{")
    p("    return __bytes_to_hex(h.final_bytes());")
    p("}")
    p("")
    for name in ivs:
        base = name[: -len("_new")]
        p(f"// {base}_bytes / {base}_hex — the one-shot digest of `s`.")
        p(f"pub function {base}_bytes(s: string): u8[] {{")
        p(f"    return {name}().update(s).final_bytes();")
        p("}")
        p("")
        p(f"pub function {base}_hex(s: string): string {{")
        p(f"    return __bytes_to_hex({name}().update(s).final_bytes());")
        p("}")
        p("")


def emit_update(p, struct, tag):
    p(f"// update / update_bytes absorb a chunk of arbitrary length — a string, or a")
    p(f"// `[u8]` view (a `u8[]` lends itself, `arr[a:b]` slices one). Rebind the result")
    p(f"// (`h = h.update(chunk)`): the state is a value, and the rebind is what lets the")
    p(f"// pending block be reused in place rather than copied.")
    p(f"pub function (h: {struct}) update(chunk: string): {struct} {{")
    p(f"    h = __{tag}_absorb(h, chunk.as_bytes());")
    p("    return h;")
    p("}")
    p("")
    p(f"pub function (h: {struct}) update_bytes(chunk: [u8]): {struct} {{")
    p(f"    h = __{tag}_absorb(h, chunk);")
    p("    return h;")
    p("}")
    p("")


def sha2_rounds(width, rounds, K, bs0, bs1, ss0, ss1):
    ty = "u32" if width == 32 else "u64"
    bpw = width // 8
    names = list("abcdefgh")

    def body(p):
        for i, n in enumerate(names):
            p(f"    var {n}: {ty} = st.h{i};")
        for i in range(16):
            p(f"    var w{i}: {ty} = {'0' if width == 32 else '(0 as u64)'};")
        p("    var off: i32 = from;")
        p("    var blk: i32 = 0;")
        p("    while (blk < nblocks) {")
        for i in range(16):
            p(f"        w{i} = {load_word(i, bpw, True, ty, width)};")
        for n in names:
            p(f"        var {n}{n}: {ty} = {n};")
        work = [n + n for n in names]
        for i in range(rounds):
            A, B, C, D, E, F, G, H = [work[(k - i) % 8] for k in range(8)]
            w = f"w{i % 16}"
            if i >= 16:
                w15, w2, w7 = f"w{(i - 15) % 16}", f"w{(i - 2) % 16}", f"w{(i - 7) % 16}"
                s0 = " ^ ".join([rotr(w15, ss0[0], width), rotr(w15, ss0[1], width), f"({w15} >> {sh(ss0[2], width)})"])
                s1 = " ^ ".join([rotr(w2, ss1[0], width), rotr(w2, ss1[1], width), f"({w2} >> {sh(ss1[2], width)})"])
                p(f"        {w} = {w} + ({s0}) + {w7} + ({s1});")
            sig1 = " ^ ".join(rotr(E, r, width) for r in bs1)
            sig0 = " ^ ".join(rotr(A, r, width) for r in bs0)
            p(f"        {H} = {H} + ({sig1}) + ({G} ^ ({E} & ({F} ^ {G}))) + {const(K[i], width)} + {w};")
            p(f"        {D} = {D} + {H};")
            p(f"        {H} = {H} + ({sig0}) + ((({A} ^ {B}) & {C}) ^ ({A} & {B}));")
        for n in names:
            p(f"        {n} = {n} + {n}{n};")
        p(f"        off = off + {16 * bpw};")
        p("        blk = blk + 1;")
        p("    }")
    return body


def sha1_rounds(p):
    names = list("abcde")
    for i, n in enumerate(names):
        p(f"    var {n}: u32 = st.h{i};")
    for i in range(16):
        p(f"    var w{i}: u32 = 0;")
    p("    var off: i32 = from;")
    p("    var blk: i32 = 0;")
    p("    while (blk < nblocks) {")
    for i in range(16):
        p(f"        w{i} = {load_word(i, 4, True, 'u32', 32)};")
    for n in names:
        p(f"        var {n}{n}: u32 = {n};")
    work = [n + n for n in names]
    for i in range(80):
        A, B, C, D, E = [work[(k - i) % 5] for k in range(5)]
        w = f"w{i % 16}"
        if i >= 16:
            x = f"({w} ^ w{(i - 14) % 16} ^ w{(i - 8) % 16} ^ w{(i - 3) % 16})"
            p(f"        {w} = {rotl(x, 1, 32)};")
        if i < 20:
            f, k = f"({D} ^ ({B} & ({C} ^ {D})))", 0x5a827999
        elif i < 40:
            f, k = f"({B} ^ {C} ^ {D})", 0x6ed9eba1
        elif i < 60:
            f, k = f"((({B} ^ {C}) & {D}) ^ ({B} & {C}))", 0x8f1bbcdc
        else:
            f, k = f"({B} ^ {C} ^ {D})", 0xca62c1d6
        p(f"        {E} = {E} + {rotl(A, 5, 32)} + {f} + 0x{k:08x} + {w};")
        p(f"        {B} = {rotl(B, 30, 32)};")
    for n in names:
        p(f"        {n} = {n} + {n}{n};")
    p("        off = off + 64;")
    p("        blk = blk + 1;")
    p("    }")


def md5_rounds(p):
    names = list("abcd")
    for i, n in enumerate(names):
        p(f"    var {n}: u32 = st.h{i};")
    for i in range(16):
        p(f"    var x{i}: u32 = 0;")
    p("    var off: i32 = from;")
    p("    var blk: i32 = 0;")
    p("    while (blk < nblocks) {")
    for i in range(16):
        p(f"        x{i} = {load_word(i, 4, False, 'u32', 32)};")
    for n in names:
        p(f"        var {n}{n}: u32 = {n};")
    work = [n + n for n in names]
    for i in range(64):
        A, B, C, D = [work[(k - i) % 4] for k in range(4)]
        if i < 16:
            f, k = f"({D} ^ ({B} & ({C} ^ {D})))", i
        elif i < 32:
            f, k = f"({C} ^ ({D} & ({B} ^ {C})))", (5 * i + 1) % 16
        elif i < 48:
            f, k = f"({B} ^ {C} ^ {D})", (3 * i + 5) % 16
        else:
            f, k = f"({C} ^ ({B} | ({D} ^ 0xffffffff)))", (7 * i) % 16
        t = f"({A} + {f} + 0x{MD5_K[i]:08x} + x{k})"
        p(f"        {A} = {B} + {rotl(t, MD5_S[i], 32)};")
    for n in names:
        p(f"        {n} = {n} + {n}{n};")
    p("        off = off + 64;")
    p("        blk = blk + 1;")
    p("    }")


def emit_blake2b(p):
    p("// === BLAKE2b (RFC 7693), unkeyed, digest length 1..64 bytes ===")
    p("")
    p("pub struct Blake2b {")
    for i in range(8):
        p(f"    h{i}: u64,")
    p("    // Pending block (up to 128 bytes live) and the count of bytes already")
    p("    // compressed — BLAKE2b holds a full block back until more input arrives,")
    p("    // since the last block is compressed with the final flag set.")
    p("    buf: u8[],")
    p("    buf_len: i32,")
    p("    total: u64,")
    p("    out_len: i32")
    p("}")
    p("")
    p("// blake2b_new(out_len) — a hasher producing an `out_len`-byte digest (1..64).")
    p("// b2sum's default is 64; `-l N` is N bits, so pass N / 8.")
    p("pub function blake2b_new(out_len: i32): Blake2b {")
    p("    var n: i32 = out_len;")
    p("    if (n < 1) { n = 1; }")
    p("    if (n > 64) { n = 64; }")
    fields = ", ".join(f"h{i}: {u64(v)}" for i, v in enumerate(SHA512_IV))
    p(f"    var h: Blake2b = Blake2b {{ {fields},")
    p("        buf: __zero_u8(128), buf_len: 0, total: 0 as u64, out_len: n };")
    p("    // Parameter block word 0: digest length, key length 0, fanout 1, depth 1.")
    p("    return Blake2b { ...h, h0: h.h0 ^ (0x01010000 as u64) ^ (n as u64) };")
    p("}")
    p("")
    p("// __blake2b_blocks compresses `nblocks` 128-byte blocks of `bs` from byte")
    p("// `from`; `t` is the byte counter after the first of them (it advances 128 per")
    p("// block) and `last` marks the final block of the message. Generated, like the")
    p("// SHA cores: the 12 rounds are unrolled over 16 state locals and 16 message")
    p("// locals with the sigma permutation applied at generation time.")
    p("function __blake2b_blocks(st: Blake2b, bs: [u8], from: i32, nblocks: i32, t: u64, last: boolean): Blake2b {")
    for i in range(8):
        p(f"    var h{i}: u64 = st.h{i};")
    for i in range(16):
        p(f"    var m{i}: u64 = 0 as u64;")
    for i in range(16):
        p(f"    var v{i}: u64 = 0 as u64;")
    p("    var counter: u64 = t;")
    p("    var off: i32 = from;")
    p("    var blk: i32 = 0;")
    p("    while (blk < nblocks) {")
    for i in range(16):
        p(f"        m{i} = {load_word(i, 8, False, 'u64', 64)};")
    for i in range(8):
        p(f"        v{i} = h{i};")
    for i in range(8):
        p(f"        v{i + 8} = {u64(SHA512_IV[i])};")
    p("        v12 = v12 ^ counter;")
    p("        if (last && blk == nblocks - 1) { v14 = v14 ^ (0xffffffffffffffff as u64); }")
    for r in range(12):
        s = BLAKE2B_SIGMA[r % 10]
        for gi, (a, b, c, d) in enumerate([(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
                                           (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]):
            x, y = f"m{s[2 * gi]}", f"m{s[2 * gi + 1]}"
            va, vb, vc, vd = f"v{a}", f"v{b}", f"v{c}", f"v{d}"
            p(f"        {va} = {va} + {vb} + {x};")
            p(f"        {vd} = {rotr(f'({vd} ^ {va})', 32, 64)};")
            p(f"        {vc} = {vc} + {vd};")
            p(f"        {vb} = {rotr(f'({vb} ^ {vc})', 24, 64)};")
            p(f"        {va} = {va} + {vb} + {y};")
            p(f"        {vd} = {rotr(f'({vd} ^ {va})', 16, 64)};")
            p(f"        {vc} = {vc} + {vd};")
            p(f"        {vb} = {rotr(f'({vb} ^ {vc})', 63, 64)};")
    for i in range(8):
        p(f"        h{i} = h{i} ^ v{i} ^ v{i + 8};")
    p("        counter = counter + (128 as u64);")
    p("        off = off + 128;")
    p("        blk = blk + 1;")
    p("    }")
    fields = ", ".join(f"h{i}: h{i}" for i in range(8))
    p(f"    return Blake2b {{ ...st, {fields} }};")
    p("}")
    p("")
    p("function __blake2b_absorb(own h: Blake2b, bs: [u8]): Blake2b {")
    p("    var n: i32 = bs.len();")
    p("    if (n == 0) { return h; }")
    p("    var pos: i32 = 0;")
    p("    var bl: i32 = h.buf_len;")
    p("    var total: u64 = h.total;")
    p("    // Only compress once the input runs past a full block: the block that")
    p("    // ends the message must be the one compressed with `last` set.")
    p("    if (bl + n > 128) {")
    p("        var take: i32 = 128 - bl;")
    p("        if (take > 0) { h = Blake2b { ...h, buf: __copy_in(h.buf, bl, bs, 0, take) }; }")
    p("        total = total + (128 as u64);")
    p("        h = __blake2b_blocks(h, h.buf, 0, 1, total, false);")
    p("        bl = 0;")
    p("        pos = take;")
    p("        var nb: i32 = (n - pos - 1) / 128;")
    p("        if (nb > 0) {")
    p("            h = __blake2b_blocks(h, bs, pos, nb, total + (128 as u64), false);")
    p("            total = total + ((nb * 128) as u64);")
    p("            pos = pos + nb * 128;")
    p("        }")
    p("    }")
    p("    h = Blake2b { ...h, buf: __copy_in(h.buf, bl, bs, pos, n - pos) };")
    p("    return Blake2b { ...h, buf_len: bl + (n - pos), total: total };")
    p("}")
    p("")
    emit_update(p, "Blake2b", "blake2b")
    p("pub function (h: Blake2b) final_bytes(): u8[] {")
    p("    var bl: i32 = h.buf_len;")
    p("    // The tail of the block must be zero; the buffer may hold stale bytes.")
    p("    var pad: u8[] = __copy_in(__zero_u8(128), 0, h.buf, 0, bl);")
    p("    var st: Blake2b = __blake2b_blocks(h, pad, 0, 1, h.total + (bl as u64), true);")
    p("    var full: u8[] = __alloc_u8(64);")
    for i in range(8):
        p(f"    full = __put_le64(full, {8 * i}, st.h{i});")
    p("    if (st.out_len == 64) { return full; }")
    p("    return __copy_in(__alloc_u8(st.out_len), 0, full, 0, st.out_len);")
    p("}")
    p("")
    p("pub function (h: Blake2b) final_hex(): string {")
    p("    return __bytes_to_hex(h.final_bytes());")
    p("}")
    p("")
    p("// blake2b_bytes / blake2b_hex — the one-shot `out_len`-byte digest of `s`.")
    p("pub function blake2b_bytes(s: string, out_len: i32): u8[] {")
    p("    return blake2b_new(out_len).update(s).final_bytes();")
    p("}")
    p("")
    p("pub function blake2b_hex(s: string, out_len: i32): string {")
    p("    return __bytes_to_hex(blake2b_new(out_len).update(s).final_bytes());")
    p("}")
    p("")


def generate():
    out = []
    p = out.append
    p(BEGIN)
    p("")
    emit_family(p, tag="md5", struct="Md5", ty="u32", width=32, nwords=4, block=64, len_bytes=8,
                big_endian=False, ivs={"md5_new": (MD5_IV, 16)}, rounds_body=md5_rounds,
                doc="MD5 (RFC 1321)")
    emit_family(p, tag="sha1", struct="Sha1", ty="u32", width=32, nwords=5, block=64, len_bytes=8,
                big_endian=True, ivs={"sha1_new": (SHA1_IV, 20)}, rounds_body=sha1_rounds,
                doc="SHA-1 (RFC 3174)")
    emit_family(p, tag="sha256", struct="Sha256", ty="u32", width=32, nwords=8, block=64, len_bytes=8,
                big_endian=True, ivs={"sha256_new": (SHA256_IV, 32), "sha224_new": (SHA224_IV, 28)},
                rounds_body=sha2_rounds(32, 64, SHA256_K, (2, 13, 22), (6, 11, 25), (7, 18, 3), (17, 19, 10)),
                doc="SHA-224 / SHA-256 (FIPS 180-4) — one state type, the IV and output length differ")
    emit_family(p, tag="sha512", struct="Sha512", ty="u64", width=64, nwords=8, block=128, len_bytes=16,
                big_endian=True, ivs={"sha512_new": (SHA512_IV, 64), "sha384_new": (SHA384_IV, 48)},
                rounds_body=sha2_rounds(64, 80, SHA512_K, (28, 34, 39), (14, 18, 41), (1, 8, 7), (19, 61, 6)),
                doc="SHA-384 / SHA-512 (FIPS 180-4) — u64 arithmetic, 128-byte blocks")
    emit_blake2b(p)
    p(END)
    return "\n".join(out) + "\n"


def main():
    text = open(TARGET).read()
    start = text.index(BEGIN)
    end = text.index(END) + len(END) + 1
    text = text[:start] + generate() + text[end:]
    open(TARGET, "w").write(text)
    print(f"regenerated {os.path.relpath(TARGET, ROOT)}")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--print":
        sys.stdout.write(generate())
    else:
        main()
