package sourcelint

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// stdlibGroupsRe pulls the STDLIB_GROUPS literal out of site/astro.config.mjs.
// Parsing the config rather than duplicating the list here is the point: a
// second copy is a second thing to forget, which is the failure this test
// exists to catch.
var stdlibGroupsRe = regexp.MustCompile(`(?s)const STDLIB_GROUPS = \[(.*?)\n\];`)

var quotedRe = regexp.MustCompile(`"([^"]+)"`)

// Every module under internal/stdlib/std/ is named in the docs sidebar's
// STDLIB_GROUPS. A module that is not falls into the sidebar's "Other" bucket,
// which the docs Playwright suite asserts is empty — so the only thing catching
// an ungrouped module today is a ten-minute browser lane, forty minutes into
// CI. This is the same check in under a second.
//
// It is a drift guard of the shape this package already carries: a list
// maintained by hand in one place while the thing it describes grows somewhere
// else. The sidebar is deliberately hand-grouped rather than autogenerated
// (astro.config.mjs says why — an alphabetical run of ~70 pages is a list to
// scroll rather than a thing to browse), so the maintenance is the price of
// the grouping and this test is what makes it cheap.
func TestEveryStdlibModuleHasASidebarGroup(t *testing.T) {
	cfg, err := os.ReadFile(filepath.Join("..", "..", "site", "astro.config.mjs"))
	if err != nil {
		t.Fatalf("read astro.config.mjs: %v", err)
	}
	m := stdlibGroupsRe.FindSubmatch(cfg)
	if m == nil {
		t.Fatal("STDLIB_GROUPS not found in site/astro.config.mjs — if the sidebar stopped being hand-grouped, delete this test with the change that did it")
	}
	grouped := map[string]bool{}
	for _, q := range quotedRe.FindAllSubmatch(m[1], -1) {
		grouped[string(q[1])] = true
	}
	// The group LABELS are quoted in the same literal as the slugs. They are
	// harmless extras in the set — a label can never collide with a module,
	// since a module slug is a filename — so the set is only ever consulted
	// for membership, never enumerated.

	ents, err := os.ReadDir(filepath.Join("..", "..", "internal", "stdlib", "std"))
	if err != nil {
		t.Fatalf("read internal/stdlib/std: %v", err)
	}
	var missing []string
	for _, e := range ents {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".fern") {
			continue
		}
		slug := strings.TrimSuffix(name, ".fern")
		// `_test_empty` is a fixture, not a module anyone imports, and
		// ferndoc emits no page for it.
		if strings.HasPrefix(slug, "_") {
			continue
		}
		if !grouped[slug] {
			missing = append(missing, slug)
		}
	}
	if len(missing) != 0 {
		sort.Strings(missing)
		t.Errorf("stdlib modules with no STDLIB_GROUPS entry in site/astro.config.mjs: %s\n"+
			"Each falls into the sidebar's \"Other\" group, which site/test/playwright/docs.spec.ts asserts is empty — "+
			"so this lands as a red docs-build lane rather than as anything readable. Give each a group.",
			strings.Join(missing, ", "))
	}
}
